### ISSUE TITLE
Proper pixel storage support

### ISSUE THREAD

**Issue by mosra** [mosra/magnum#104]
Currently there is no support for `glPixelStorei()`, which means that we're always using the default pixel storage values. In most cases this is not a problem, but by default `GL_{UN,}PACK_ALIGNMENT` is 4, which means that size of each row of an image must be divisible by four (e.g. RGB image 7 pixels wide would be imported incorrectly).

Due to recent changes regarding compressed images, the `Trade::ImageData` now contains sized array instead of raw pointer without size information. The size is calculated with four-byte alignment in mind, which makes **all image importer tests fail** now because the importers currently don't respect alignment, the test images are oddly-sized and thus the calculated image data size is larger than expected.

What needs to be done:
- [x] store `glPixelStorei()` configuration for each `*Image` and `*CompressedImage`
- [x] state tracking for `glPixelStorei()`
- [x] respect pixel storage in texture upload, download and framebuffer reading functions
- [x] fix all image importers to either respect the alignment etc. (better) or reconfigure it when the input data have different properties (worse, but sometimes inevitable) -- that would finally fix the tests
- [x] change `Image`, `ImageView`, `BufferImage` and `Trade::ImageData` constructors and data setting calls to accept only sized array instead of raw pointer
- [x] assert that the data passed to images have *at least* the size that is required by the alignment etc.

**Comment by mosra** [comment]
This is still being worked on in the `pixelstorage-wip` branch, currently I have pixel store configuration for each image, state tracking and new image constructors.

However, many aspects of pixel storage in GL are poorly documented and I'm now running into a lot of implementation-specific/undefined/buggy driver behavior.

**Comment by mosra** [comment]
Should be done in 232a8038e46875c10a47f14d8ed839ce3462ff0e and **sixteen** more commits before this one and mosra/magnum-plugins@e4f07b82869714494221345003b12b2a38738e9b and **nineteen** commits before that one. 

I hate these monster features that need to be there but otherwise nobody uses them directly. One month of deadly boring work. Ugh.
> 68 files changed, 4958 insertions(+), 2666 deletions(-)

Using `ARB_compressed_texture_pixel_storage` revealed a lot of underspecified/vague GL functionality regarding 3D compression (or I'm failing to understand those things (or there's a bug in my NVidia driver)). If anyone has an AMD card with this extension supported and is willing to test a few things for me, it will be *very* appreciated.

**Comment by LB--** [comment]
I have an AMD Radeon HD 7660G, how do I find out if I have that extension?

**Comment by mosra** [comment]
It's part of GL 4.2, so if you have updated drivers and sane platform (i.e. not OSX) it should be supported.

I'm interested in output of failing tests -- compile Magnum with `BUILD_TESTS=ON` and `BUILD_GL_TESTS=ON`, then run `ctest --output-on-failure` in build dir and upload the output somewhere.

Thanks a lot!

**Comment by LB--** [comment]
> 87% tests passed, 17 tests failed out of 129

Lots of "BlahTest.exe has stopped working" from Windows which I had to manually close each time they came up.

https://gist.github.com/LB--/922c4164bc870ed52a7e

**Comment by LB--** [comment]
Compiled and ran tests with VS2015, both 32bit and 64bit. This time some of the 'stopped working' dialogs were replaced with Abort/Retry/Ignore, to which I always chose Abort. The results were only slightly different.

32bit: https://gist.github.com/LB--/44c1584b61ca60d78fa5
64bit: (in progress)

Let me know if I need to do anything else.

**Comment by mosra** [comment]
Huh. It looks far worse than I expected.

I (hopefully) fixed majority of the minor issues with precision qualifiers (fef46953ec11dfd559e029e5fd361b6052c80477), so it should be now slightly more than 87%. I did a small fix for label queries (0c086b631b5e78b85a05d8a343736c3b313f1e91), but it is probably unrelated and looks like debug output needs to be enabled on context creation for proper function on AMD drivers.

The failing texture tests are alarming -- it looks like the test cases are failing completely randomly, sometimes the pixel storage parameters work only for PBO, sometimes only for client-side storage, sometimes only for compressed data... Another funny thing is that cases that were failing on NVidia are passing on AMD, so probably driver bugs.

Reopening as this needs more investigation from my side.

**Comment by LB--** [comment]
I pulled https://github.com/mosra/magnum/commit/03c8272aea9ff5d30131786d906427bd81c00f9b and re-did all the tests.
> 88% tests passed, 16 tests failed out of 129

nuwen MinGW: https://gist.github.com/LB--/9744f26f7d6fd89afd4b
VS2015 32bit: https://gist.github.com/LB--/0ca86b6979ae22ce04aa
VS2015 64bit: https://gist.github.com/LB--/2b89ee5d6ab2ca6f30dd

**Comment by LB--** [comment]
I have a new AMD A8-8650 Radeon R7 desktop running the latest beta drivers. I pulled https://github.com/mosra/magnum/commit/e6567af3641c790da679d5f1bc80c17c2d120a4d and got [basically the same test results](https://gist.github.com/LB--/fdbd404b2ca8d8b19ceb). So, at least I know my older graphics card isn't just completely broken.

**Comment by mosra** [comment]
Thank you for the continued effort!

I still don't know why the hell is it crashing inside all the `label()` tests. Just a random thought ... could you try the following patch?
```patch
diff --git a/src/Magnum/AbstractObject.cpp b/src/Magnum/AbstractObject.cpp
index a50bc03..a9ff8c2 100644
--- a/src/Magnum/AbstractObject.cpp
+++ b/src/Magnum/AbstractObject.cpp
@@ -161,7 +161,7 @@ std::string AbstractObject::getLabelImplementationNoOp(GLenum, GLuint) { return
 std::string AbstractObject::getLabelImplementationKhr(const GLenum identifier, const GLuint name) {
     /* Get label size (w/o null terminator). Specifying 0 as size is not
        allowed, thus we pass the maximum instead. */
-    GLsizei size;
+    GLsizei size = 0;
     #ifndef MAGNUM_TARGET_GLES
     glGetObjectLabel(identifier, name, maxLabelLength(), &size, nullptr);
     #elif !defined(CORRADE_TARGET_NACL)
@@ -189,7 +189,7 @@ std::string AbstractObject::getLabelImplementationKhr(const GLenum identifier, c
 }
 
 std::string AbstractObject::getLabelImplementationExt(const GLenum identifier, const GLuint name) {
-    GLsizei size;
+    GLsizei size = 0;
 
     /* Get label size (w/o null terminator) */
     #ifndef CORRADE_TARGET_NACL

```

**Comment by LB--** [comment]
> could you try the following patch?

It didn't make a difference, sorry.

**Comment by mosra** [comment]
I got a crappy AMD laptop at work, so I might be finally able to pinpoint and fix all these annoying issues.

**Comment by mosra** [comment]
Issues with tests not working properly/crashing on binary AMD drivers should be fixed with 4d67544fdaf902802791a2f6b6e96300af906195 and 16576552d24055804529c6f7a6b04518b781e0b8, so now only the annoying pixel storage issues remain.

**Comment by LB--** [comment]
Things have definitely improved, just 8 failing tests instead of 16: https://gist.github.com/LB--/9e747804b3e4844fdf5a

**Comment by LB--** [comment]
Down to 6 failing tests now! https://gist.github.com/LB--/cb3665d193d9c454544c

**Comment by mosra** [comment]
So what we have now, according to my tests:

- The `FramebufferGLTest` fails because AMD has a bug in `ARB_direct_state_access` implementation. Running the test with `--magnum-disable-extensions "GL_ARB_direct_state_access"` makes the test pass. I'll add a workaround.
- The `CubeMapGLTest` **crashes** on SIGFPE because AMD has another bug in `ARB_direct_state_access`. Disabling the extension fixes the crash (but 5 test cases still fail). Disabling also `GL_EXT_direct_state_access` magically reduces the failed test cases to just two. Aargh. I might need to add another workaround.
- `PrimitiveQueryGLTest` fails for unknown reason on AMD.
- Setting pixel storage causes the memory to be shifted somehow on AMD. I'm not experiencing these on Mesa or NV.
- Pixel storage and image queries on 3D and array textures is behaving differently from what I expect. This is present everywhere and I need to investigate.

**Comment by mosra** [comment]
Did a few improvements/workarounds related to compressed cubemap/array texture pixel storage in ~fifteen commits leading up to 5f8c32f05d06fc90423a4635b97bf923d6ad5e3f, but these were affecting mainly NVidia, so I don't expect any improvements elsewhere.

I so want to get rid of this already. Ugh.

**Comment by LB--** [comment]
Just tested, still [6 failing tests](https://gist.github.com/LB--/bc453cf8fc56752a42ef), but great work on getting everything working on NVidia, and happy new year!

**Comment by mosra** [comment]
Production use of this feature in the last months ironed out some last bugs (1cfd2dc7b5c361e10d36c4a5f6569646fc0e00b2, d998cb0f769854973412032ae673eaadfb5b3a84), thus I'm closing this as done.

Finally.
