### ISSUE TITLE
"Context: unsupported version string: 1.1.0" on nvidia gtx850m

### ISSUE THREAD

**Issue by Squareys** [mosra/magnum#105]
Hello @mosra !

A friend of mine is getting an "Context: unsupported version string: 1.1.0" on his nvidia gtx850m when running the magnum bullet example. Interestingly, **the motionblur example works fine** though.

We found out, when specifying `.setSampleCount(16);`, `tryCreateContext` errors out with that message for some reason.

Any ideas?

**Comment by mosra** [comment]
huh. 

This looks like it for some reason preferred software renderer with GL 1.1 for the multisampled context. I am interested in what the actual renderer was, could you print out also the renderer string [here](https://github.com/mosra/magnum/blob/0d02fdc1549fbd15a2392ba06eb46c3fa9d0bec4/src/Magnum/Context.cpp#L466) like this?

```cpp
Error() << "Context: unsupported version string:" << version << rendererString();
```

What OS is that? Does it have NVidia Optimus? Up-to-date drivers?

**Comment by HerleX** [comment]
Hello @mosra !

I am the mysterious friend. I changed the outputstring, so that the rendererstring will also be printed.
This is the output:

    Context: unsupported version string: 1.1.0 GDI Generic

I am working with Windows 7. Optimus is not running. All drivers are up-to-date.
Greetz.

**Comment by mosra** [comment]
Hah, software GDI renderer! That's the first time I see this and not exactly sure how to fix it. Looks like the GPU is not able to create 16x MSAA context so it falls back to software, which is **very** suspicious for GTX850M.

Did it print any message beforehand, for example something similar to the following?
> Platform::Sdl2Application::tryCreateContext(): cannot create core context (falling back to compatibility context)

If you run the motionblur example, it should print some short system info to the console (GPU name etc.), can you post that?

If you change the `setSampleCount(16)` line to just `setSampleCount(4)`, does the example start properly? What GPU does it report?

And last, can you post the output of `magnum-info --limits`?

Thanks.

**Comment by HerleX** [comment]
Hey. I found the problem. I used my Intel on-board graphiccard the whole time.
There isn't any message beforehand.

When i decrease the samplecount to 4 it is working.

Output of Magnum-info --limits:

http://prntscr.com/81kmsa
http://prntscr.com/81knai
http://prntscr.com/81knel
http://prntscr.com/81kniv

**Comment by mosra** [comment]
Great :)

I will decrease the sample count so it is able to work also on non-NVidia cards. In this case it should also properly do the fallback without MSAA, so that's a problem that should be fixed on my side too.

**Comment by mosra** [comment]
Heh, it took me whole two months to finally find a time for proper fix?

Proper fallback in *all* cases should be implemented in 277828ea444484abd4138fb7c9fd16f123438416. @HerleX could you please try running the Bullet example on Intel card with mosra/magnum-examples@888e395 reverted to see if it now works as expected? Thank you.

**Comment by HerleX** [comment]
Hello @mosra.

Sorry for not testing the update. I do not have a intel-card anymore.
Also do you know a method to get the examples working in a virtual machine?

Thank you.

**Comment by mosra** [comment]
Hi, if I remember correctly, I did test myself at some point and it was working for me.

If your virtual machine provides GPU virtualization, then it should "just work". Otherwise I'm not really sure. But even that, the best GPU virtualizations are supporting GL 3.3 at most, so pretty ancient.
