### ISSUE TITLE
Phong Shader and Alpha

### ISSUE THREAD

**Issue by Squareys** [mosra/magnum#112]
Hello @mosra !

I recently messed around with alpha blending, and I was just not able to get it working. In the end I had a look at the Phong shader and realized that it does not use alpha and forces it to `1.0f`.

I bet there is a design decision behind that, but for my use case (an alpha masked texture), it would be amazing, if the phong shader would use the textures alpha value rather than forcing to `1.0f`, if a texture is set (and possibly a `UseTextureAlpha` Flag or whatnot).

Is this something that could be added?

Thank you in advance!
Greetings, 
Squareys

**Comment by mosra** [comment]
Available for testing in `phong-alpha-mask` branch (commit 76b0f1e205f2ca58f96c2da71302cbd4658afbc1). Will merge into master if it works well enough for you.

**Comment by Squareys** [comment]
@mosra Yep, works well enough, thanks!

**Comment by mosra** [comment]
Merged into master then :)
