### ISSUE TITLE
Wrong name for libsdl2 dependency on Ubuntu 15.10

### ISSUE THREAD

**Issue by lynchs61** [mosra/magnum#119]
I installed this on Ubuntu 15.10 using the DEB packages. But the SDL2 dependency for magnum is listed in the control file as libsdl2. I'm not sure if it changed in a recent version but the package name is libsdl2-2.0-0. With the wrong name there's errors about the dependency not being available. Once it's changed to the correct package name dpkg installs magnum with no errors.

**Comment by lynchs61** [comment]
I can make the change and submit a pull request but I assume the dependency is listed as libsdl2 for a reason. Is this the name of the package on Debian?

**Comment by LB--** [comment]
Have you tried `sudo apt-get install libsdl2-dev`? I think that's how I got it building in my Ubuntu 15.10 virtual machine.

**Comment by mosra** [comment]
Hi, thanks for the report. The package was done in the times of Ubuntu 12.04, so I guess the names changed since (I had similar issues with Bullet). Fixed in bec686cec4d3a0a731d4334f523cb15a69f4bb24 to be `libsdl2-2.0-0` now.
