### ISSUE TITLE
attachCubeMapTexture issue

### ISSUE THREAD

**Issue by chpatrick** [mosra/magnum#123]
I'm trying to use `Framebuffer::attachCubeMapTexture` to attach a face of a cubemap, but in my apitrace I see that it calls `glNamedFramebufferTexture`, without specifying the appropriate texture target. My guess is that it's because it picks `texture2DImplementationDSA`, which doesn't seem appropriate in this situation.

**Comment by mosra** [comment]
Hi, sorry, somehow completely missed this one (GitHub is not sending e-mails about new issues, aargh). I guess it should call `glNamedFramebufferTextureLayer()`, right? Will look into it right now.

**Comment by mosra** [comment]
Should be fixed in 291b5bd3a82c3829d828af5f2f31ffe3725db37a, please reopen if there are any other problems. 

As a side note I now understand what layered attachments are (and why it didn't report any GL error), so I should be able to implement support for these now as well.

**Comment by mosra** [comment]
Layered attachments done in 3d9d70f15363566817c572ccaa83241181e807bd.
