### ISSUE TITLE
Terrain rendering example

### ISSUE THREAD

**Issue by VinnyVicious** [mosra/magnum#128]
It would be nice to have a terrain rendering example or built-in shader, something along the lines of:

http://udn.epicgames.com/Three/TerrainAdvancedTextures.html
https://www.assetstore.unity3d.com/en/#!/content/5664

**Comment by mosra** [comment]
Yes, sure. As pointed out in bkaradzic/bgfx#597, this will make sense only if the example is used to explain some advanced functionality like LOD switching, on-the-fly mesh updates, transform feedback or something like that.

I currently have other things with higher priority (animation, iOS support, ...), so this will not be done in near future unless someone else volunteers to do this. Keeping this open.

**Comment by mosra** [comment]
Moved to #102.
