### ISSUE TITLE
error while building from source

### ISSUE THREAD

**Issue by sajjadul-wematter** [mosra/magnum#139]
Hello, 
I am having the following error while compiling from source at Ubuntu 15.10. The corrade is already installed . 

///////////////////////////////////////////////////////////
[ 42%] Compiling data resource file /home/sajjad/Downloads/Magnum/magnum-master/build/src/Magnum/Shaders/resource_MagnumShaders_RCS.cpp
/usr/local/bin/corrade-rc: error while loading shared libraries: libCorradeUtility.so.0: cannot open shared object file: No such file or directory
src/Magnum/Shaders/CMakeFiles/MagnumShaders.dir/build.make:72: recipe for target 'src/Magnum/Shaders/resource_MagnumShaders_RCS.cpp' failed
make[2]: *** [src/Magnum/Shaders/resource_MagnumShaders_RCS.cpp] Error 127
CMakeFiles/Makefile2:4171: recipe for target 'src/Magnum/Shaders/CMakeFiles/MagnumShaders.dir/all' failed
make[1]: *** [src/Magnum/Shaders/CMakeFiles/MagnumShaders.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 42%] Building CXX object src/Magnum/Primitives/CMakeFiles/MagnumPrimitives.dir/Circle.cpp.o
[ 43%] Building CXX object src/Magnum/Primitives/CMakeFiles/MagnumPrimitives.dir/Crosshair.cpp.o
Linking CXX shared library libMagnumMeshTools.so
[ 43%] Building CXX object src/Magnum/Primitives/CMakeFiles/MagnumPrimitives.dir/Cube.cpp.o
[ 43%] Built target MagnumMeshTools
[ 43%] Building CXX object src/Magnum/Primitives/CMakeFiles/MagnumPrimitives.dir/Cylinder.cpp.o
[ 44%] Building CXX object src/Magnum/Primitives/CMakeFiles/MagnumPrimitives.dir/Icosphere.cpp.o
[ 44%] Building CXX object src/Magnum/Primitives/CMakeFiles/MagnumPrimitives.dir/Line.cpp.o
[ 44%] Building CXX object src/Magnum/Primitives/CMakeFiles/MagnumPrimitives.dir/Plane.cpp.o
[ 45%] Building CXX object src/Magnum/Primitives/CMakeFiles/MagnumPrimitives.dir/Square.cpp.o
[ 45%] Building CXX object src/Magnum/Primitives/CMakeFiles/MagnumPrimitives.dir/UVSphere.cpp.o
[ 45%] Building CXX object src/Magnum/Primitives/CMakeFiles/MagnumPrimitives.dir/Implementation/Spheroid.cpp.o
[ 46%] Building CXX object src/Magnum/Primitives/CMakeFiles/MagnumPrimitives.dir/Implementation/WireframeSpheroid.cpp.o
Linking CXX shared library libMagnumPrimitives.so
[ 46%] Built target MagnumPrimitives
Linking CXX shared library libMagnumSceneGraph.so
[ 46%] Built target MagnumSceneGraph
Makefile:126: recipe for target 'all' failed
make: *** [all] Error 2
//////////////////////////////////////////////////////////////////////////////////////////////////////////

Any hint to get rid of this problem ?

Thanks

**Comment by mosra** [comment]
Hi, looks like you are installing to non-standard location. The solution is either install to system-wide location (pass `-DCMAKE_INSTALL_PREFIX=/usr` to cmake when building Corrade) or properly specify RPATH in case you are installing somewhere else -- so in case you are installing into `/usr/local` (the default), you should pass `-DCMAKE_INSTALL_RPATH=/usr/local/lib` to cmake. Then it will be able to find the `libCorradeUtility.so` library and not end with an error.

By the way, which distribution are you using? There are already ArchLinux, Debian and Gentoo packages which should be much more convenient to use.

**Comment by sajjadul-wematter** [comment]
I am using ccmake  interface. How to insert RPATH there ? I do not see anywhere to mention this RPATH. There is only one point to enable RPATH or not.

**Comment by mosra** [comment]
Huh, what the hell, ccmake is not able to add a new variable (it's not there by default, you have to add it). Then the only way is to call `cmake` directly with the desired path to set the variable:
```
cd build 
cmake . -DCMAKE_INSTALL_RPATH=/usr/local/lib
```

**Comment by mosra** [comment]
Closing as resolved.
