### ISSUE TITLE
OpenGex importer crashes on trying to import this file

### ISSUE THREAD

**Issue by wivlaro** [mosra/magnum#144]
The stack seems to imply it's trying to parse a Half value. The code tries to dereference 'i' but it is null.

Debugger screen capture on crash:
![selection_001](https://cloud.githubusercontent.com/assets/384300/15411003/ea2871f2-1e14-11e6-8527-962a11e2c722.png)

Input file that fails:
[garage_module.ogex.txt](https://github.com/mosra/magnum/files/273529/garage_module.ogex.txt)

**Comment by Squareys** [comment]
See [the documentation](http://mosra.cz/blog/magnum-doc/classMagnum_1_1Trade_1_1OpenGexImporter.html) "half data type results in parsing error.".

*But*, searching your file, there does not seem to be half values in there, am I correct?

**Comment by mosra** [comment]
The file you uploaded seems to be incomplete. That might cause the crash. I'll try to fix the parser so it can handle these cases more gracefully.

**Comment by mosra** [comment]
Fixed in https://github.com/mosra/magnum-plugins/commit/aff9d4f9ef028d45412179d86d933a8700c69af4. The importer now properly reports an error instead of crashing.
