### ISSUE TITLE
Installing to another location other than /usr/local/ or /usr/  cannot find libCorradeUtility

### ISSUE THREAD

**Issue by chrisspaceape** [mosra/magnum#145]
I'm building Corrade and then magnum with:
``
-DCMAKE_INSTALL_PREFIX=/Users/chrisjubb/dev/protoTests/lib/
``

Corrade builds fine and installs to that location.
Then I try to build Magnum. It's able to mostly find the libraries but fails on this step:
``
[ 68%] Built target MagnumPrimitives
Scanning dependencies of target MagnumShaders_RCS-dependencies
[ 68%] Built target MagnumShaders_RCS-dependencies
[ 69%] Compiling data resource file /Users/chrisjubb/dev/protoTests/dependencies/magnum/build-release/src/Magnum/Shaders/resource_MagnumShaders_RCS.cpp
dyld: Library not loaded: @rpath/libCorradeUtility.0.dylib
  Referenced from: /Users/chrisjubb/dev/protoTests/libs/bin/corrade-rc
  Reason: image not found
/bin/sh: line 1: 17116 Trace/BPT trap: 5       /Users/chrisjubb/dev/protoTests/libs/bin/corrade-rc MagnumShaders_RCS resources.conf /Users/chrisjubb/dev/protoTests/dependencies/magnum/build-release/src/Magnum/Shaders/resource_MagnumShaders_RCS.cpp
make[2]: *** [src/Magnum/Shaders/resource_MagnumShaders_RCS.cpp] Error 133
make[1]: *** [src/Magnum/Shaders/CMakeFiles/MagnumShaders.dir/all] Error 2
``

Any ideas? Looks like that corrade-rc is looking for the libCorradeUtility.0.dylib which I can see in:
/Users/chrisjubb/dev/protoTests/libs/lib/libCorradeUtility.0.dylib

Does something need to change with that @rpath variable?
I've tried setting:
``
DYLD_LIBRARY_PATH
LD_LIBRARY_PATH
DYLD_FALLBACK_LIBRARY_PATH
``

I'm on Mac OSX 10.11.3

**Comment by mosra** [comment]
Hi, yes, as noted in docs, [you have to set `CMAKE_INSTALL_RPATH`](http://mosra.cz/blog/corrade-doc/building-corrade.html#building-corrade-linux) to `/Users/chrisjubb/dev/protoTests/libs/lib` during the CMake configuration step for *both* Corrade and Magnum.

**Comment by chrisspaceape** [comment]
ah sorry I missed that. thanks a lot :)
