### ISSUE TITLE
Vulkan / GL split

### ISSUE THREAD

**Issue by mosra** [mosra/magnum#147]
**The problem:** Magnum was originally designed with OpenGL support _only_. That means the root namespace is full of GL-related classes and there is currently no clean way to introduce Vulkan to it. Thus we need to do some refactoring to make it possible.

**Goal:** Have GL-specific code and Vk-specific API coexist in the same repository. This does _not_ mean doing an abstraction that covers both. Ideally being able to compile, install and use both APIs at the same time (use cases: performance comparison, incremental porting). NVidia also provides an ability to feed Vulkan framebuffer to OpenGL using [GL_NV_draw_vulkan_image](http://developer.download.nvidia.com/assets/gameworks/downloads/secure/Vulkan_Beta_Drivers/GL_NV_draw_vulkan_image.txt?autho=1465036419_b7648494463040729ecda500a6f1a339&file=GL_NV_draw_vulkan_image.txt) and I don't want to make this use case impossible with wrong design decisions.

## Naming

My idea is to have `GL` identifier for GL-related code and `Vk` for Vulkan-related code. `GL` casing is inconsistent with `Vk`, but `Gl` is even worse as it looks too much like `GI`. `gl`/`vk` is not an option because it breaks CamelCase coding style. Using full names like `OpenGL` and `Vulkan` seems too verbose to me (and misleading, because `WebGL` is `GL` but not `OpenGL`).

## Building

We need at least a possibility to enable either GL (desktop, GLES2, GLES3, WebGL1, WebGL2), or Vulkan or both. Simplest way is to introduce new `TARGET_VK`/`TARGET_GL` CMake options. For backwards compatibility `TARGET_GL` would be enabled by default (much like `TARGET_GLES2` is enabled by default now -- _I should consider removing it already_).

There is also a value in enabling none. That way we would get a pretty neat math library, scene graph and asset management pipeline for use with any other API (Metal, DX12, `bgfx`...).
## C++ standard and minimal CMake version

Because Vulkan is brand new, we can assume that people using Vulkan won't be on old systems with old drivers, tools and compilers. I would like to still keep the GL part of the codebase on CMake 2.8.12 and C++11, however for the new Vulkan code I would propose targeting CMake 3.x and C++14. That would exclude GCC < 4.9, MSVC 2013 and Ubuntu 14.04 LTS from the supported list.

Using C++14 allows us to use some lambda tricks, unbounded constexpr madness and more. Thanks to recent CMake buildsystem changes we can set `CORRADE_CXX_STANDARD` for `Magnum::Vk` to `14` while still keeping the rest on `11`.
- ~~[x] Decide which neat new CMake features could be useful for Vulkan and set that version as minimal~~ 3.7 has FindVulkan, I think there is no need to go higher

## Splitting the GL and Vk code

Originally I thought about just moving the GL code from `src/Magnum` to `src-gl/Magnum`, while the Vk code would start appearing in `src-vk/Magnum`. This would, however, prevent them to coexist.

Current idea is this:
-   Create new `src/Magnum/GL/` directory, a `Magnum::GL` namespace and `Magnum::GL`/`libMagnumGL.so` library and move all GL-related code to it.
-   Create new `src/Magnum/Vk/` directory, a `Magnum::Vk` namespace and `Magnum::Vk`/`libMagnumVk.so` library and start putting the Vk code to it.

Because this would break _all_ users code, we have to make some countermeasurements:

- [x] Create include "symlinks" from `Magnum/*.h` to `Magnum/GL/*.h`, put them somewhere in a separate temporary place (`src-gl/Magnum`) and mark them as deprecated right away, removing them in the future. Another option is to have symlinks also from `Magnum/*.h` to `Magnum/vk/*.h`, but that would lead to great confusion so I'm not doing it.
- [x] ~~Link the `Magnum::Magnum` library to `Magnum::GL` as a backward-compatible option that will be removed in the future.~~ not possible (cyclic dependencies)
- [x] ~~Make both `Magnum::GL` and `Magnum::Vk` namespaces inline. That way one could still use (and is encouraged to use) `Framebuffer` instead of `GL::Framebuffer`, without being forced to suddenly prefix all the code.~~ No.
  - [x] Or discourage it, make it explicit by default and have only the `GL` namespace inline for backwards compatibility (and removing it later)? There might be some issues regarding the API-independent enums (below).
  - [x] ~~I have to check the behavior if one would include both `<Magnum/GL/Framebuffer.h>` and `<Magnum/Vk/Framebuffer.h>`. I expect that this won't emit any error, but one has to explicitly use `GL::Framebuffer` or `Vk::Framebuffer` to avoid ambiguity.~~ No.
  - [x] ~~I have to check that this works on all compilers we want to support and find a way to emulate it on older versions (MSVC 2013, [I'm looking at you](https://msdn.microsoft.com/cs-cz/library/hh567368.aspx)! No Vulkan for you then.)~~ Obsolete.

## API-independent code

Some code (such as various wrappers in the root namespace, `Math`, `Audio`, `Shapes` and `SceneGraph` namespaces) is completely API-independent, which means that there should be no difference whatsoever if the `Audio` library comes from Magnum compiled with GL support or Magnum compiled with Vk support.

The code would just stay in `src/Magnum` as it always was, either as part of the (now API-independent) `Magnum::Magnum` library or in its own dedicated library (like before).

## Math code that is API-specific

- [x] ~~Projection matrix creation. Would need to be moved out from `Math::Matrix::*Projection()` to some API-specific header.~~ moved to #234 

## Code that depends on API definitions

Some code (such as `PixelStorage` class, `Trade`, `Primitives`, and `MeshTools` namespaces) does not interact with the API in any way, but uses some global enums (`MeshPrimitive`, `PixelFormat`, `PixelType`) that are specific to OpenGL. That would prevent having them independent (so one would need to use two different `Trade` libraries for GL and Vk code, which seems _very_ weird).

Vulkan uses quite a different naming (for example there is just `Format` that covers all vertex, texture and pixel formats).

The proposal is to make `Magnum::MeshPrimitive`, `Magnum::PixelFormat`, `Magnum::PixelType` enums contain only a sane subset that is supported on both GL and Vulkan, are just numbered from `0` up and are translated using a LUT to `Magnum::GL::MeshPrimitive`, `Magnum::GL::PixelFormat` and `Magnum::GL::PixelType` or to `Magnum::Vk::Format` on runtime.

For API-dependent classes there should be `Magnum::PixelStorage` supporting common subset of `Magnum::GL::PixelStorage` and `Magnum::Vk::PixelStorage` and be implicitly convertible to it. This goes also for `Image`, `ImageView` (but not `Trade::Image`, that one will use only the common subset).

- [x] ~~Having the same name in the root namespace would clash with the `inline namespace`. I need to invent a different naming for the API-independent stuff.~~ Obsolete.
- [x] ~~Find a way to create _and maintain_ the LUT easily. There are 100s of values and just the `static_assert` proposed in http://www.g-truc.net/post-0704.html is simply not enough. Code generation using Python script? Static assert in a loop (C++14 only)?~~ implemented, using the same definition for table and test
- [x] ~~How is pixel storage represented in Vulkan?~~ not at all, have to handle manually
- [x] ~~Are there any other interactions I forgot about?~~ nope
- [x] Shouldn't we split the `Format` into usage-specific enums also for Vulkan to avoid mistakes? It proved to be very useful. -- yes
- [x] ~~Define what's a "sane subset" ... or a superset, rather?~~ basically what importers support, excluding *old* things like GL_LUMINANCE
- [x] ~~Is there any possibility to have e.g. `Magnum::MeshPrimitive` implicitly convertible to `Magnum::GL::MeshPrimitive`? Or do I need to have _two_ overloads for every function that takes these enums? What about backwards compatibility then?~~ no, providing explicit conversion functions and function overloads instead

## Code that is API-specific

Code in namespaces `DebugTools`, `Shaders`, `Text`, `TextureTools`, font plugins. Options:

- [x] Either make them API-agnostic and include both GL and Vulkan-specific implementation inside. That implies common(-ish) API for both, making unnecessary generalizations and restrictions (for example the `Text::Renderer` should be much more low-level for Vulkan with no implicit memory management).
- [x] ~~Make separate implementations for each API (thus `Magnum::GL::Shaders` and `Magnum::Vk::Shaders`, similarly with namespaces and filesystem location) and achieve API compatibility on parts that make sense using "static polymorphism". This would make sense only for libraries that don't have too much API-independent code (such as shaders).~~ no
  - [x] ~~Do CMake imported targets support multiple double colons in target names?~~
- ~~Make them API-independent, forcing the user to handle the boilerplate. Would make them more flexible (e.g. allowing the user to use GL buffer storage instead of implicit `glBufferData()`). This makes sense only for libraries that don't require API interaction at its heart (such as `Text`, but not `TextureTools::distanceField()`).~~ no

## API-independent code in API-specific namespaces

Parts of `DebugTools` and `TextureTools` namespaces such as `DebugTools::Profiler` and `TextureTools::atlas()`. Options:
- [x] ~~Having them unnecessarily duplicated in both libraries (ugh)~~ no
- [x] ~~Splitting them out to a new API-independent namespace, exploding the amount of libraries (similarly to the second option above, backward compatibility considerations also apply)~~ no
- [x] Have a single library, control parts of it using `TARGET_*`

## Platform-specific interfaces

In case of windowed applications, `Platform::GlfwApplication` will get Vulkan context creation support, similar thing could be done manually in `Platform::Sdl2Application`. The context creation support for either API will be controlled by the `TARGET_GL`/`TARGET_VK` options. There will not be any API-specific classes in `GL::Platform` and `Vk::Platform` namespaces.

In case of windowless applications:
- [x] ~~Is it possible to create a _single_ `Platform::WindowlessVkApplication` that works on all platforms the same way? With GL it might be `Platform::WindowlessEglApplication` but drivers still have to come a long way before it is supported anywhere else than on NV.~~ Yes, but better idea would be, as creating windowless Vulkan instance doesn't involve interacting with _any_ platform-specific API, having just `VkInstance` wrapper (equivalent to current `Magnum::Context`).
- [x] ~~Have `Platform::WindowlessVk*Application` with no "static polymorphism" or anything to be compatible with `Platform::Windowless*GL*Application` classes? That would prevent having both GL and Vk context in a windowless application.~~ doesn't make sense with the above idea
- [x] ~~Other options? Have one Vulkan-only app and shoveling Vulkan support into each of the current `Platform::Windowless*GL*Application` classes?~~ also doesn't make sense with the above idea

- [x] For context creation, there would need to be separate configuration classes, `Application::GLConfiguration` and `Application::VkConfiguration`. To avoid duplicating non-API-related code, window-specific configuration would be in ~~`Application::WindowConfiguration` (this would also prepare the ground for multi-window support)~~ using just `Configuration` for backwards compatibility, also makes it possible to have some spp-global config in addition to window-specific config

I imagine Vulkan will _always_ need some non-implicit setup -- at least specifying application name, maybe enabling features/extensions. To keep backwards compatibility, if no configuration is passed to the constructor, GL context will be created. If Vk configuration is passed to the constructor, only Vulkan context is created. To create both GL and Vk context, the user needs to pass both configurations to the app (even though the GL configuration would be default-constructed).
- [x] ~~What about backwards-compatible `Application::Configuration`? Just an empty class inheriting from both `WindowConfiguration` and `GLConfiguration` (with proper overloads for method chaining)?~~ not a problem anymore as we keep `Configuration`

## Testing

Currently there is `Magnum::GL::AbstractOpenGLTester` class that uses one of `Platform::Windowless*Application` classes (I'm planning on making it a public API and not just an internal thing) and GL tests available under `BUILD_GL_TESTS`. I think it makes sense to create `Magnum::Vk::AbstractVulkanTester` ~~, some `Platform::WindowlessVk*Application` class~~ and Vulkan tests under `BUILD_VK_TESTS` as soon as possible.

Since the Vulkan tester doesn't require any platform-specific code, it doesn't need to be as complex as with the GL tester, however some amount of setup work might be useful.

- [x] ~~Decide what to set up in the Vulkan tester and what to leave up to the tests (will probably become clearer once we implement a few)~~ moved to #234

## Where to start with Vulkan?

This seems like a lot of work before we can even start playing with Vulkan, right? No. If I assume correctly, it should be no problem to link code that uses GL with code that uses Vulkan.
- [x] Verify this

Thus we can start implementing Vulkan APIs right now and treat `Magnum::Magnum` as API-independent base with only the `Math` library inside. At least until we start using the `Trade` library for importing stuff. TODO list to get started, in order:
-   Introduce `TARGET_VK` CMake option, default to `OFF`
-   Create `src/Magnum/Vk`, `Magnum::Vk` library and make it available through the `find_package(Magnum REQUIRED Vk)` call
-   Create _some_ ~~`Platform::WindowlessVk*Application` and~~ `Vk::AbstractVulkanTester` class so it is possible to test the implementation right from the start
-   Start implementing!

**Comment by Squareys** [comment]
> it should be no problem to link code that uses GL with code that uses Vulkan. [...] Verify this

You can mark as verified. You cannot create a Vulkan swapchain if a OpenGL context exists (at least on NV), but linking is no problem.

**Comment by mosra** [comment]
Thanks!

**Comment by Squareys** [comment]
> Is it possible to create a single Platform::WindowlessVkApplication that works on all platforms the same way?

I propose to have the Vulkan context (`Vk::Context`, which would wrap a `VkInstance`) independent of `Platform::*Application`.
This allows using it in any application you want (as long as you don't require a `VkSurface`\*, which requires platform specific handles or support by the Application, which `GlfwApplication` could do through glfw for example.)
Also, it allows to test more easily (entirely without `*Application`). 

\*  `VkSurface`* is used for presenting images to a window.*

*(This is a summary of what I already noted via chat etc. For public discussion :-) )*

**Comment by Squareys** [comment]
>  I expect that this won't emit any error, but one has to explicitly use GL::Framebuffer or Vk::Framebuffer to avoid ambiguity.

Correct. While there is no `GL::Framebuffer` yet, including `<Magnum/Framebuffer.h>` (currently even `<Magnum/Magnum.h>` because of forward declarations) will obviously result in ambiguity if `using namespace Vk;` and requires explicitly adding `Vk::` prefix.

Personally, I would find it useful if this prefix would be omissible when using only `Magnum::Vk` (after the split has been done).

**Comment by Squareys** [comment]
>  I think it makes sense to create Magnum::Vk::AbstractVulkanTester

Definitely. How much setup work should this tester do? Probably something like:

1. Setup the context (With features requested by the class implementing `AbstractVulkanTester`?)
2. Setup the device (simply using the first physical device listed)
3. (?) Setup a device queue

It might be useful to have more than one type of `AbstractVulkanTester` with different amounts of setup work.

**Comment by mosra** [comment]
@Squareys thanks!

Great idea with omitting the windowless application class completely, simplifies a lot of things. I think it makes sense to follow Vulkan naming convention and use `Vk::Instance` instead of `Vk::Context`.

> How much setup work should this tester do?

I would like to have at least the same features as in the GL tester -- so setting up some debug/validation layer, if available, so we have all the error checking etc. for easier testing. I think the actual needs will become clearer once we have a few of the tests implemented (seeing which code is unnecessarily repeated or what setup is done too implicitly and restricts the testing possibilities). Another (not necessarily essential) feature -- being able to select different GPU / feature set from command-line when running the test, similarly to what `--magnum-disable-extensions` etc. is doing now.

> I would find it useful if this prefix would be omissible when using only Magnum::Vk (after the split has been done).

Me too. My original idea with the API-independent functionality was something like this (where you would use the prefix only if you want to target a specific API), but apparently that doesn't work -- GCC complains about ambiguous reference:

```cpp
namespace Magnum {
    // API-independent values
    enum class PixelFormat {
        RGBA8 = 0,
        //....
    };

    inline namespace Vk {
        // Vulkan-specific values
        enum class PixelFormat {
            RGBA8 = VK_FORMAT_R8G8B8A8_UNORM,
            //....
        };
    }

    inline namespace GL {
        // GL-specific values
        enum class PixelFormat {
            RGBA8 = GL_RGBA8,
            //....
        };
    }
}

using namespace Magnum;

int main() {
    // Using API-independent value by default
    auto a = PixelFormat::RGBA8;

    // Or an explicit value targeting a specific API
    auto b = Vk::PixelFormat::RGBA8;
    auto c = GL::PixelFormat::RGBA8;
}
```

... so I need to invent something else.

**Comment by Squareys** [comment]
> makes sense to follow Vulkan naming convention and use Vk::Instance instead of Vk::Context

Sure, that will help moving from pure-Vk to Magnum::Vk or vice-versa, if you already know one or the other.

**Comment by mosra** [comment]
Added a note about API-dependent math code (projection matrices).

**Comment by mosra** [comment]
Initial work on this is being done in #233.

**Comment by mosra** [comment]
Initial Vulkan work is being done in #234.

**Comment by mosra** [comment]
#233 got merged and released in 2018.04, nothing blocks Vulkan work anymore.

**Comment by kghose** [comment]
@mosra - question from a n00b here: I read on the internet that macOS is deprecating OpenGL and emphasizing metal. I guess OpenGL will keep working for a while, but it did make me think. One hope with using a render abstraction like Magnum is to be able to use (ideally) the same code and not worry about backends. Is this the case with Magnum? Is this ideal too hard? What about for simpler things? The thing I liked about OpenGL is that one can take pretty old code and still compile it. Thanks!

**Comment by mosra** [comment]
Everything from the above list got implemented already and the minor things that are left are now moved to #234. Closing as done, since keeping this open would mean the above information gets inevitably stale.
