### ISSUE TITLE
Dropppping unmaintained code

### ISSUE THREAD

**Issue by mosra** [mosra/magnum#148]
Assuming nobody uses the following parts anymore, I propose deprecating and then dropping them:

- [x] `Shapes` namespace. Poorly designed, sparsely implemented and of no real use. This would make #5 and also the `DebugTools::ShapeRenderer` class obsolete. Affects the Bullet and Audio example, which would need to be reworked without these (shouldn't be hard, we could also make use of instancing there) -- deprecated in 8efc6b39e902d01dfac904163ad90385d3007013
  - [x] adapt the Bullet example -- mosra/magnum-examples@11f917f9a99dd16257055d7b64490f123aef87a3
  - [x] adapt the Audio example -- mosra/magnum-examples@8a8b06ebf7a0d2929fc3c19a9500182c17698139
  - [x] deprecate `BulletIntegration::convertShape()` -- mosra/magnum-integration@968fa40c7fe58ae9efced185f91e47d0992589d9
  - [x] Drop everything -- mosra/magnum@aca02f52f550c98c632358b2e5bb8ecda3853b6d, mosra/magnum-integration@e2be55b0a2f65d97b74cf8d9acae10f1ee0cbd93
  - [x] Remove `@collisionoperator` or whatever is it named from Doxyfile and Coding Style docs
- [x] `Platform::GlutApplication` class. Is there any platform that has GLUT but doesn't have SDL2? The class is not receiving any updates anymore and I'm not sure if it even works. -- deprecated in d70f75a179f05920da5dcf09c61dd268476328bf
  - [x] Drop it (#195)
- [x] `ColladaImporter` plugin. Depends on outdated `Qt4`, supports only some features because COLLADA files are impossible to parse and I don't plan to extend it anymore. I propose replacing it with general-purpose importer based on `Assimp` (#146) -- deprecated in mosra/magnum-plugins@35ee1a2665917c0246b02b108086a7ade88d1f0f
  - [x] Drop it -- mosra/magnum-plugins@ced67fce5791fea1ce4b8f477351e4423de86ca8
- [x] The `compatibility` branch, along with support for GCC 4.4, 4.5, 4.6 and MSVC 2013.

**Comment by wivlaro** [comment]
I still use collada importer. But can probably move to opengex at some
point. I think assimp is quite good iirc, only concern would be it being a
bit lowest-common-feature set.

**Comment by Squareys** [comment]
> Affects bullet example, which would need to be reworked

And audio example too ;) But replacing by mesh primitives should be fine there too,

**Comment by mosra** [comment]
New item added: completely dropping the `compatibility` branch, along with support for GCC 4.4, 4.5, 4.6 and MSVC 2013. The branch wasn't updated since October last year so I don't expect anyone to still depend on it. For me it's real maintenance nightmare.

The last reason why I wanted to keep it was Windows Phone SDK that still depends on MSVC 2013, but since that platform is also almost dead, the pain-to-portability ratio is too high.

Please raise objections if you have a different opinion.

**Comment by ManuelK89** [comment]
We might need some line - sphere/box collision detection for selecting objects but we could also implement it ourselves. As I have seen so far, the shapes are currently implemented for floats only anyway.

**Comment by mosra** [comment]
@ManuelK89 The actual "brain" of the `Shapes` namespace is in `Math::Geometry`, where ~~all~~ most of the intersection/distance algorithms are implemented -- e.g. line/sphere intersection is just a call to [Math::Geometry::Distance::linePointSquared()](http://mosra.cz/blog/magnum-doc/classMagnum_1_1Math_1_1Geometry_1_1Distance.html#ae1d2b2b23aeaee457b94a728594d5a9a)

**Comment by mosra** [comment]
The `compatibility` branch is now removed along with all documentation references to it. If you happen to still find any reference to it, please tell me.

**Comment by mosra** [comment]
`Shapes` namespace and `DebugTools::ShapeRenderer` is deprecated since 8efc6b39e902d01dfac904163ad90385d3007013.

**Comment by mosra** [comment]
`ColladaImporter` is deprecated in mosra/magnum-plugins@35ee1a2665917c0246b02b108086a7ade88d1f0f, `BulletIntegration::convertShape()` in mosra/magnum-integration@968fa40c7fe58ae9efced185f91e47d0992589d9.

**Comment by mosra** [comment]
Everything is removed now:

- Shapes in aca02f52f550c98c632358b2e5bb8ecda3853b6d and mosra/magnum-integration@e2be55b0a2f65d97b74cf8d9acae10f1ee0cbd93
- GlutApplication in 035f644769742d00af800f33af2b586a389608c2
- ColladaImporter in mosra/magnum-plugins@ced67fce5791fea1ce4b8f477351e4423de86ca8

Together with #81 it totalled in around 18k lines removed. Not bad :fire: :fire: :fire:
