### ISSUE TITLE
Physically based rendering

### ISSUE THREAD

**Issue by VinnyVicious** [mosra/magnum#150]
https://interplayoflight.wordpress.com/2013/12/30/readings-on-physically-based-rendering/
http://www.codinglabs.net/article_physically_based_rendering.aspx
http://codeflow.org/entries/2011/apr/18/advanced-webgl-part-3-irradiance-environment-map/

**Comment by Squareys** [comment]
An example for PBR is already planned: https://github.com/mosra/magnum/issues/102

I would therefore consider this a duplicate.

**Comment by mosra** [comment]
Hi, thanks for the links -- I consider the engine more as a middleware, providing you all the things you need for implementing a particular rendering technique and feeding it with data, but giving you full freedom to implement it any way you want. Putting this directly into the engine would thus force the users to adapt one particular approach, even though it might not fit their use case. On the other hand, I'm more than happy to have a self-contained example for this, thus I'm adding the links to the global example tracking issue #102 and closing this one.
