### ISSUE TITLE
Real-Time Global Illumination

### ISSUE THREAD

**Issue by VinnyVicious** [mosra/magnum#151]
Real-Time Diffuse Global Illumination Using Radiance Hints: http://graphics.cs.aueb.gr/graphics/docs/papers/RadianceHintsPreprint.pdf

Other approaches:
https://www.wpi.edu/Pubs/ETD/Available/etd-121815-134638/unrestricted/csun.pdf
https://users.cg.tuwien.ac.at/zsolnai/wp/wp-content/uploads/2016/02/AdamPapp_cgsem.pdf
https://users.cg.tuwien.ac.at/zsolnai/wp/wp-content/uploads/2015/02/kevin_streicher_star.pdf

**Comment by mosra** [comment]
Hi, thanks for the links -- I consider the engine more as a middleware, providing you all the things you need for implementing a particular rendering technique and feeding it with data, but giving you full freedom to implement it any way you want. Putting this directly into the engine would thus force the users to adapt one particular approach, even though it might not fit their use case. On the other hand, I'm more than happy to have a self-contained example for this, thus I'm adding the links to the global example tracking issue #102 and closing this one.
