### ISSUE TITLE
Shadow mapping

### ISSUE THREAD

**Issue by VinnyVicious** [mosra/magnum#155]
http://www.cspaul.com/publications/Rosen.2012.I3D.pdf
http://publications.lib.chalmers.se/records/fulltext/198979/198979.pdf
http://jmarvie.free.fr/Publis/2014_I3D/i3d_2014_SubPixelShadowMapping.pdf

**Comment by mosra** [comment]
Hi, thanks for the links -- I consider the engine more as a middleware, providing you all the things you need for implementing a particular rendering technique and feeding it with data, but giving you full freedom to implement it any way you want. Putting this directly into the engine would thus force the users to adapt one particular approach, even though it might not fit their use case. On the other hand, I'm more than happy to have a self-contained example for this, thus I'm adding the links to the global example tracking issue #102 and closing this one.

**Comment by wivlaro** [comment]
Following up on this @VinnyVicious - https://github.com/mosra/magnum-examples/pull/24
