### ISSUE TITLE
GLFW key repeat event handling

### ISSUE THREAD

**Issue by staticfloat** [mosra/magnum#161]
It'd be nice to get GLFW key repeat events in the same way as given by SDL2.  I would be satisfied with just mapping `GLFW_REPEAT` to `keyPressEvent()` [right here](https://github.com/mosra/magnum/blob/798ec9af9b7c0752c54e1dc1ce87ee7c85742186/src/Magnum/Platform/GlfwApplication.cpp#L171).  What do you think?

**Comment by mosra** [comment]
Yup, it seems to be equivalent. Furthermore SDL2 says whether the event is repeated or not in the key event, I guess that could be also useful to expose in some `*Application::KeyEvent::isRepeated()` function if one would *not* want to handle repeated events?

**Comment by mosra** [comment]
Done in c5e22ae560fbaf152b5645204bb8d8732685d5bc and 7c631d714af5af15644913a876ece38dd544528e.

**Comment by staticfloat** [comment]
Thanks @mosra, you're the best.
