### ISSUE TITLE
Context::current(): no current context

### ISSUE THREAD

**Issue by staticfloat** [mosra/magnum#167]
I have a multithreaded application on OSX that is trying to create Magnum objects (`Mesh`, `Shader`, etc... objects) on a background thread, but whenever I attempt to do so, I get the above error.  I'm not certain how to create a context for the background thread properly, and although the documentation states that there should be a context object created transparently for each thread in thread-local-storage, that does not seem to be the case.

What is the proper method for creating a context for the background thread so that these objects can be created, and then rendered on the main thread?

**Comment by mosra** [comment]
Hmm.. I fear that my answer will disappoint you ;)

The only way to access GL from multiple threads is to have one GL context per thread, you can't have one context bound to two threads at the same time. This by default means that the contexts are completely independent, not knowing about each other's objects. Manually creating thread-local contexts is supported by Magnum, it's [documented here](http://mosra.cz/blog/magnum-doc/platform.html#platform-windowless-contexts) and was battle tested very recently in a multiplatform production-level app (Linux, iOS, OSX, Windows).

> the documentation states that there should be a context object created transparently for each thread in thread-local-storage

What the documentation of e.g. [MAGNUM_BUILD_MULTITHREADED](http://mosra.cz/blog/magnum-doc/Magnum_8h.html#af2d9ad7711f07880ba64835331927d64) is trying to say is: you are able to have multiple thread-local GL contexts and the `Magnum::Context` instance will also be thread-local so the access to it doesn't clash across threads and each thread knows only about it's local copy. The error above is just saying that you didn't create (GL context and) `Magnum::Context` instance for your other thread I admit there is some confusion between Magnum context and GL context, sorry.

To be able to share *some* objects between separate GL contexts GL supports creating *shared* contexts. This is currently not supported by Magnum. Also it has severe limitations, e.g. objects like `Mesh` and `Framebuffer` aren't shared and you have to create them separately on both sides. So -- very annoying to use and I'm not optimistic about this being bug-free and optimized in the drivers...

If you don't need the background thread after you create the objects, you could in theory make the context current on the background thread first and then, after the init is done, move it back to the main thread. But a few bits are missing in Magnum APIs to be able to do that.

What is the actual thing you are trying to achieve, anyway? If the core of it is just populating (and not creating) objects from background thread, then you could make use of buffer mapping, PBOs etc. -- the memory pointers can be shared across the threads as you need, you just have to call the GL map/unmap APIs on the main thread.

**Comment by staticfloat** [comment]
Ah, I see.  I was confusing the idea of a Magnum context with a GL context.  Everything you say makes sense, and I have already re-architected my program to do all the heavy lifting in the background thread, then create the objects from the precomputed data just-in-time for drawing.  Thank you for the very complete answer!

My goals are rapid plotting of scientific measurement data.  In essence, I build measurement and processing applications with Magnum because it's the easiest way for me to plot thousands of datapoints 60 times a second and see my measurements live.  I just have to be careful on which threads I create Magnum objects. :)

**Comment by mosra** [comment]
Hey, great use case :) If you happen to have any screenshots, it would be great addition to the upcoming "Showcase" section in the docs.

This is what I meant by populating the objects in background thread: http://on-demand.gputechconf.com/gtc/2012/presentations/S0356-GTC2012-Texture-Transfers.pdf however they go one step further and actually have shared GL contexts and sync the threads to ensure the uploads are complete before displaying the contents. Neither shared contexts nor GL sync objects are supported in Magnum ATM, but I could add them if your use case would require them.
