### ISSUE TITLE
Download and build corrade as a ExternalProject / git submodule

### ISSUE THREAD

**Issue by tony** [mosra/magnum#169]
When trying to try magnum out for the first time, I saw it had a minimum requirement of https://github.com/mosra/corrade. A library which I haven't seen before, I looked and haven't found any package repositories that provide it as a pre-built shared library.

While I have no problem with keeping corrade separate, using [``ExternalProject_add``](https://cmake.org/cmake/help/v3.6/module/ExternalProject.html#command:externalproject_add) in CMake or a git submodule would allow a dependency like that to be automatically retrieved, built and linked as part of the magnum build system.

**Comment by LB--** [comment]
This is already supported, see the docs here: http://mosra.cz/blog/magnum-doc/getting-started.html
> Magnum libraries support both separate compilation/installation and **CMake subprojects**. We'll use the subproject approach now, because adding the dependencies means just cloning them into your project tree

**Comment by tony** [comment]
@LB-- The ExternalProject route seems most promising, but none of the instructions worked when I tried.

```
-- Found SDL2: /usr/local/lib/libSDL2.dylib
CMake Error at /usr/local/Cellar/cmake/3.6.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find Magnum (missing: Sdl2Application)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.6.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  vendor/magnum/modules/FindMagnum.cmake:648 (find_package_handle_standard_args)
  CMakeLists.txt:102 (find_package)


-- Configuring incomplete, errors occurred!
See also "/Users/me/work/c++/sdl2-playproject/build/CMakeFiles/CMakeOutput.log".
See also "/Users/me/work/c++/sdl2-playproject/build/CMakeFiles/CMakeError.log".
```

In my situation its more important to have this lib buildout as a library I can easily plop into a current CMake project and link to for desktop dev (ExternalProject_Add style).  I can't spend more time on it at the moment.

**Comment by Squareys** [comment]
You need to specify `-DWITH_SDL2APPLICATION=ON` to build that component of magnum which you seem to require for your project.
