### ISSUE TITLE
Publish API for converting math types

### ISSUE THREAD

**Issue by mosra** [mosra/magnum#173]
Currently the API that is able to convert math types between Magnum types and external types (e.g. converting `btVector3` to `Magnum::Vector3` and back) is part of `Math::Implementation` namespace with no documentation and the only way how implementers can make it working is looking [into tests](https://github.com/mosra/magnum/blob/8d38f1d258303f7bce3d3601b084df7d6ec81dcd/src/Magnum/Math/Test/QuaternionTest.cpp#L40-L51) or [actual code in the integration libraries](https://github.com/mosra/magnum-integration/blob/cdace8de771096025156c4899b4d1ae6ff3075a4/src/Magnum/OvrIntegration/Conversion.h).

This API should be published (taken out of the `Implementation` namespace) and documented to make it easier for people to adopt when writing new integration libraries.

**Comment by Squareys** [comment]
I use this API quite alot myself (for integration with OpenVR for example), I can easily imagine this being useful for other people. :+1:

**Comment by mosra** [comment]
With the `EigenIntegration`, `GlmIntegration` and others, together with similar private APIs being introduced for `Containers::ArrayView`, `Containers::Pointer` etc., I'm leaning more towards keeping these private and documenting them with prose like [here](https://doc.magnum.graphics/corrade/classCorrade_1_1Containers_1_1ArrayView.html#Containers-ArrayView-stl) or [here](https://doc.magnum.graphics/magnum/GeometryIntegration_8h.html) -- the actual type signatures are in many cases very crazy, don't really say much to the end user and would only add noise to the docs (since one usually needs many variants to cover all conversion cases). On the other hand, writing such an integration is a task meant for magnum developers rather than users, and there one's expected to read source code anyway.

Similar approach could be thought of for `Utility::ConfigurationValue` or `Utility::TweakableParser` specializations, but these types are rather simple and having each of those specializations listed conveys the information about what types are usable with `Utility::Tweakable` or `Utility::Configuration`, so I think it's okay to keep them public.
