### ISSUE TITLE
OpenAL floating point formats

### ISSUE THREAD

**Issue by Alicemargatroid** [mosra/magnum#174]
I see that we have types to represent floating point audio (both 32 and 64 bit), but is this actually playing correctly/usable? 

As well, as it is, it looks like there is no way to actually load any form of floating point; WAV, Vorbis, and FLAC all only support integer formats currently. Is this correct?

**Comment by Squareys** [comment]
> As well, as it is, it looks like there is no way to actually load any form of floating point; WAV, Vorbis, and FLAC all only support integer formats currently. Is this correct?

Yes, I believe so. After I added the float and double mono and stereo format, the importers were not updated (I am guessing at least .wav could support it?). The float and double buffer formats  are an extension of OpenAL.

> but is this actually playing correctly/usable?

I don't see a reason why it shouldn't work :)

**Comment by mosra** [comment]
WAV supports both 32 and 64bit floats, yes. I think updating the builtin WAV importer shouldn't be hard. It's probably just a different format ID and then the data can be just copied with no transformation.

I have no idea about Vorbis or FLAC.

Or someone could add a WAV importer plugin using [dr_wav](https://mackron.github.io/dr_wav), it claims to support that too.

**Comment by Alicemargatroid** [comment]
@mosra @Squareys It turned out to not be at all as easy as I thought, as seen in my PR: #175

FLAC does not support floating point (though, 24 bit seems like it should be converted to 32 bit floats), and ogg is a mess. WAV, however, supports basically everything we can throw into OpenAL.

**Comment by mosra** [comment]
As the PR is merged now, I think this can be closed too.
