### ISSUE TITLE
Sdl2Application disables compositing on startup

### ISSUE THREAD

**Issue by mosra** [mosra/magnum#184]
SDL is [unconditionally asking for `_NET_WM_BYPASS_COMPOSITOR`](https://github.com/spurious/SDL-mirror/blob/4fcf9fa0fce31f2f4fb5a03f1e04698d380967f2/src/video/x11/SDL_x11window.c#L572) and there is no way to disable this (at least in SDL 2.0.5). On KDE and KWin this causes annoying flickering every time I start an application. 

Possible workarounds:

- ~~Pass `SDL_WINDOW_UTILITY` in window flags when the window gets created. According to the SDL window creation code this doesn't bypass compositor, but I'm not sure what are the consequences of utility windows. Also this is since SDL 2.0.5. On the positive side, this can be done on developer side with no user intervention.~~ This makes the window not appear in taskbar or Alt-Tab dialog. Not good.
- Disable composition forcing globally in KWin [as described here](https://bugs.kde.org/show_bug.cgi?id=361154#c67). This is ugly because it's platform-specific, has to be done on user side and is done globally for all apps, not just those selected.

Things to do:

- [x] ~~Report this to SDL~~ already fixed: https://github.com/SDL-mirror/SDL/commit/f8023f1dd4387aac6fd185698fd5b23f4660ffd1, implemented here in 3828e6b9a3cd32236f3d26339968f08d2d335758
- [x] ~~Make it possible to specify window type in app configuration~~ not needed here
- [x] Mention this in the documentation

**Comment by japanoise** [comment]
>Disable composition forcing globally in KWin as described here. This is ugly because it's platform-specific, has to be done on user side and is done globally for all apps, not just those selected.

+1 for the temporary fix. I'm getting this too.

**Comment by daniel-j** [comment]
Since SDL 2.0.8 (I think): `SDL_SetHint(SDL_HINT_VIDEO_X11_NET_WM_BYPASS_COMPOSITOR, "0");` before creating the window.

**Comment by mosra** [comment]
@daniel-j yay, awesome! thanks for the update :+1:

**Comment by mosra** [comment]
Implemented in 3828e6b9a3cd32236f3d26339968f08d2d335758, the docs [are extended to mention this](http://doc.magnum.graphics/magnum/classMagnum_1_1Platform_1_1Sdl2Application.html#Platform-Sdl2Application-usage-linux) together with a way to revert to the original behavior via an env var.
