### ISSUE TITLE
Math::Geometry::Intersection::planeLine stability issues

### ISSUE THREAD

**Issue by Squareys** [mosra/magnum#188]
Hi!

As discussed: `planeLine()` seems to have a problem with numerical stability, as I found during coding a software raytracer:

![image](https://cloud.githubusercontent.com/assets/1889284/21987519/35f73250-dc04-11e6-8dbf-cb982dc76907.png)

(The top and bottom planes are black out of other reasons)

I have a version that fixes this locally and will open a PR once I have time next week.

Regards, Jonathan.

**Comment by Squareys** [comment]
Turns out this is invalid and I was being stupid!

One plane works perfectly well. For my raytracer the issue came up with scenes that had two parallel planes: I did not check that the intersection was in front of the camera and therefore got two intersections with the same distance.

Sorry about that and sorry this took me so long!

**Comment by mosra** [comment]
Yay! :) Back on only 30 open issues again! Next milestone: 20 :)
