### ISSUE TITLE
GlfwApplication crashes without context

### ISSUE THREAD

**Issue by Squareys** [mosra/magnum#192]
Hi @mosra !

I have a use case in which I decide whether to open a window or not via a `--headless` flag.

If headless is set, I do not call `tryCreateContext(..)` and therefore `_window` in GlfwApplication remains unitialized (or nullptr?). Since `glwfShouldClose(_window)` in `GlfwApplication::exec()` seems to not be able to deal with that, it segfaults.

If you agree that this is a valid use case, I will see how to best fix this and open a PR. :)

Regards, Jonathan

**Comment by Squareys** [comment]
As discussed via gitter:
 - GlfwApplication should always open a window, the way to correctly handle the use case is by handling the headless switch in`main()` instead of using `MAGNUM_APPLICATION_MAIN()`.
 - GlfwApplication should fail gracefully if no window has been opened instead

Will open a PR once I have time to fix it.

**Comment by mosra** [comment]
Fixed by #272 and f832c8df51ab618c243c4af5fe0a9d989574d9cd, closing :)
