### ISSUE TITLE
Drop (P)NaCl support

### ISSUE THREAD

**Issue by mosra** [mosra/magnum#198]
Since I dropped support for GCC 4.4, the old NaCl port is no longer working (and I doubt things compiled with the old SDK versions even work anymore). The question is, if I should even continue to maintain this port, as it is exclusively Chrome-only and Emscripten is working very well. OTOH, it allows things like unrestricted threads and other stuff, which may be useful for some cases (porting heavily threaded code).

Things to do:

- [ ] Drop NaClApplication and WindowlessNaClApplication
- [ ] Drop the ~~old~~ NaCl toolchain
- [x] ~~Create new PNaCl toolchain~~
- [x] ~~I guess there will be serious build issues with the code (GL extensions, `NaClApplication`), so fix them~~
- [x] ~~Verify if it's possible to have unit tests on PNaCl and implement support for them into `Corrade::TestSuite`~~
- [x] ~~Port `Sdl2Application` to PNaCl~~
- [x] ~~(Re-)port the examples to PNaCl~~
- [x] ~~Test on the CIs~~

**Comment by wivlaro** [comment]
Surely it would be better to focus efforts on a WebAssembly toolchain rather than try to revive NaCl. Isn't that basically going to supercede it?

**Comment by mosra** [comment]
This settles it, then: https://blog.chromium.org/2017/05/goodbye-pnacl-hello-webassembly.html

**Comment by mosra** [comment]
NaCl support is no more since mosra/corrade@94fcae1fa4e6169ce25f79acc55ae0e4ff86c0a6, mosra/magnum@2145ae9b969f058e39bcaa008c7e5f6bab57189e, mosra/magnum-plugins@ffe2f386f78f415ee6fd8dd81507a80f2ee346e6, mosra/magnum-integration@898e2d846236ff232e9451d55392444d712e49fb and mosra/magnum-examples@f9adf62d6b764123a96b79e6331b1e1935e2d321. The `base-nacl` bootstrap project was removed as well. 

The projects now received updates needed for making WebAssembly possible. There will be a blog post about this (and a bunch of live wasm examples) on http://blog.magnum.graphics/ soon-ish.
