### ISSUE TITLE
Framebuffer target is wrong for GLES2

### ISSUE THREAD

**Issue by julee** [mosra/magnum#204]
For GLES2, glBindFramebuffer, the param target only support GL_FRAMEBUFFER (without extension).

void Framebuffer::renderbufferImplementationDefault(const BufferAttachment attachment, const GLuint renderbufferId)
call:  glFramebufferRenderbuffer(GLenum(bindInternal()), GLenum(attachment), GL_RENDERBUFFER, renderbufferId);

bindInternal() returns   FramebufferTarget{}; this will make GLenum(bindInternal()) to 0,  glFramebufferRenderbuffer(0, xxxx) is illegal, so it  failed!

**Comment by mosra** [comment]
Hello,

thanks for the report! I managed to reproduce this locally -- ES2 context on my machine supports `NV_framebuffer_blit` and so I probably never tested for a case where separate read/write framebuffer bindings are not supported.

Will look into this now and fix it.

**Comment by mosra** [comment]
Should be fixed in 219417e0fdd84629526d1ee2cd54d7472c6753ec.
