### ISSUE TITLE
BoolVector bit setting bug

### ISSUE THREAD

**Issue by Crisspl** [mosra/magnum#208]
I think you've got a little bug [here](https://github.com/mosra/magnum/blob/master/src/Magnum/Math/BoolVector.h#L125). If `value` is `false`, then i-th bit won't be set to 0. I was wondering if you just meant this method to set to 1 a bit (probably *set* can be understood like this in context of bits), but then presence of `value` argument doesn't make sense to me, so I think it's a bug. I was looking for a proper solution and [there](https://stackoverflow.com/questions/47981/how-do-you-set-clear-and-toggle-a-single-bit) I found it.

**Comment by mosra** [comment]
Fixed with #210. Thanks a lot!
