### ISSUE TITLE
Texture::setStorage will pass a wrong TextureForamt to setImage when texture_storage is not support

### ISSUE THREAD

**Issue by julee** [mosra/magnum#214]
Texture::setStorage api:

        /**
         * @brief Set storage
         * @param levels            Mip level count
         * @param internalFormat    Internal format
         * @param size              Size of largest mip level
         * @return Reference to self (for method chaining)
         *
         * After calling this function the texture is immutable and calling
         * @ref setStorage() or @ref setImage() is not allowed.
         *
         * If neither @extension{ARB,direct_state_access} (part of OpenGL 4.5)
         * nor @extension{EXT,direct_state_access} desktop extension is
         * available, the texture is bound before the operation (if not
         * already). If neither @extension{ARB,texture_storage} (part of OpenGL
         * 4.2), OpenGL ES 3.0 nor @extension{EXT,texture_storage} in OpenGL
         * ES 2.0 is available, the feature is emulated with sequence of
         * @ref setImage() calls.
         * @see @ref maxSize(), @ref setMaxLevel(), @fn_gl2{TextureStorage1D,TexStorage1D} /
         *      @fn_gl2{TextureStorage2D,TexStorage2D} / @fn_gl2{TextureStorage3D,TexStorage3D},
         *      @fn_gl_extension{TextureStorage1D,EXT,direct_state_access} /
         *      @fn_gl_extension{TextureStorage2D,EXT,direct_state_access} /
         *      @fn_gl_extension{TextureStorage3D,EXT,direct_state_access},
         *      eventually @fn_gl{ActiveTexture}, @fn_gl{BindTexture} and
         *      @fn_gl{TexStorage1D}/@fn_gl{TexStorage2D}/@fn_gl{TexStorage3D}
         * @todo allow the user to specify PixelType explicitly to avoid
         *      issues in WebGL (see setSubImage())
         */
        Texture<dimensions>& setStorage(Int levels, TextureFormat internalFormat, const VectorTypeFor<dimensions, Int>& size) {
            DataHelper<dimensions>::setStorage(*this, levels, internalFormat, size);
            return *this;
        }

When texture_storage is not  support, use setImage, but the texture format for this two function is not the same.
For example, when we want set texture format to rgba,  for GLES2, with texture_storage extension,
glTexStorage2DEXT require format such as GL_RGBA8.
but glTexImage2D needs GL_RGBA. GL_RGBA8 is an illegal value.

With Magnum:
Texture::setStorage will call glTexStorage2DEXT or glTexImage2D according the runtime device, when we set  the Magnum::TextureFormat::RGBA8 for the TextureFormat param of this function, if will fail when running on devivce without texture_storage extension. If we use Magnum::TextureFormat::RGBA, it will fail when the device has texture_storage extension.

By the way, I doubt magnum may has other bugs seems like this. I suggest  run unittest on a devivce without any extension, and just basic gles 2.0 support, such as Android Emulator(with  GPU Graphics support ).

**Comment by mosra** [comment]
Hello, yes I am *very* aware of this, it's quite a nightmare corner case.

I'm not sure if there is a way to make the texture storage fallback working well on all possible configurations and platforms (it would need to do some very complicated enum mapping which would be another source of nightmares), so I suggest just using the `setImage()` API on affected platforms directly:

```cpp
#ifdef MAGNUM_TARGET_GLES2
if(!Context::current().isExtensionSupported<Extensions::EXT::texture_storage>()) {
    texture.setImage(0, TextureFormat::RGBA, ...);
} else 
#endif
{
    texture.setStorage(1, TextureFormat::RGBA8, ...);
}
```

Would that be a solution for you?

**Comment by julee** [comment]
Yeah， this way can work around this problem， but it break the encapsulation of the setStorage api, user doesn't known if setStorage will work when running on user's device, so they have to check the extension support before using it (the reason it the inner implement may not work).

 The platofrom whitch doesn't have texture storage api(mabe just GLES 2) doesn't have much too much internalformat for glTexImage*D api, without extension, only GL_ALPHA, GL_LUMINANCE, GL_LUMINANCE_ALPHA, GL_RGB, GL_RGBA., may be some extesion may provide more extra formats, but it  won't be too much, and less be used. 
 I think the magnum can just convert targeting those formats, and add a note to the documentation of this api.

 Currently I just modified the AbstractTexture.cpp storageImplementationFallback method, change all

         DataHelper<2>::setImage(*this, level, internalFormat,
                ImageView2D{format, type, Math::max(Vector2i(1), size >> level)});

         DataHelper<2>::setImage(*this, level, (TextureFormat)(int)format,
                ImageView2D{format, type, Math::max(Vector2i(1), size >> level)});

as imageFormatForInternalFormat has already implent the convertion for almost all formats, and it almost all ways corrent using it as the Internal Format ... (Mabe some infrequent extension formats won't work here, but a platform just without texture storage extension will have extension to support those formats? )

**Comment by mosra** [comment]
Hey, that is a great idea, thank you! So simple and yet it never occured to me. Yes, I think it should "just work" in majority of cases, I'm not aware of any ES2/WebGL1 extension that would break this assumption.

I'm currently travelling, so I'm not able to put this in until Wednesday evening the earliest. Is that okay for you?

**Comment by julee** [comment]
Yes, of course.

**Comment by mosra** [comment]
Pushed the initial change as 98a676ef653fc956b375712bc7765e622a6dd2e9, but immediately after discovered that it's not doing the right thing for sRGB textures. That needs a bigger change, I will fix that later, so keeping this open.

Please tell me if at least this works for you.

**Comment by julee** [comment]
It works for me now on Android.
Thank you.

**Comment by mosra** [comment]
sRGB textures should be working properly now as well. Details in 929329b1f8363ac5e6f8688423c6c6854014865e.
