### ISSUE TITLE
Improve error checking with the CMake build when finding libpng

### ISSUE THREAD

**Issue by AndySomogyi** [mosra/magnum#215]
If the runtime dynamically linked libpng is different than the libpng header files that Magnum was compiled with, then it will result is a rather nasty exception:

```
 Assertion file failed in .../src/MagnumPlugins/PngImporter/PngImporter.cpp on line 71
```

This happens if you have more that one version of libpng installed (surprisingly common, as many programs install libpng). 

I think we could improve the CMake by having it check to see if the runtime linked libpng is in the same directory tree as the header directory. I think some version info checking would make the runtime error detection a lot nicer. 

The ```png_libpng_ver``` libpng global holds the current version: 
<https://refspecs.linuxfoundation.org/LSB_5.0.0/LSB-Desktop-generic/LSB-Desktop-generic/libpng12-png-libpng-ver.html>

So, something like 
```C++
if (strcmp (PNG_LIBPNG_VER_STRING, png_libpng_ver) != 0) {
Error() << "libpng version mismatch, expecting version " << PNG_LIBPNG_VER_STRING 
   << " but the runtime library is version: " << png_libpng_ver;
}
```

**Comment by AndySomogyi** [comment]
No problem, but will have to wait until next week.

**Comment by mosra** [comment]
Done in mosra/magnum-plugins@ecc9c0bb667a36630c881a55538bd53e9a1f66b8. In the end I decided to use an assert as well (it points out to a broken installation which can't really be solved from within the app at runtime), but this time it at least gives a helpful message. Thanks for the initial patch!
