### ISSUE TITLE
OpenAL Licensing Concerns

### ISSUE THREAD

**Issue by Xeverous** [mosra/magnum#221]
Hey, it's me again. I stopped when I realized that while Magnum is on MIT licence the required OpenAL for audio is propertiary. I have found that there is Open AL Soft, which uses LGPL license but this one on itself has concerns. 

From Wikipedia:

> The main difference between the GPL and the LGPL is that the latter allows the work to be linked with (in the case of a library, "used by") a non-(L)GPLed program, regardless of whether it is free software or proprietary software.[1] The non-(L)GPLed program can then be distributed under any terms if it is not a derivative work. If it is a derivative work, then the program's terms must allow for "modification for the customer's own use and reverse engineering for debugging such modifications." Whether a work that uses an LGPL program is a derivative work or not is a legal issue. A standalone executable that dynamically links to a library through a .so, .dll, or similar medium is generally accepted as not being a derivative work as defined by the LGPL. It would fall under the definition of a "work that uses the Library".

This brings even more problems if the library code is used to derive classes and instantiate C++ templates. I don't even know if the Soft version would work with Magnum.

My questions:
- Is there any way for fully MIT-compatile usage of Magnum audio part? Or should I just resign of it and find a standalone MIT audio library?
- Are there any other Magnum parts that may not be MIT licensed?

**Comment by Squareys** [comment]
> Is there any way for fully MIT-compatile usage of Magnum audio part? Or should I just resign of it and find a standalone MIT audio library?

I used Magnum::Audio with openal-soft and it works. Also, the Magnum::Audio has no real notion of OpenAL Soft, it's just a implementation of OpenAL which is linked to dynamically through the OpenAL API. So I *think* you should be fine. (But I'm not a lawyer and so on 😜 )

**Comment by Xeverous** [comment]
Wikipedia says there are still concerns of licensing statically (and even dynamically) linked software with LGPL parts, although the autors have [said C++ templates](https://listengine.tuxfamily.org/lists.tuxfamily.org/eigen/2008/02/msg00003.html) are valid.

**Comment by Squareys** [comment]
But

> A standalone executable that dynamically links to a library through a .so, .dll, or similar medium is generally accepted as not being a derivative work as defined by the LGPL.

states pretty clearly it's ok?

**Comment by Xeverous** [comment]
"generally". Ideally I want a full MIT library stack

**Comment by mosra** [comment]
Hi!

I don't see this being a problem. Yes, Magnum works with OpenAL Soft -- that's basically the only version of OpenAL available on Linux and I can confirm it always worked here.

OpenAL Soft is *not* bundled in Magnum and as long as you link to an unmodified distribution of it dynamically, you fulfilled the license requirements and can publish your stuff without worrying about releasing all the sources. Its API is also a pure C interface, which means there are no issues with C++ templates.

Speaking from personal experience: in a past project we were making a proprietary embedded software using a **modified version** of Qt. Qt is LGPL, so after some negotiating with our lawyers we were presented with two options:

1. either buy the commercial Qt license so we don't have to release our patches to Qt, can link statically and don't need to give credit
2. or publicly release our patches to Qt as required by LGPL, link to it dynamically and give them credit somewhere in the manual of the released software together with a link to download the patched sources

In the end we went with option 2. Having to budle a bunch of additional shared libraries was a bit of pain, but not so much. In neither case we would need to release source code of our app. So as long as you can use unmodified OpenAL, you can "just use it" and there's no clash with MIT *as long as* you link to it dynamically.

> Or should I just resign of it and find a standalone MIT audio library?

You could use SDL audio instead, but I'm not sure about support on all platforms. OpenAL has wider support as far as I can say.

> Are there any other Magnum parts that may not be MIT licensed?

There are examples, which are public domain, other than that everything is MIT. The only part that comes close to the above is the ColladaImporter plugin, which depends on Qt (LGPL). Mmmayybee using GlutApplication against some version of GLUT that has GPL-like license might *hypothetically* be a problem, but who's using that anyway.

If a *hypothetical* platform would have OpenGL drivers that are GPL, then .. well, I don't know. That would be a clash of licenses I think. No such problem with OpenAL.

I'm also not a lawyer, so take that into account when reading the above ;)

**Comment by Xeverous** [comment]
Much thanks for detailed answer.  *Sounds* like I can go with OpenAL Soft, but I think you should warn users that OpenAL has different lincensing than OpenAL Soft (all the CMake and github mentions just "OpenAL").

**Comment by mosra** [comment]
Okay, good idea. Reopening until I update the docs.

**Comment by Xeverous** [comment]
Sorry, I have another question. I'm having trouble understanding `WITH_*APPLICATION` `WITH_*CONTEXT` switches in CMake. I'm not sure what I should (not) mark in order to be able to create borderless (or fullscreen) applications that have multiplatform abstraction in code and work everywhere.

**Comment by mosra** [comment]
Hmm, I think this could be better explained through a chat than here. Can you join Gitter at https://gitter.im/mosra/magnum ? You can log in using your GitHub account.

**Comment by Xeverous** [comment]
Sorry, I don't have more time today. I want to fully explore Magnum but no not fall into any features that would disable build on some platforms. Reading CMake switches concerned me about borderless and fullscreen windows.

**Comment by mosra** [comment]
Hmm. Closing as resolved, I think :)
