### ISSUE TITLE
CASCADED_DUE_TO_MISSING_DEPENDENCIES

### ISSUE THREAD

**Issue by grandprixgp** [mosra/magnum#232]
Following [vcpkg quick start docs](https://github.com/Microsoft/vcpkg#quick-start) and [Magnum vcpkg build docs](http://doc.magnum.graphics/magnum/building.html#building-packages-vcpkg).

Not sure where to go with this error, seemingly all dependencies fulfilled.

https://gist.github.com/grandprixgp/0e4df592550903b810c4f5037c031f54

**Comment by mosra** [comment]
Hmm. Looks like some weird `vcpkg` bug to me :/ Can you try explicitly installing Corrade first?

```bat
vcpkg install corrade:x64-windows-static
vcpkg install magnum:x64-windows-static
```

**Comment by grandprixgp** [comment]
Thanks for the quick response ;)

I had already tried manually installing the problematic dependency (corrade) at first hoping that it would give me another error that I could work with, no luck unfortunately 👎 

> PS C:\src\vcpkg> .\vcpkg install corrade:x64-windows-static
The following packages will be built and installed:
    corrade[core,interconnect,pluginmanager,testsuite,utility]:x64-windows-static
Starting package 1/1: corrade:x64-windows-static
Building package corrade[core,interconnect,pluginmanager,testsuite,utility]:x64-windows-static...
Error: Building package corrade:x64-windows-static failed with: CASCADED_DUE_TO_MISSING_DEPENDENCIES
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: corrade:x64-windows-static
  Vcpkg version: 0.0.105-2018-02-26-71d44cebdb85926bc00241fc08f0dcaaedb868d2

I did open a separate issue with vcpkg [here](https://github.com/Microsoft/vcpkg/issues/2891) just FYI.

I've tried multiple clean installs of vcpkg, I have made sure I have all of the requirements, upgraded VS 2017, reinstalled VS CMake integrations, etc.

I feel like there might be a small requirement or system dependency causing this that I'm missing but I can't find anything, and the vcpkg logs are really useless.

**Comment by mosra** [comment]
@Squareys did this package update (and also implemented part of the [Features](https://github.com/Microsoft/vcpkg/blob/master/docs/specifications/feature-packages.md) thing in `vcpkg` itself). Magnum is one of the first packages making heavy use of the vcpkg features, so there might be some corner cases where this doesn't work properly yet. He might know what's the culprit, but he's busy until tomorrow afternoon :)

Can you try installing the dynamic version? I think the dynamic one worked. (I don't have an access to a Windows machine at the moment to try it out myself.)

**Comment by grandprixgp** [comment]
The error appears to be the same for all versions. I tried `--head` too. I will throw up a Paperspace Windows VM shortly and try this out on a fresh machine, might as well. If it comes down to it, I can still build everything manually to try out Magnum, I was just excited hyped to try it out with such ease using `vcpkg`.

**Comment by mosra** [comment]
Another random idea:

```bat
vcpkg install corrade[utility]:x64-windows-static
vcpkg install corrade:x64-windows-static
vcpkg install magnum:x64-windows-static
```

(I hope that's the correct syntax, hehe.) There seems to be a problem with inter-package dependencies, but according to @Squareys this all worked a week ago, huh.

**Comment by grandprixgp** [comment]
> PS C:\src\vcpkg> .\vcpkg install corrade[utility]:x64-windows-static
The following packages will be built and installed:
    corrade[core,interconnect,pluginmanager,testsuite,utility]:x64-windows-static
Starting package 1/1: corrade:x64-windows-static
Building package corrade[core,interconnect,pluginmanager,testsuite,utility]:x64-windows-static...
Error: Building package corrade:x64-windows-static failed with: CASCADED_DUE_TO_MISSING_DEPENDENCIES
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: corrade:x64-windows-static
  Vcpkg version: 0.0.105-2018-02-26-71d44cebdb85926bc00241fc08f0dcaaedb868d2

I've got VS and such installing on a Windows VM as we speak, will let you know if this is happening there too asap.

**Comment by grandprixgp** [comment]
[Seems this isn't limited to my machine.](https://i.imgur.com/YaRosfK.png)

Fresh Windows Server 2016 deployment with VS 2017 Community + Linux Buildtools + CMake 3.10.2

**Comment by mosra** [comment]
Oh well. Sorry about the time wasted.

Hopefully Squareys will have an idea what's wrong tomorrow.

**Comment by grandprixgp** [comment]
No need to apologize :+1: Excited to try Magnum out regardless.

**Comment by grandprixgp** [comment]
@mosra Good news, this was resolved on vcpkg' side by Robert https://github.com/Microsoft/vcpkg/issues/2891#issuecomment-368679006 and I can confirm everything builds properly now.

**Comment by mosra** [comment]
Yay! Happily closing this, then :)
