### ISSUE TITLE
Ams.js and flags "-s USE_PTHREADS=1" and "--closure 1"

### ISSUE THREAD

**Issue by lecopivo** [mosra/magnum#239]
My application is multi-threaded and I would like to compile it for the web. However I'm having some troubles. 

As a first step I wanted to compile =magnum-triangle= from =magnum-examples= with thread support. But already this does not work for me. There are two problems:

1: when I compile using Emscipten(to Ams.js) with "-s USE_PTHREADS=1" I have to turn off "--closure 1" otherwise the compilation does not complete. 

2: Adding flag "-s USE_PTHREADS=1" breaks shader compilation. This is the error I get in a browser(Firefox Nightly):
![untitled](https://user-images.githubusercontent.com/6596305/37838945-8585712a-2eb9-11e8-89f3-9d44a03a5ee6.png)

What is going on?

**Comment by Squareys** [comment]
If you are not calling any of the threading functionality (it sounds like you are just compiling the code with that flag), this is likely a Emscripten bug.
Maybe try compiling to WASM also.

Apart from that, I just found a note [in the docs](https://kripken.github.io/emscripten-site/docs/porting/pthreads.html) that pthreads support may currently not be working in browsers without enabling some settings.

**Comment by lecopivo** [comment]
Yes I'm not using any threading functionality. The problem is the presence of the flag.

On the other hand, I have managed to compile simple c++ threading application(based on this [https://stackoverflow.com/a/31466135/1258071](url)). I had to use Ams.js and tweak settings of my browser(as you have mentioned). For some reason I was unable to get this simple application running under WASM.

But you are right that this is probably Emscripten bug and I will ask on their site.

**Comment by mosra** [comment]
Oh, sorry about the `--closure` flag, I need to throw that away already, it's only making the build slower and more broken.

I never tried threading with WASM myself, but I would say it's meant to work better than any hacks with asm.js and WebWorkers. Some info that might be helpful: https://github.com/WebAssembly/binaryen/issues/1085

The shader compiler error looks like all the shader sources are empty, like if Emscripten just gave up and didn't supply any memory image, huh.

**Comment by lecopivo** [comment]
Now, I have tested it also with WASM and the error is the same. It looks like the shader sources are empty. (btw based on this [https://github.com/kripken/emscripten/wiki/Pthreads-with-WebAssembly](url) I had to install `incoming` branch of emscripten which I didn't have before.)

Here is the test:

Threading test - just to test your browser(you need Firefox Nightly and enabled threading):
[http://pub.ist.ac.at/~tskrivan/pthreads-test/main.html](url)

Magnum-triangle example - this should run on any modern browser
[http://pub.ist.ac.at/~tskrivan/triangle-no-pthreads/magnum-triangle.html](url)

Magnum-triangle + compiled with "-s WASM=1 -s USE_PTHREADS=1"
[http://pub.ist.ac.at/~tskrivan/triangle-with-pthreads/magnum-triangle.html](url)

**Comment by mosra** [comment]
Finally was able to reproduce and track down the issue. For some weird reason it seems to be caused by UTF-8 characters in license headers of shader sources. Removing those makes it work again.

I have no idea why the flag would affect it, will investigate further.

**Comment by mosra** [comment]
Okay, found it: https://github.com/kripken/emscripten/blob/7f89560101843198787530731f40a65288f6f15f/src/fetch-worker.js#L54-L58

```js
/// TODO: DO SOMETHING ABOUT ME.
function Pointer_stringify(ptr, /* optional */ length) {
  if (length === 0 || !ptr) return "";
  // TODO: use TextDecoder
  // Find the length, and check for UTF while doing so
```

etc. So, apparently, at the moment, when using threads, if it discovers anything with UTF-8 in it, it will simply give up and return empty string. Ugh. The GL compiler then complains about getting an empty string as a shader source.

I'll put in a "driver workaround" to circumvent this.

**Comment by mosra** [comment]
Workaround is in since fff756ad063c9687ea03e5952c1c5e4665d48b55 -- if threaded Emscripten build is detected, all shader sources containing Unicode characters are patched to not contain them anymore. This also triggered me to implement a few improvements across the board, so expect some Emscripten-related updates soon.

Also, since ec41dc4bab22e60002950a560bc67082eb4ddb79 the toolchain was updated to not use `--closure` anymore. There was some nasty issue that overwrote CMAKE_CXX_FLAGS, that's fixed as well.

The workaround is reported in the console output as shown below. If you are using the Magnum builtin JS runner, adding `?magnum-disable-workarounds=emscripten-pthreads-broken-unicode-shader-sources` to the query string will restore the unpatched behavior. 

![image](https://user-images.githubusercontent.com/344828/37878552-2f8d6120-306b-11e8-9ca7-1c988feb04d5.png)

I'm too lazy/annoyed to complain upstream, though :)

**Comment by lecopivo** [comment]
Thanks a lot for fixing this! I will try it out tomorrow.

**Comment by lecopivo** [comment]
Yay! It workds :champagne: I was really curious, so I tested it now.

**Comment by lecopivo** [comment]
I'm a PhD student doing research in computer graphics/physics simulation and I really want to share my demos online. However, physics simulation can be computationally demanding so I would like to have multi-threading. 

Currently I'm polishing my code for our paper which just got accepted to Siggraph, I will share it in few weeks and hopefully I will be able to get the demo working in a browser.

**Comment by mosra** [comment]
Cool! :)
