### ISSUE TITLE
 magnum in a hooked context?

### ISSUE THREAD

**Issue by saedrna** [mosra/magnum#242]
Is it possible to use magnum in a hooked contex? This requires magnum to create context from existing opengl dc and render a frame into the hooked swapbuffer function.

**Comment by Squareys** [comment]
Hi @saedrna !

Have a look at [State tracking and interaction with third-party code](http://doc.magnum.graphics/magnum/opengl-wrapping.html#opengl-state-tracking), it shows how to reset `Magnum::Context` to have magnum work with external contexts.

You can simply call the swapbuffer function yourself, if you don't use any of the `Magnum::*Application` classes. If you do, you can simply not call `*Application::swapBuffers()` (e.g. in [Sdl2Application](http://doc.magnum.graphics/magnum/classMagnum_1_1Platform_1_1Sdl2Application.html#a2e6c2689b7f733fb4949e7d35664e993) and call your own swap buffers... I think. (@mosra may want to confirm this.)

Hope that helps!

**Comment by saedrna** [comment]
Thanks @Squareys !

For the following pipeline, structured in native opengl calls,

```
HGLRC hrc_hook;
HGLRC hrc_native;
// this is a hooked function 
BOOL WINAPI hook_SwapBuffers( HDC hdc ){
    // for the first time, initialize a new rendering context
    if(first) {
        hrc_native = wglGetCurrentContext();
        hrc_hook = wglCreateContext(hdc);
    }
    // draw into my own contecx to prevent strange things
    wglMakeCurrent(hdc, hrc_hook); 

    // reset to native
    wglMakeCurrent(hdc, hrc_native);
    
    native_SwapBuffer(hdc); 
}
```

How to initialize the magnum context? So I can call something like `mesh.draw()` inside this? Also, as far as I know, the mesh has to be initialized in the same context.

**Comment by Squareys** [comment]
I am a little confused at what you're trying to do. Do you want to draw stuff *inside* this hook_SwapBuffers function?

Then from the link to the docs I mentioned, it should be something like

~~~cpp
HGLRC hrc_hook;
HGLRC hrc_native;
Platform::Context magnumContext{NoCreate};

// this is a hooked function 
BOOL WINAPI hook_SwapBuffers( HDC hdc ){
    // for the first time, initialize a new rendering context
    if(first) {
        hrc_native = wglGetCurrentContext();
        hrc_hook = wglCreateContext(hdc);
    }
    // draw into my own contecx to prevent strange things
    wglMakeCurrent(hdc, hrc_hook);
    if(first) magnumContext = Context();
    else
        Context::current().reset(Context::State::ExitExternal);

    Mesh mesh;
    Shaders::Phong shader;
    //...
    mesh.draw(_shader);

    // reset to native
    Context::current().reset(Context::State::EnterExternal);
    wglMakeCurrent(hdc, hrc_native);
    
    native_SwapBuffer(hdc); 
}
~~~

Some relevant doc links: [Platform::Context](http://doc.magnum.graphics/magnum/classMagnum_1_1Platform_1_1Context.html) and [Plain GLFW Example page](http://doc.magnum.graphics/magnum/examples-triangle-plain-glfw.html).

\* *Written off the top of my head and using the docs, no guarantee that it compiles like that.*

**Comment by saedrna** [comment]
Thanks, I think now I get the basic ideas in magnum.
