### ISSUE TITLE
LOD implementations?

### ISSUE THREAD

**Issue by saedrna** [mosra/magnum#244]
Hi, for large scale scenes, LOD with disk paging is necessary. Is there an example or some tutorials for this in magnum?

Thanks.

**Comment by mosra** [comment]
Hi! :)

I *think* @Squareys had some LOD implementation for terrain rendering, maybe he'll have something to share. Other than that, there is no example or tutorial for LOD at the moment.

You could use [Utility::Directory::map()](http://doc.magnum.graphics/corrade/namespaceCorrade_1_1Utility_1_1Directory.html#a84c45342a8cec2111853f51873d82c9d) to memory-map large files for streaming, [SampleQuery](http://doc.magnum.graphics/magnum/classMagnum_1_1SampleQuery.html) for querying how large a placeholder object could be on screen and then choosing a particular LOD level (or trigger a load of it). [Sparse textures](https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_sparse_texture.txt), if you need that, are not exposed in the Magnum API yet, but the OpenGL functions are exported and you can call the functions directly.

**Comment by saedrna** [comment]
Thanks, SampleQuery is helpful and finally I have to implement a small pipeline to get this done.
