### ISSUE TITLE
Error in GlfwApplication:  Platform::GlfwApplication::tryCreate(): context already created

### ISSUE THREAD

**Issue by underdoeg** [mosra/magnum#247]
I was able to solve it by setting the _window = nullptr here:
https://github.com/mosra/magnum/blob/master/src/Magnum/Platform/GlfwApplication.h#L483

System is an up to date arch linux 64bit, compiling with gcc

**Comment by mosra** [comment]
Hi, sorry about this, I should have tested more :see_no_evil: A PR with fix was submitted a few hours ago in #246 and I just merged it together with some further improvements to GlfwApplication.
