### ISSUE TITLE
Documentation refers to `grid3DWireframe` which is now `planeWireframe`

### ISSUE THREAD

**Issue by kghose** [mosra/magnum#250]
http://doc.magnum.graphics/magnum/namespaceMagnum_1_1Primitives.html#a878f9ac70bc18e2af290d779931f1c29

vs

https://github.com/mosra/magnum/blob/b1c60c1b78d470a1e12bd1131998fb087ecb1546/src/Magnum/Primitives/Plane.h#L74

**Comment by mosra** [comment]
Yes, there are both and both have their uses :)
