### ISSUE TITLE
Magnum/GL/DefaultFrameBuffer.h: No such file or directory (Ubuntu)

### ISSUE THREAD

**Issue by kghose** [mosra/magnum#252]
Hi @mosra !

When you get a chance could you take a look at [this build error](https://circleci.com/gh/kghose/groho/14) please?

It's building on an ubuntu based image. I used the recommended way to add Magnum, and CMake initializes fine (i.e. finds everything) but the build fails with

```
Magnum/GL/DefaultFrameBuffer.h: No such file or directory
```

The same code is compiling fine on my local mac.

Thanks!
-Kaushik

**Comment by mosra** [comment]
I suspect it's because macOS (and Windows) default filesystem is case-insensitive, while Linux has it case-sensitive. The correct casing is:

```cpp
#include <Magnum/GL/DefaultFramebuffer.h>
```

with lowercase `b` ;)

**Comment by kghose** [comment]
@mosra That was it! Thanks!
