### ISSUE TITLE
Broken feature parity between SDL2Application and GLFWApplication

### ISSUE THREAD

**Issue by Consti10** [mosra/magnum#256]
For Sdl2Application there is a distinction between left,middle,right,x1,x2 Movements in the `Sdl2Apllication::MouseMoveEvent` class. That's not the same for `GlfwApplication:: MouseMoveEvent.`
Therefore, you cannot toggle between **sdl2** / **glfw** in "Magnum Viewer example", but have to uncomment
`if(!(event.buttons() & MouseMoveEvent::Button::Left)) return; ` first.

**Comment by mosra** [comment]
For the record: as we talked about in person, this got fixed independently in the meantime. See 80e682d04616ae2b5606f62f3652877b9700ddac for details. Closing as done then :)
