### ISSUE TITLE
Linker Errors

### ISSUE THREAD

**Issue by Jvac7785** [mosra/magnum#257]
Hey, I know this may not be the best place to post errors in my code, but I don't know of any other place.
I get a linker error from squareSolid()
Application.cpp:(.text+0x242): undefined reference to `Magnum::Primitives::squareSolid(Magnum::Primitives::SquareTextureCoords)'

**Comment by Jvac7785** [comment]
Never mind I am dumb
I needed to include Primitives in my CMake file

**Comment by mosra** [comment]
:slightly_smiling_face: 

For questions and general discussion there's the [Gitter chat room](https://gitter.im/mosra/magnum), you are welcome to join -- simply use your GitHub account to log in :)
