### ISSUE TITLE
Search feature or equivalent for docs

### ISSUE THREAD

**Issue by kghose** [mosra/magnum#260]
I miss the search widget. Would it be possible to arrange an alternative, please? Nowadays I need to go to a search engine and search from there. Thanks!

**Comment by mosra** [comment]
Hi, sorry -- the widget is still there, just the icon for it disappeared for some reason. Open it either by clicking on the empty space on far right where it always were before, or by pressing the Tab key.Not sure what happened there, will investigate later today when I get back on my computer.

**Comment by mosra** [comment]
Fixed now. Turns out a website update I did recently made the styling out of sync with docs that were generated earlier and so the icon either disappeared (on Chrome) or, on the other hand, appeared extremely oversized (on Firefox, see #261).

Sorry about the mess ;)
