### ISSUE TITLE
[Docs-Web] Search icon oversized 

### ISSUE THREAD

**Issue by TheAifam5** [mosra/magnum#261]
Hey,

I noticed on the [doc](http://doc.magnum.graphics/doc/magnum/) website that the search icon is too big :D 

![image](https://user-images.githubusercontent.com/2192274/42738636-30d619ae-8887-11e8-91cf-0c68d3c52364.png)

Regards,
TheAifam5

**Comment by mosra** [comment]
Hi, thanks a lot for the report. 

I messed up when doing website update and the styling got out of sync, causing this (or, on Chrome, making the icon completely disappear, see #260).

Fixed now, sorry for the mess :see_no_evil: ;)
