### ISSUE TITLE
Trying to understand an issue I'm having with supported extensions

### ISSUE THREAD

**Issue by nnarain** [mosra/magnum#270]
I have the following vertex shader code:

```c++
  const char *vertex_shader =
      // "#ifndef NEW_GLSL\n"
      // "#define in attribute\n"
      // "#define out varying\n"
      // "#endif\n"
      "\n"
      "#ifdef EXPLICIT_UNIFORM_LOCATION\n"
      "layout(location = 0)\n"
      "#endif\n"
      "  uniform mediump mat4 ProjMtx;\n"
      "\n"
      "#ifdef EXPLICIT_ATTRIB_LOCATION\n"
      "layout(location = 0)\n"
      "#endif\n"
      "  in mediump vec2 Position;\n"
      "\n"
      "#ifdef EXPLICIT_ATTRIB_LOCATION\n"
      "layout(location = 1)\n"
      "#endif\n"
      "  in mediump  vec2 UV;\n"
      "\n"
      "#ifdef EXPLICIT_ATTRIB_LOCATION\n"
      "layout(location = 2)\n"
      "#endif\n"
      "  in mediump vec4 Color;\n"
      "\n"
      "out mediump vec2 Frag_UV;\n"
      "out mediump vec4 Frag_Color;\n"
      "\n"
      "void main()\n"
      "{\n"
      "  Frag_UV = UV;\n"
      "  Frag_Color = Color;\n"
      "  gl_Position = ProjMtx * vec4(Position.xy,0,1);\n"
      "}\n";

const char *fragment_shader = ... // Omitting fragment shader stuff

```

Note the `EXPLICIT_ATTRIB_LOCATION` and `EXPLICIT_UNIFORM_LOCATION` `ifdef`s.

Then grab the OpenGL version and Initialize the shader:

```c++
  const GL::Version version = GL::Context::current().supportedVersion(
      {  GL::Version::GL330, GL::Version::GL310, GL::Version::GL300, GL::Version::GL210});

  GL::Shader vert{version, GL::Shader::Type::Vertex};
```
My system uses OpenGL 4.5, so GL::Version::GL330 is returned.

Now I want to have shaders explicitly set the attribute and uniform locations if it is supported. So I check if the extensions `explicit_attrib_location` and `explicit_unifrom_location` are supported for the current version:

```c++
  if (GL::Context::current().isExtensionSupported<GL::Extensions::ARB::explicit_attrib_location>(version)) {
    vert.addSource({"#define EXPLICIT_ATTRIB_LOCATION\n"});
  }
  else {
    bindAttributeLocation(Position::Location, "Position");
    bindAttributeLocation(TextureCoordinates::Location, "UV");
    bindAttributeLocation(Color::Location, "Color");
  }
```

`isExtensionSupported` returns true in this case and things are working as expected.

Now finally the issue I'm trying to understand.

```c++
 if (GL::Context::current().isExtensionSupported<GL::Extensions::ARB::explicit_uniform_location>(version)) {
    vert.addSource({"#define EXPLICIT_UNIFORM_LOCATION\n"});
}
```
`isExtensionSupported` returns true, but the shader fails compilation stating that setting the uniform location is not supported.

Adding `GL::Version::GL430` to the `supportedVersion` check makes things work. OpenGL 4.3 is the core version of the `explicit_uniform_location` extension.

At the moment I'm doing the following checks but not sure if it is the best way:

```c++
  if (GL::Extensions::ARB::explicit_uniform_location::coreVersion() <= version) {
    vert.addSource({"#define EXPLICIT_UNIFORM_LOCATION\n"});
  }
```

Advice appreciated.

**Comment by mosra** [comment]
Hi, thank you for the very detailed report! :+1: 

This is interesting and sounds like a driver issue. The workaround you mentioned may be a solution. What's your system, GPU, driver version?

The builtin shaders use this exact same approach and I'm currently running on Linux with Mesa Intel drivers and GL 4.5 without any problem. 

I have a few test cases for this that might help uncover the root of the problem. Not sure whether you have Magnum built from source or from a package, but would be possible for you to build it from source with both `BUILD_TESTS` and `BUILD_GL_TESTS` enabled and then run `ShadersPhongGLTest`? Like this, using CTest:

```sh
ctest -V -R ShadersPhongGLTest
```

Please paste the output here after.

**Comment by nnarain** [comment]
Output from `ShadersPhongGLTest`.

```bash
Renderer: AMD Radeon (TM) R9 380 Series by ATI Technologies Inc.
OpenGL version: 4.5.13506 Compatibility Profile/Debug Context 23.20.15017.3010
Using optional features:
    GL_ARB_ES2_compatibility
    GL_ARB_direct_state_access
    GL_ARB_get_texture_sub_image
    GL_ARB_invalidate_subdata
    GL_ARB_multi_bind
    GL_ARB_separate_shader_objects
    GL_ARB_texture_filter_anisotropic
    GL_ARB_texture_storage
    GL_ARB_texture_storage_multisample
    GL_ARB_vertex_array_object
    GL_EXT_direct_state_access
    GL_KHR_debug
Using driver workarounds:
    no-forward-compatible-core-context
    no-layout-qualifiers-on-old-glsl
Starting Magnum::Shaders::Test::PhongGLTest with 15 test cases...
    OK [01] construct()
    OK [02] construct(ambient texture)
    OK [03] construct(diffuse texture)
    OK [04] construct(specular texture)
    OK [05] construct(ambient + diffuse texture)
    OK [06] construct(ambient + specular texture)
    OK [07] construct(diffuse + specular texture)
    OK [08] construct(ambient + diffuse + specular texture)
    OK [09] construct(alpha mask)
    OK [10] construct(alpha mask + diffuse texture)
    OK [11] constructMove()
    OK [12] bindTextures()
    OK [13] bindTexturesNotEnabled()
    OK [14] setAlphaMask()
    OK [15] setAlphaMaskNotEnabled()
Finished Magnum::Shaders::Test::PhongGLTest with 0 errors out of 31 checks.
```

**Comment by nnarain** [comment]
All the shader tests are passing

**Comment by mosra** [comment]
I think I have it now, overlooked it before. In order to use explicit attribute location on shader versions below 430, you need to explicitly enable the extension, so basically adding this to your shader source:

```cpp
#ifdef EXPLICIT_UNIFORM_LOCATION
    #extension GL_ARB_explicit_uniform_location: enable
#endif
```

To be totally correct, you should do the same for explicit attribute location, i.e.:

```cpp
#ifdef EXPLICIT_ATTRIB_LOCATION
    #extension GL_ARB_explicit_attrib_location: enable
#endif
```

(In your case you are already beyond the minimal required version for explicit attrib location so it doesn't make any difference, but just to be sure.)

**Comment by mosra** [comment]
Awesome. Closing this one, then :)
