### ISSUE TITLE
Docs: Revise "Getting Started" with vcpkg on windows

### ISSUE THREAD

**Issue by Squareys** [mosra/magnum#271]
TODO for myself so that I don't forget to go over 
http://doc.magnum.graphics/magnum/building.html#building-packages-vcpkg
and put in some more useful information to prevent loads of issues being opened about vcpkg installation not working.

@mosra You may assign me :)

Cheers, Jonathan.

**Comment by mosra** [comment]
Resolved with #273 and https://github.com/mosra/magnum/commit/c8e3ee68db9f05de19877306504621178bb53b92, closing :)
