### ISSUE TITLE
Failing assertion in dpiScaling.hpp if Xorg RESOURCE_MANAGER not present

### ISSUE THREAD

**Issue by hannes-steffenhagen-diffblue** [mosra/magnum#290]
Platform: Linux (Anarchy Linux/Xorg/XMonad)
Happens when I try to build and run the triangle example (https://doc.magnum.graphics/magnum/examples-triangle.html). Didn't try yet, but it should happen in pretty much all projects.

Here:
https://github.com/mosra/magnum/blob/master/src/Magnum/Platform/Implementation/dpiScaling.hpp#L101-L105

It's asserted (internally) that a `RESOURCE_MANAGER` always exists. This isn't really reliable, if no resource database was explicitly created at some point then `xResourceManagerString` may return `nullptr`. I think the correct handling in this case would be to print the same warning as [here](https://github.com/mosra/magnum/blob/master/src/Magnum/Platform/Implementation/dpiScaling.hpp#L120) in this case.

This can be worked around by explicitly creating a resource database, but may be annoying especially for beginners.

**Comment by mosra** [comment]
Thanks for the report, good to know! Will fix that right away.

Is this the only case where the internal assertion might fail? 

As a different workaround, it should be possible to completely sidestep this code path by running the applications with a `--magnum-dpi-scaling physical` parameter.

**Comment by hanst99** [comment]
I believe this should be the only case in which the assertion fails, but I'm not really an expert on Xorg issues, this is just me reading the man page. As an aside, this leaks a small bit of memory; Technically you're supposed to free the returned string with `XFree` when you're done with it. Considering this only happens once on startup I wouldn't worry too much about it though.

**Comment by mosra** [comment]
*(pushed to the `next` branch as 89f7a5ee753e7c8d8b06f468f15b46c26371e946, [waiting on the CIs](https://magnum.graphics/build-status/?mosra/corrade=next&mosra/magnum=next&mosra/magnum-plugins=next&mosra/magnum-extras=next&mosra/magnum-integration=next&mosra/magnum-examples=next&mosra/magnum-examples=ports-next&mosra/magnum-bootstrap=next) to get green)*

> As an aside, this leaks a small bit of memory

I was reading through the [XrmGetResource](https://www.x.org/releases/X11R7.5/doc/man/man3/XrmQGetResource.3.html) manual and it says it always returns a pointer to the internal database, so no freeing needed. To verify that, I ran a test app with ASan enabled and it didn't report any leaks coming from this code (more precisely, it was reporting the same amount of leaks going through X11 and Mesa internals as when the DPI query is sidestepped using `--magnum-dpi-scaling physical`). So I think I'm good here.

**Comment by hanst99** [comment]
:heavy_check_mark: Works as advertised. Sorry it took a while for me to check this as for some reason I couldn't get my cmake configuration to use the Sdl2Application from the from-source-build rather than my system level install (had to uninstall while I was testing this).

**Comment by mosra** [comment]
Awesome, thanks. Closing as resolved, then :)

**Comment by hanst99** [comment]
(The note on memory leaks was just me misreading the man page, for future reference)
