### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by kororro** [mosra/magnum#291]
Hello.
At https://github.com/mosra/magnum  site,
"Magnum Plugins — various importer plugins for image, font, audio and 3D model formats is at https://github.com/mosra/magnum-plugins-plugins/branch/master)"
link doesnt work.

At  https://doc.magnum.graphics/magnum/getting-started.html site,
    "https://libsdl.org/download-2.0.php,"   (there is comma at link, so doesnt open right site).

**Comment by mosra** [comment]
You're awesome, thank you :+1: Fixed in edbb2820db0a922ed5ec670e4a1a6030be507028, the updated docs should be uploaded now as well.
