### ISSUE TITLE
Clang format config is impossible

### ISSUE THREAD

**Issue by mosra** [mosra/magnum#311]
Discovered this nice online tool: https://zed0.co.uk/clang-format-configurator/ and tried to fiddle with the options to match the [coding style described in the docs](https://doc.magnum.graphics/corrade/corrade-coding-style.html). Well, nope, not even close.

Current state of the config is here:

```.clang-format
AccessModifierOffset: '0'
AlignEscapedNewlines: Right
AlignTrailingComments: 'true'
AllowShortBlocksOnASingleLine: 'false'
AllowShortCaseLabelsOnASingleLine: 'true'
AllowShortFunctionsOnASingleLine: All
AllowShortIfStatementsOnASingleLine: 'true'
AllowShortLoopsOnASingleLine: 'true'
AlwaysBreakAfterDefinitionReturnType: None
AlwaysBreakAfterReturnType: None
AlwaysBreakTemplateDeclarations: 'false'
BreakBeforeInheritanceComma: 'false'
BreakBeforeTernaryOperators: 'false'
BreakConstructorInitializers: AfterColon
ColumnLimit: '500'
CompactNamespaces: 'true'
ConstructorInitializerIndentWidth: '4'
ContinuationIndentWidth: '0'
Cpp11BracedListStyle: 'true'
FixNamespaceComments: 'false'
IncludeBlocks: Preserve
IndentCaseLabels: 'true'
IndentWidth: '4'
IndentWrappedFunctionNames: 'false'
KeepEmptyLinesAtTheStartOfBlocks: 'false'
Language: Cpp
MaxEmptyLinesToKeep: '1'
NamespaceIndentation: None
PointerAlignment: Left
SortIncludes: 'true'
SpaceAfterCStyleCast: 'true'
SpaceAfterTemplateKeyword: 'false'
SpaceBeforeAssignmentOperators: 'true'
SpaceBeforeParens: Never
SpaceInEmptyParentheses: 'false'
SpacesBeforeTrailingComments: '1'
SpacesInAngles: 'false'
SpacesInContainerLiterals: 'true'
SpacesInParentheses: 'false'
SpacesInSquareBrackets: 'false'
Standard: Cpp11
UseTab: Never
```

What's discovered to be lacking:

- [ ] <kbd>critical</kbd> There's **no way** to tell it to keep some rule as-is, it always needs to have some opinion on stuff, removing indentation, indenting too much, adding/removing spaces and what else. Not possible to just *let it be*. That's a major blocker. For example: 
    - some smaller inner namespaces (such as `Implementation`) have their contents indented, but larger ones don't. Impossible to preserve.
    - rare functions with wrapped parameters / constructors with wrapped initializer list and an opening brace alone on a line are converted to brace on the same line. Impossible to preserve.
    - multi-line expressions get reformatted if names inside get longer or shorter, making diffs **HARD** to read
- [x] <kbd>critical</kbd> It's **not possible** to indent preprocessor macros. 6.0 has [an option to indent after `#`](https://stackoverflow.com/questions/24476165/indenting-preprocessor-directives-with-clang-format), which is beyond ugly. -- finally possible in Clang 9 with `PPDIS_BeforeHash`, it seems: https://clang.llvm.org/docs/ReleaseNotes.html#clang-format
- [ ] It's not possible to indent both the `public:` label *and* the inside (Yes, it's excessive indentation, but I won't be changing all code right now just to please clang-format.)
- [ ] headers are alphabetically ordered BUT MIXING UP FILES AND DIRECTORIES (who ever thought that's a good idea?!)
- [ ] (minor) Not possible to have a space in the `const &&` function qualifier

**Comment by Squareys** [comment]
I remember playing around with that configurator tool too quite some time ago. IIRC it doesn't allow configuration of a lot of variables that you could have. I also used https://github.com/johnmcfarlane/unformat on the Corrade code once, but the result wasn't too great either.

**Comment by mosra** [comment]
Clang 9 seems to *finally* have an option to indent preprocessor lines *before* the hash: https://clang.llvm.org/docs/ReleaseNotes.html#clang-format

However, from my experience using it on another project, it still does *way too many* unnecessary and unwanted formatting changes (for example, a multi-line expression gets totally reformatted if something inside gets longer/shorter, which I find *absolutely* unacceptable).

**Comment by mosra** [comment]
After ~~experiencing~~ suffering through clang-format firsthand on a larger project, I finally came to a conclusion that it's *absolutely* against my view of how a cleanly formatted code should look *and* how a code formatting utility should behave:

- A block of similarly-looking lines gets arbitrarily reformatted to fit some arbitrary line length limit, making them not look similar anymore and *harder to read*.
- STL includes are mixed up with 3rd party includes "to have them ordered alphabetically", mixing files and directories up. PEP8 separates standard and 3rd party includes and every sane file manager groups files and directories separately. Clang format doesn't. (Well, maybe Clang 13 will have that option, but what until then?!)
- Sometimes, adding or removing *a single character* causes an expression wrapped on multiple to get reformatted. How the hell are people supposed to look at diffs with noise like this?!
- Since there's no way to tell clang-format to format only changed or newly added code (and there's no way to tell it to "don't change formatting of such things" either), the only way to make it work without it adding noise to new commits is reformatting *the whole project* with that, thus losing *all* history (or, alternatively, [introduce custom tools](https://twitter.com/sylvestreledru/status/1068571441296220165) that deal with that change, making everyone's life even harder). **Hell no.**
