### ISSUE TITLE
How can I set texture data from PBO?

### ISSUE THREAD

**Issue by sleepyeye** [mosra/magnum#316]
Hello. I'm trying to reimplement my OpenGL based application by using Magnum.
I'm here to get some advice a functionality that I wanted to implement using Magnum.
UnfortunatelyI'm stucked due to my short understanding of Magnum.

What I want to do is, viewing some intermediate rendering result.
So I generated my data into PBO and fetch data into texture and then view it through by simply drawing textured quad.

Fetching data from PBO to texture,my original code looks like this.
```cpp
glBindTexture(GL_TEXTURE_2D, texture);
glBindBuffer(GL_PIXEL_UNPACK_BUFFER, pboid);
glTexImage2D(
     GL_TEXTURE_2D, 0, GL_RGBA32F, (GLsizei)width, (GLsizei)height,
      0, GL_RGBA, GL_FLOAT, (void *)0);
glBindBuffer(GL_PIXEL_UNPACK_BUFFER, 0);
glBindTexture(GL_TEXTURE_2D, 0);
```

But.... I have no good idea how to implement this simple functionality using Magnum.
```cpp
// Setup PBO
GL::Buffer pbo;
pbo.setTargetHint(Magnum::GL::Buffer::TargetHint::PixelUnpack);
pbo.setData({nullptr, imageSize.product() * sizeof(float) * 4},  // RGBA4 float
              Magnum::GL::BufferUsage::StreamRead);
...
// Setup Texture
GL::Texture2D texture;
texture.setWrapping(GL::SamplerWrapping::ClampToEdge)
        .setMagnificationFilter(GL::SamplerFilter::Linear)
        .setMinificationFilter(GL::SamplerFilter::Linear)
        .setStorage(0, GL::TextureFormat::RGBA32F, imageSize);
...
// Reneder loop
{
    // update pbo use my renderer

    ....

    // fetch data from PBO to texture
    ???
}
```

Implementing `// fetch data from PBO to texture` part is unclear to me.
I want some advice at this part.

The problem is `Texture` does not take `Buffer` for their `setSubImage` method. Instead it takes `BufferImage`. However `BufferImage` takes `Buffer` for setting up its data. Since it use `std::move`, I believe it take the ownership of pbo from me. But I don't want to loose my ownership of pbo for later usage. 
As summary, for implementing this, I need to make another `Buffer` and copy my pbo data into there. Then I need to construct temporal `BufferImage` by using my temopral `Buffer`. Then set my texture data using my temporal `BufferImage`.
But this is too much for me. I just want to explicitly copy my pbo data into texture storage. I believe there is some other easy way to do this.

Using `BufferTexture` could be one option for me. But I need to manage my buffer and texture separately. And I have to do two copy operation(pbo to temporal buffer, temporal buffer to texture storage) So it is quite cumbersome.

Is there any other way to directly feed data from `Buffer` to `Texture`?

Thanks!

**Comment by mosra** [comment]
Hi! 

you have basically two options -- the recommended one is storing your `pbo` already as a `BufferImage`. I made it this way because for a PBO `Buffer` instance you need to store some metadata alongisde anyway, so why not just have that all together in a `BufferImage`. It'll also do some things for you and check that the data has correct size for given dimensions. There's also [GL::BufferImage::buffer()](https://doc.magnum.graphics/magnum/classMagnum_1_1GL_1_1BufferImage.html#a98e51a5688751ca2a9b5548ee4df43e5) if you need to access the underlying buffer directly. So the above would look like this (disclaimer: there might be minor syntax errors):

```cpp
// Setup PBO
GL::BufferImage pbo{PixelFormat::RGBA32F, imageSize, 
    {nullptr, imageSize.product() * sizeof(float) * 4}, 
    GL::BufferUsage::StreamRead};

...
// Setup Texture
GL::Texture2D texture;
texture.setWrapping(GL::SamplerWrapping::ClampToEdge)
        .setMagnificationFilter(GL::SamplerFilter::Linear)
        .setMinificationFilter(GL::SamplerFilter::Linear)
        .setStorage(0, GL::TextureFormat::RGBA32F, pbo.size());
...
// Reneder loop
{
    // update pbo use my renderer

    ....

    // fetch data from PBO to texture
    texture.setSubImage(0, {}, pbo);
}
```

If the above is for some reason unacceptable (I'd like to know why, though), it's possible to create a non-owning copy of the buffer using [GL::Buffer::wrap()](https://doc.magnum.graphics/magnum/classMagnum_1_1GL_1_1Buffer.html#ad89e9924d9e3a96c9270713890a4a40b) and then use that to create a temporary `BufferImage` for texture upload, for example like below. But to me this approach feels unnecessarily verbose, especially since you need the image instance most of the time anyway.

```cpp
    ...

    // fetch data from PBO to texture
    GL::BufferImage image{PixelFormat::RGBA32F, imageSize, 
        Buffer::wrap(pbo.id(), GL::Buffer::TargetHint::PixelUnpack), 
        imageSize.product() * sizeof(float) * 4};
    texture.setSubImage(0, {}, image);
}
```

Hope this helps! :)

**Comment by sleepyeye** [comment]
Thank you for your fast feedback!
Excellent and clear answer for me.

I think I can use the first method. But I've got additional questions(sorry for bothering you)
1.  Can I set target in the buffer inside of `BufferImage`(in this case pbo variable)?

For example, I want to make sure that copy operation of the buffer use async pixel operation because of better performance.
So I want to give specific target.

```cpp
// Reneder loop
{
    // update pbo use my renderer

    ....

    // fetch data from PBO to texture
    pbo.buffer().setTargetHint(Magnum::GL::Buffer::TargetHint::PixelUnpack);  
    texture.setSubImage(0, {}, pbo);
}
```
Is this work? In other words, `setTargetHint(SomeTarget, ...)` is same as `glBindBuffer(SomeTarget, ...)`?


2. Can I change the target hint of the buffer?
This is extension of previous question.

For example
```cpp
// Reneder loop
{
    // update pbo use my renderer

    // Some operation
    pbo.buffer().setTargetHint(Magnum::GL::Buffer::TargetHint::ShaderStorage);


    ....

    // fetch data from PBO to texture
    pbo.buffer().setTargetHint(Magnum::GL::Buffer::TargetHint::PixelUnpack);
    texture.setSubImage(0, {}, pbo);
}
```

3. Is it okay to use raw (GL/CUDA operation outside of the Magnum)
Since my application use CUDA to write the contents of the PBO, sometimes I need to give id of buffer object to some function. And I need to register the id of PBO to CUDA. And some CUDA function and GL functions may be applied to the buffer through the registered id and its corresponding device pointer.
The only thing that I can say is that layout and format will not be change in the cuda function.


``` cpp
// PBO creation
GL::BufferImage pbo{PixelFormat::RGBA32F, imageSize, 
    {nullptr, imageSize.product() * sizeof(float) * 4}, 
    GL::BufferUsage::StreamRead};
...
// Register PBO ID to cuda buffer
device_ptr p_pboBuffer = REGISTER_TO_CUDA(pbo.buffer().id())


// Reneder loop
{
    // update pbo use my renderer
    cuda_function(p_pboBuffer, ...)

    // Some operation
    pbo.buffer().setTargetHint(Magnum::GL::Buffer::TargetHint::ShaderStorage);
    ....

    // fetch data from PBO to texture
    pbo.buffer().setTargetHint(Magnum::GL::Buffer::TargetHint::PixelUnpack);
    texture.setSubImage(0, {}, pbo);
}
```



I wonder there are potential problems.


Thank you!

**Comment by mosra** [comment]
1. yes, but the buffer is bound automatically to this target inside the `setSubImage()` function, so it's redundant
2. yes, you can, the target hint is basically used only for the `glBindBuffer()` command. But if you are, for example, going to bind the SSBO for use in a shader, you'll use [bind(Target, UnsignedInt)](https://doc.magnum.graphics/magnum/classMagnum_1_1GL_1_1Buffer.html#aaad3e6e809d309310eb2ef2cc21d149a), and there you tell the target explicitly anyway. Also note there it's `Target`, while here it's just TargetHint. For modern desktop GL the target hint mostly doesn't matter (that's also why it's named "hint"). For other systems however (WebGL, in particular), a buffer can be only bound to one target (so e.g. an index buffer has to stay index buffer, can't suddenly turn into a PBO).
3. yes, raw ID is completely fine, and the `GL::Buffer` is not much more than just a C++ wrapper around that. By design I'm not doing any opaque magic underneath, in order to make such interop (with CUDA, with OpenCL etc.) as easy as possible, without unnecessary surprises.

**Comment by jay3d** [comment]
Hi!

I have tried do the same with magnum but I always get a black window!

Is there anything wrong with my code?

magnum code:

Initialization:
`glContext.create();
    Platform::GLContext::makeCurrent( &glContext );

    GL::Renderer::enable( GL::Renderer::Feature::Blending );
    GL::Renderer::setBlendFunction( GL::Renderer::BlendFunction::One,
                                    GL::Renderer::BlendFunction::OneMinusSourceAlpha );

    appData = new AppData{};

    appData->GuiPbo.emplace_back( GL::BufferImage2D{ GL::PixelFormat::BGRA,
                                                     GL::PixelType::UnsignedByte,
                                                     { imageW, imageH },
                                                     { nullptr, static_cast< size_t >( dataSize ) },
                                                     GL::BufferUsage::StreamDraw } );
    appData->GuiPbo.emplace_back( GL::BufferImage2D{ GL::PixelFormat::BGRA,
                                                     GL::PixelType::UnsignedByte,
                                                     { imageW, imageH },
                                                     { nullptr, static_cast< size_t >( dataSize ) },
                                                     GL::BufferUsage::StreamDraw } );

    appData->GuiTexture = GL::Texture2D{};

    appData->GuiTexture.setMagnificationFilter( GL::SamplerFilter::Nearest )
        .setMinificationFilter( GL::SamplerFilter::Nearest )
        .setWrapping( GL::SamplerWrapping::ClampToEdge )
        .setStorage( 0, GL::TextureFormat::RGBA, appData->GuiPbo[ 0 ].size() );

    appData->QuadBuffer = GL::Buffer{};

    appData->QuadBuffer.setData( appData->QuadData );

    appData->QuadMesh.setPrimitive( GL::MeshPrimitive::Triangles )
        .setCount( 6 )
        .addVertexBuffer( appData->QuadBuffer, 0, QuadShader::Position{} );

    appData->QuadShader = QuadShader{};`

Render loop:
`static auto index     = 0;
    auto        nextIndex = 0; // pbo index used for next frame

    // "index" is used to copy pixels from a PBO to a texture object
    // "nextIndex" is used to update pixels in a PBO
#if 0
    // In single PBO mode, the index and nextIndex are set to 0
    index = nextIndex = 0;
#else
    // In dual PBO mode, increment current index first then get the next index
    index     = ( index + 1 ) % 2;
    nextIndex = ( index + 1 ) % 2;
#endif

    GL::defaultFramebuffer.setViewport( { { 0, 0 }, { w, h } } );
    GL::defaultFramebuffer.clear( GL::FramebufferClear::Color );

    appData->GuiTexture.setSubImage( 0, {}, appData->GuiPbo[ index ] );

    appData->GuiPbo[ nextIndex ].buffer().setData( { nullptr, static_cast< size_t >( dataSize ) },
                                                   GL::BufferUsage::StreamDraw );

    const auto ptr = appData->GuiPbo[ nextIndex ].buffer().map( GL::Buffer::MapAccess::WriteOnly );

    CORRADE_INTERNAL_ASSERT( ptr );

    BLImage img( 480, 480, BL_FORMAT_PRGB32 );

    BLContext ctx( img );

    ctx.setCompOp( BL_COMP_OP_SRC_COPY );
    ctx.clearAll();

    // First shape filled by a radial gradient.
    BLGradient radial( BLRadialGradientValues( 180, 180, 180, 180, 180 ) );
    radial.addStop( 0.0, BLRgba32( 0xFFFFFFFF ) );
    radial.addStop( 1.0, BLRgba32( 0xFFFF6F3F ) );

    ctx.setCompOp( BL_COMP_OP_SRC_OVER );
    ctx.setFillStyle( radial );
    ctx.fillCircle( 180, 180, 160 );

    // Second shape filled by a linear gradient.
    BLGradient linear( BLLinearGradientValues( 195, 195, 470, 470 ) );
    linear.addStop( 0.0, BLRgba32( 0xFFFFFFFF ) );
    linear.addStop( 1.0, BLRgba32( 0xFF3F9FFF ) );

    ctx.setCompOp( BL_COMP_OP_DIFFERENCE );
    ctx.setFillStyle( linear );
    ctx.fillRoundRect( 195, 195, 270, 270, 25 );

    ctx.end();

    BLImage gfx;

    gfx.createFromData( imageW, imageH, BL_FORMAT_PRGB32, ptr, imageW * 4 );

    BLContext ctx2( gfx );

    ctx2.setCompOp( BL_COMP_OP_SRC_COPY );
    ctx2.clearAll();
    ctx2.setFillStyle( BLRgba32( 0xFFFFFFFF ) );
    ctx2.fillAll();

    ctx2.setGlobalAlpha( 0.5 );

    ctx2.blitImage( BLPoint{}, img );

    ctx2.setGlobalAlpha( 1.0 );

    ctx2.setFillStyle( BLRgba32( 0xFFFFFFFF ) );
    ctx2.fillUtf8Text( BLPoint( 60, 80 ), *font, "A test bed for the creation of a future GUI" );

    ctx2.end();

    CORRADE_INTERNAL_ASSERT_OUTPUT( appData->GuiPbo[ nextIndex ].buffer().unmap() );

    appData->QuadShader.SetAspectRatio( { float( w ) / float( imageW ), float( h ) / float( imageH ) } )
        .BindTexture( appData->GuiTexture );

    appData->QuadMesh.draw( appData->QuadShader );`

Raw OpenGL code:

Init:
`glEnable( GL_BLEND );

    glBlendFunc( GL_ONE, GL_ONE_MINUS_SRC_ALPHA );

    glGenTextures( 1, &renderedTextureId );

    glBindTexture( GL_TEXTURE_2D, renderedTextureId );

    glTexParameteri( GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_NEAREST );
    glTexParameteri( GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_NEAREST );
    glTexParameteri( GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE );
    glTexParameteri( GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE );

    glTexImage2D( GL_TEXTURE_2D, 0, GL_RGBA, imageW, imageH, 0, PIXEL_FORMAT, GL_UNSIGNED_BYTE, nullptr );

    glBindTexture( GL_TEXTURE_2D, 0 );

    glGenBuffers( 2, pboIds );
    glBindBuffer( GL_PIXEL_UNPACK_BUFFER, pboIds[ 0 ] );
    glBufferData( GL_PIXEL_UNPACK_BUFFER, dataSize, nullptr, GL_STREAM_DRAW );
    glBindBuffer( GL_PIXEL_UNPACK_BUFFER, pboIds[ 1 ] );
    glBufferData( GL_PIXEL_UNPACK_BUFFER, dataSize, nullptr, GL_STREAM_DRAW );
    glBindBuffer( GL_PIXEL_UNPACK_BUFFER, 0 );

glGenBuffers( 1, &quadVertexBufferId );
    glBindBuffer( GL_ARRAY_BUFFER, quadVertexBufferId );
    glBufferData( GL_ARRAY_BUFFER, sizeof( quadVertexBufferData ), quadVertexBufferData, GL_STATIC_DRAW );

    const auto& quadVertexShaderId = glCreateShader( GL_VERTEX_SHADER );

    glShaderSource( quadVertexShaderId, 1, &quadVertexShader, nullptr );
    glCompileShader( quadVertexShaderId );

    const auto& quadFragmentShaderId = glCreateShader( GL_FRAGMENT_SHADER );

    glShaderSource( quadFragmentShaderId, 1, &quadFragmentShader, nullptr );
    glCompileShader( quadFragmentShaderId );

    quadShaderProgramId = glCreateProgram();

    glAttachShader( quadShaderProgramId, quadVertexShaderId );
    glAttachShader( quadShaderProgramId, quadFragmentShaderId );
    glLinkProgram( quadShaderProgramId );

    textureId     = glGetUniformLocation( quadShaderProgramId, "renderedTexture" );
    aspectRatioId = glGetUniformLocation( quadShaderProgramId, "aspectRatio" );`

Render:
`// start to copy from PBO to texture object

    // bind the texture and PBO
    glBindTexture( GL_TEXTURE_2D, renderedTextureId );
    glBindBuffer( GL_PIXEL_UNPACK_BUFFER, pboIds[ index ] );

    // copy pixels from PBO to texture object
    // Use offset instead of pointer.
    glTexSubImage2D( GL_TEXTURE_2D, 0, 0, 0, imageW, imageH, PIXEL_FORMAT, GL_UNSIGNED_BYTE, nullptr );

    // start to modify pixel values

    // bind PBO to update pixel values
    glBindBuffer( GL_PIXEL_UNPACK_BUFFER, pboIds[ nextIndex ] );

    // map the buffer object into client's memory
    // Note that glMapBuffer() causes sync issue.
    // If GPU is working with this buffer, glMapBuffer() will wait(stall)
    // for GPU to finish its job. To avoid waiting (stall), you can call
    // first glBufferData() with NULL pointer before glMapBuffer().
    // If you do that, the previous data in PBO will be discarded and
    // glMapBuffer() returns a new allocated pointer immediately
    // even if GPU is still working with the previous data.
    glBufferData( GL_PIXEL_UNPACK_BUFFER, dataSize, nullptr, GL_STREAM_DRAW );

    const auto ptr = static_cast< GLubyte* >( glMapBuffer( GL_PIXEL_UNPACK_BUFFER, GL_WRITE_ONLY ) );

    if ( ptr )
    {
        // BLImage img;
        // img.createFromData( imageW, imageH, BL_FORMAT_PRGB32, ptr, imageW * 4 );

        BLImage img( 480, 480, BL_FORMAT_PRGB32 );

        BLContext ctx( img );

        ctx.setCompOp( BL_COMP_OP_SRC_COPY );
        // ctx.fillAll();
        ctx.clearAll();

        // First shape filled by a radial gradient.
        BLGradient radial( BLRadialGradientValues( 180, 180, 180, 180, 180 ) );
        radial.addStop( 0.0, BLRgba32( 0xFFFFFFFF ) );
        radial.addStop( 1.0, BLRgba32( 0xFFFF6F3F ) );

        ctx.setCompOp( BL_COMP_OP_SRC_OVER );
        ctx.setFillStyle( radial );
        ctx.fillCircle( 180, 180, 160 );

        // Second shape filled by a linear gradient.
        BLGradient linear( BLLinearGradientValues( 195, 195, 470, 470 ) );
        linear.addStop( 0.0, BLRgba32( 0xFFFFFFFF ) );
        linear.addStop( 1.0, BLRgba32( 0xFF3F9FFF ) );

        ctx.setCompOp( BL_COMP_OP_DIFFERENCE );
        ctx.setFillStyle( linear );
        ctx.fillRoundRect( 195, 195, 270, 270, 25 );

        ctx.end();

        BLImage gfx;

        gfx.createFromData( imageW, imageH, BL_FORMAT_PRGB32, ptr, imageW * 4 );

        BLContext ctx2( gfx );

        ctx2.setCompOp( BL_COMP_OP_SRC_COPY );
        ctx2.clearAll();

        ctx2.setGlobalAlpha( 0.5 );

        ctx2.blitImage( BLPoint{}, img );

        ctx2.setGlobalAlpha( 1.0 );

        ctx2.setFillStyle( BLRgba32( 0xFFFFFFFF ) );
        ctx2.fillUtf8Text( BLPoint( 60, 80 ), *font, "A test bed for the creation of a future GUI" );

        ctx2.end();

        glUnmapBuffer( GL_PIXEL_UNPACK_BUFFER ); // release pointer to mapping buffer
    }

    // it is good idea to release PBOs with ID 0 after use.
    // Once bound with 0, all pixel operations behave normal ways.
    glBindBuffer( GL_PIXEL_UNPACK_BUFFER, 0 );

    // glBindFramebuffer( GL_FRAMEBUFFER, 0 );

    // glViewport( 0, 0, w, h );

    // glClear( GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT );

    glUseProgram( quadShaderProgramId );

    glActiveTexture( GL_TEXTURE0 );
    // glBindTexture( GL_TEXTURE_2D, renderedTextureId );

    glUniform2f( aspectRatioId, float( w ) / float( imageW ), float( h ) / float( imageH ) );
    glUniform1i( textureId, 0 );

    glEnableVertexAttribArray( 0 );

    glBindBuffer( GL_ARRAY_BUFFER, quadVertexBufferId );
    glVertexAttribPointer( 0, 3, GL_FLOAT, GL_FALSE, 0, nullptr );

    glDrawArrays( GL_TRIANGLES, 0, 6 );

    glDisableVertexAttribArray( 0 );

    glBindTexture( GL_TEXTURE_2D, 0 );`

Thanks!

**Comment by mosra** [comment]
@jay3d can't see anything wrong by just looking at the code. Some ideas:

- you seem to be using custom GL context creation, is there a default framebuffer or are you supposed to draw into some provided framebuffer object (which is the case with Qt, for example)?
- if you set a custom clear color, can you see at least that when you do a framebuffer clear alone?
- any GL errors reported?
- what does [debug output](https://doc.magnum.graphics/magnum/classMagnum_1_1GL_1_1DebugOutput.html#GL-Magnum-DebugOutput-usage) say?

**Comment by jay3d** [comment]
I'm using SDL separately with special hacks to let graphics running during dragging and resizing the window on Windows.
I'm just drawing to a texture and mapping that texture into a quad geometry.
Before that I tried the triangle example to make sure switching contexts is working.
I haven't enabled the debug output, let me give it a try.

It's strange because the raw GL code works perfectly.

**Comment by mosra** [comment]
> switching contexts

Hmm... Is Blend2D (or any other lib, or other code) calling into GL as well? (I checked Blend2D but that one seems to be software-only.) Because that could be the issue. Magnum has an internal state tracker to avoid redundant `glBind*()` calls and such and if you mix it up with other GL code, it will get confused.

That's not a showstopper tho, you just need to ensure it gets to know when the state tracker assumptions need to be updated. [Docs here.](https://doc.magnum.graphics/magnum/opengl-wrapping.html#opengl-state-tracking)

**Comment by jay3d** [comment]
@mosra 

Blend2D is a software only graphics library, it only uses the mapped buffer directly without copying and it's not involved with any gl* calls

I can send you the whole test project to check, as I have debugged every raw gl call issued by magnum and it seems to be fine and matches the vanilla code closely.

**Comment by jay3d** [comment]
@mosra 

Ok I got it working with setImage at texture initialization instead of setStorage.
If the texture initialized with setStorage you'll get a black texture.

```cpp
    appData->GuiTexture.setMagnificationFilter( GL::SamplerFilter::Nearest )
        .setMinificationFilter( GL::SamplerFilter::Nearest )
        .setWrapping( GL::SamplerWrapping::ClampToEdge )
        //.setStorage( 0, GL::TextureFormat::RGBA, appData->GuiPbo[ 0 ].size() ) // Black texture
        //.setImage( 0, GL::TextureFormat::RGBA, ImageView2D{ PixelFormat::RGBA8Unorm, appData->GuiPbo[ 0 ].size() } ) // Correct texture
        .setImage( 0, GL::TextureFormat::RGBA, appData->GuiPbo[ 0 ] ); // Correct texture
```

Which I found it strange.

Another interesting thing is that ImageView2D will actually create a PBO buffer internally, I thought maybe using that abstraction instead of dealing with creating BufferImages? Will it harm the performance? Because I'm not sure if ImageView2D will map the buffer to update internally like I did in the code.
