### ISSUE TITLE
Video medias in magnum

### ISSUE THREAD

**Issue by gdeverlant** [mosra/magnum#327]
Greetings to all!

I wanted to know if there is a way to render ffmpeg decoded frame inside Magnum or if it is possible to display video file like in a browser simply.

Thanx

**Comment by mosra** [comment]
Hi!

Yes, this is possible if you write the decoding on your own and then pass the decoded frame data via an [ImageView](https://doc.magnum.graphics/magnum/classMagnum_1_1ImageView.html) to some texture. More integrated support for en/decoding video with ffmpeg is planned (audio as well, see https://github.com/mosra/magnum-plugins/pull/55), but at the moment nothing prevents you from doing the decoding directly. 

IIRC there are also some OpenGL extensions and ffmpeg APIs that should allow you to do the decoding on the GPU and pass the decoded frames directly, without extra copies.

**Comment by gdeverlant** [comment]
Are there any exemples I can inspire myself from?
I never used OpenGL or anything raw graphic oriented so
I'm totally a noob in this area, but I'm not a noob programmer.

**Comment by mosra** [comment]
Ah okay, sorry for assuming you already know all this :) Hopefully this will give you something to start from:

I don't have any ready-made ffmpeg code for decoding frame data, unfortunately. When I was learning it myself (for the audio) I studied various code snippets scattered on the internet (but be aware that these are of varying quality and some of them make use of long-deprecated features). Then there's an [example section](https://ffmpeg.org/doxygen/4.0/examples.html) in the ffmpeg documentation including a plain C video decoder, so maybe that helps? :)

Once you get the raw frame data, pass them to the `ImageView`, specify the pixel format (you'll need `RGB8Unorm` or `RGBA8Unorm`, *not* YUV, check the ffmpeg examples again for a way how to convert YUV to RGB) and dimensions and then upload the image to a texture (similarly as done in the [Textured triangle](https://doc.magnum.graphics/magnum/examples-textured-triangle.html) example). There's also a ready-made [Primitives::squareSolid()](https://doc.magnum.graphics/magnum/namespaceMagnum_1_1Primitives.html#a2b9e6b87efe8f6eb09178dbdfdbc00a6) that you could apply the texture to (using, transforming and rendering the primitives is described in the [Primitives](https://doc.magnum.graphics/magnum/examples-primitives.html) example).

**Comment by gdeverlant** [comment]
Ok that is a better explanation but I still need to understand all of the technical term.

Maybe the results of my searches can be of any help to you. I will list all the great resources I found
concerning FFMPEG and let know if you have the same.

https://github.com/mpenkov/ffmpeg-tutorial
https://github.com/abdullahfarwees/screen-recorder-ffmpeg-cpp
http://dranger.com/ffmpeg/tutorial04.html
https://github.com/andreanobile/opencv_ffmpeg_streaming
http://ffmpeg.org/doxygen/trunk/doc_2examples_2decoding_encoding_8c-example.html
https://github.com/leandromoreira/ffmpeg-libav-tutorial#intro

**Comment by mosra** [comment]
> Maybe the results of my searches can be of any help to you.

Not sure what's the question here? :) I *do* know my way around ffmpeg, I just don't have any example code with ffmpeg+magnum for you. From the links, I think [this](https://ffmpeg.org/doxygen/4.0/decode_video_8c-example.html) is the one you're looking for.

**Comment by gdeverlant** [comment]
I have found an App which makes use of ImGui and FFMPEG pushing videos in OpenGL with the source code. I'm trying to gather the whole information that I need before starting my project.

The part I wanted to understand is the ImGui and FFMPEG but it was not easy to find something uncomplicated until today. Now the part with ImGui+FFMPEG is covered since Magnum is also integrating ImGui. What is remaining now is to create a basic prototype With Magnum, Imgui and take the part from the other project and try to push the FFMPEG in Magnum,ImGui.

I hope this will not be a pain in the butt.

**Comment by mosra** [comment]
Anything left to be done here? Otherwise I'd suggest to close this issue.

For general questions, discussion and asking for help please use the [Gitter channel](https://gitter.im/mosra/magnum) instead (you can log in with your GitHub account), issues are more suited for feature requests or bug reports -- and I'm trying to be nice to the almost 200 people watching the repository, since each of them gets an e-mail notification for every comment ;)

**Comment by gdeverlant** [comment]
Yes you can close this ticket. Let us know when video support is on its way.
