### ISSUE TITLE
ImGuiIntegration::image issue

### ISSUE THREAD

**Issue by Tryum** [mosra/magnum#328]
Hi,

I have some issues with ImGuiIntegration::image, I think there's some conflicts with internal imgui textures used for rendering :
![ImGuiIntegration_image](https://user-images.githubusercontent.com/161625/54719518-69c3eb80-4b5d-11e9-83f6-b5152d74e444.JPG)

I'm displaying 3 textures, the first 2 are always the font texture. If I call an internal reload (where I recreate the textures), I get the correct textures displayed.

I tried with magnum head ;)

**Comment by mosra** [comment]
I had a suspicion on what it could be, but looked into the code and everything looked alright. The `image()` and `imageButton()` functionality is used quite heavily by a few people (running on Windows + NV/Intel but also other systems) and I don't remember any issues reported with these.

For now I'm suspecting it's something similar to #321, if there's some problem with the texture binding then it could be causing both the flicker and this.

**Comment by Tryum** [comment]
With `--magnum-gpu-validation on` I have this error : 
```
Debug output: high severity API error (1282): GL_INVALID_OPERATION error generated. <texture> is not a valid texture name.
```
which disappear once I do my internal reload is called and I have the 3 textures rendered correctly.

**Comment by mosra** [comment]
Thanks! That says something.

The code is keeping a pointer to the `GL::Texture` object, so I suspect your instance of the texture had been moved somewhere else, so the pointer is now garbage and thus `<texture>` is 76546543 or some other random memory instead of a valid texture ID?

Can you `Debug{} << texture.id();` right before you call the `ImGuiIntegration::image()`?

**Comment by Tryum** [comment]
That's it, thanks,
Now I need to figure out what's going on... (and I now know that texture ID 0 is Imgui's fonts ;) ).

**Comment by mosra** [comment]
ID 0 is no texture, though... as far as I remember how NV assigns GL object IDs, if ImGui is instantiated as the first thing in the app, the ID should be 1 or 2 or similarly low (but non-zero) number.

The textures are bound to texture unit 0, but that's a different thing.

**Comment by Tryum** [comment]
Damn I feel dumb ... I was storing the textures in a vector, and passing pointers around. On the first load the growing vector would move data, resulting in only the last pointer to be valid.... night coding at its best :|

**Comment by mosra** [comment]
Haha :) Good thing that the debug output helped discover this. 

I thought about storing a "shallow copy" of the texture instead of a pointer, but that wouldn't help in this case anyway, since when you're calling `image()` the texture reference is already dangling.
