### ISSUE TITLE
Wild card expression for importer and Reading texture data from importer class 

### ISSUE THREAD

**Issue by sleepyeye** [mosra/magnum#330]
Hello,
I have two questions related to importers.
I tried to search documentations and examples but failed to find one that I need.

1. Does `Trade::AbstractImporter` support wild card expression?

For instance, I have a folder which has quite a lot of obj files.
Currently I'm reading list of filenames using filesystem library then put the path of obj file to `openFile` method one by one.

If `openFile` method in `AbstractImporter` supports wild card expression, then it would be handy.
 

2.  Does `Trade::AssimpImporter` supports automatic reading of mtl file? If it is, how can I access to raw texture data of obj file?

Currently I am using Assimp importer to load my obj file.
It is single obj file with single mtl file and there are multiple textures for each part in obj file.
```
my-data.obj  // consist of part 1, part 2 ....
my-data.mtl // contains all parameters for each part of obj file
my-data-texture-01.jpg // texture for part 1
my-data-texture-02.jpg // texture for part 2
...
```

(I'm just assuming that the importer read all mtl and jpg files when it load obj file. But it is still unclear to me.)

Reading obj file itself works perfect. I could obtain position, normal, texture and indices for each part of mesh in obj file.
But the problem is I don't know how to access raw texture data for each obj file. For example, when I read the part 1 in my obj, then I have `Trade::MeshData3D` of part 1 mesh. That means that some how I should bind it to `my-data-texture-01.jpg`. To do that I need to access the raw texture data of it. How can I do that with the class?

If the `Trade::AssimpImporter` does not support automatic reading of mtl files, then I should some how bind the mesh data and the texture data that I read. 
Is there any way to do it with magnum?

Thank you!

**Comment by mosra** [comment]
Hello,

1. This is not possible to do in a general way. Imagine two OBJ files (or glTF files) having a mesh or a material with the same name, but different contents. The importer would then need to merge them together *somehow* and then you wouldn't be able to distinguish what file the name belongs to. And this would need to be done for all formats, not just OBJ, ensuring all material, animation, texture references are still correct etc. It would be a lot of work on the library side for questionable benefits on the application side -- what's wrong with doing `openFile()` in a loop? If that's really a problem, it's always possible to combine multiple OBJ files into one and then open it just once. But that has to be done on the editor / modeller side, it's out of scope of the importer APIs in Magnum.
2. Generally, the connection between a mesh and a material is done via the `object*()` functions -- you get a `Trade::ObjectData3D` out of it and it says what mesh the object has and also what material (and thus also what textures and what images). Have a look at the [Viewer example](https://doc.magnum.graphics/magnum/examples-viewer.html) to see how the connection between objects, meshes, materials and textures is usually done. That said, I'm not 100% sure how Assimp does it for OBJ, but for other formats imported by Assimp (such as glTF, `*.blend` or COLLADA) this has been working quite well.

Hope this helps! :)

**Comment by sleepyeye** [comment]
@mosra 
Sorry for late feedback.

I resolve the problem with`Trade::ObjectData3D`. The viewer example helped me a lot.
`AssimpImporter` worked just as other importer.

Thanks for your clear answer!
