### ISSUE TITLE
OpenCV image to GL::Texture2D

### ISSUE THREAD

**Issue by faisalkalim** [mosra/magnum#337]
Is there any way of converting CV::Mat to GL::Texture2D? 
In my application, I would like to display live video captured through CV::VideoCapture and display it with some augmentation.

**Comment by mosra** [comment]
Hi!

(I have very little experience with OpenCV, but) reading the docs, `CV::Mat` seems to be tightly packed image data residing in CPU memory, right? Then you should be able to create an [ImageView2D](https://doc.magnum.graphics/magnum/classMagnum_1_1ImageView.html) pointing at the underlying data with corresponding format and size (and, maybe, some row length / alignment specifications passed through [PixelStorage](https://doc.magnum.graphics/magnum/classMagnum_1_1PixelStorage.html) in case `CV::Mat` *isn't* tightly packed). Then you can upload the image view using [GL::Texture2D::setSubImage()](https://doc.magnum.graphics/magnum/classMagnum_1_1GL_1_1Texture.html#ad3bb523a881dd4fac66c535dd069dbb4).

However, if it's a captured video, a more performant approach would be to *somehow* make CV decode it directly on the GPU, without going to RAM (and then back to the GPU memory again when you upload the texture). But I don't have enough experience with OpenCV to know if that's possible.

**Comment by faisalkalim** [comment]
Thank you.

**Comment by mosra** [comment]
Nothing left to do here I think, closing :)

**Comment by Squareys** [comment]
[We](vhiterabbit.com) did some stuff with [ARuco](https://www.uco.es/investiga/grupos/ava/node/26) and magnum once. That was OpenCV ~2.4.9, though, so might not be useful:

~~~cpp
Mat frame;
/* Get a new frame from camera */
_capture >> frame; 

/* Run ARuco on that frame, as usual (omitted) */
detectMarkers(frame);

const cv::Size s = frame.size();
const Vector2i size{s.width, s.height};
ImageView2D img{PixelFormat::RGBA8Unorm, size,
    Corrade::Containers::ArrayView<const void>(frame.ptr(), size.product()*4)};

/* Move data to magnum */
_texture.setSubImage(0, {}, img);

/* Draw Fullscreen Triangle with the frame on it */
#include <Magnum/MeshTools/FullScreenTriangle.h>

GL::Mesh _fstMesh;
_fstMesh.setCount(3);

FullScreenTriangleShader _fstShader;
_fstShader.bindTexture(_texture);

_fstMesh.draw(_fstShader);
~~~

This will obviously not compile, but should make the implementation pretty straight forward.
