### ISSUE TITLE
Add functions to map a value from one range to another in Magnum:Math

### ISSUE THREAD

**Issue by roig** [mosra/magnum#341]
I think it would be useful to have those functions in Magnum::Math

something like :
http://api.unrealengine.com/INT/BlueprintAPI/Math/Float/MapRangeClamped/

**Comment by mosra** [comment]
You mean [Math::lerpInverted()](https://doc.magnum.graphics/magnum/namespaceMagnum_1_1Math.html#a8f151ca0349b31e91882117ee43764dd) combined with [Math::lerp()](https://doc.magnum.graphics/magnum/namespaceMagnum_1_1Math.html#a8d0cf4b89dfd92edf6cff3954adf7cf7)? :)

```cpp
Float a = Math::lerp(5.0, 15.0, Math::lerpInverted(-1.0, 1.0, value));
```

maps `value` from a range [ -1; +1 ] to a range [ 5; 15 ]. Works for vectors (and vector ranges) too.

**Comment by roig** [comment]
Yes, that's it!

**Comment by mosra** [comment]
A mention of this is in the docs of [Math::lerpInverted()](https://doc.magnum.graphics/magnum/namespaceMagnum_1_1Math.html#a586189ebf6a1c2e3fea58fe6b12147d6) since 2a9f4a1fed4a70fce486a0cc2d6ee42346a35ab3. Closing as resolved :)
