### ISSUE TITLE
Use threejs in magnum web

### ISSUE THREAD

**Issue by liweimax** [mosra/magnum#351]
Is it possible to plugin threejs to magnum in web?

**Comment by Squareys** [comment]
You can use Magnum in the Web without three.js :) That is done by compiling it to WebAssembly and making use of WebGL (which three.js also uses).

Here's a link to the documentation that might get you started: https://doc.magnum.graphics/magnum/platforms-html5.html


In case you want to use three.js inside magnum, you can check [emscripten's APIs to connect C++ with JS](https://emscripten.org/docs/porting/connecting_cpp_and_javascript/index.html).

Hope some of this helps.

**Comment by liweimax** [comment]
I mean is it possbile to share the webgl context between Magnum and threejs?  Then we can draw threejs object in Magnum.

**Comment by Squareys** [comment]
Yes, that should be possible :)

**Comment by mosra** [comment]
@liweimax anything else left to be done here or can I close this issue? :) Unfortunately I've never used three.js myself, so I'm afraid I can't help further.

One thing worth mentioning when combining GL rendering from multiple libraries -- Magnum needs to be aware of that and [told to reset its state tracker at appropriate times](https://doc.magnum.graphics/magnum/opengl-wrapping.html#opengl-state-tracking).

**Comment by mosra** [comment]
Closing as resolved -- @liweimax, comment here in case you have further questions ;)
