### ISSUE TITLE
Mesh::addVertexBufferInternal conversion from 'GLintptr' to 'GLsizei'

### ISSUE THREAD

**Issue by Adam-Black-Bose** [mosra/magnum#352]
Regarding void Mesh::addVertexBufferInternal(Buffer&, GLsizei, GLuint, GLintptr) in GL/Mesh.h

This function is generating W3 warnings for converting int64 to int32.

Callers are specifying parameters in {buffer, offset, stride, divisor} order, which is the cause of the error.

Thus conclude that the correct declaration should be void addVertexBufferInternal(Buffer&, GLintptr, GLsizei, GLuint) {}

**Comment by mosra** [comment]
Yes, you're right! Thanks a lot for the detailed description, probably slipped through when refactoring the argument order some years back :) Fixed in 51cd4b3dd0a27948ea49e770613980a5d3821608.
