### ISSUE TITLE
Vertical Text

### ISSUE THREAD

**Issue by hsdk123** [mosra/magnum#356]
Hi, as of now, the current implementation of texts in Magnum seem to focus only on horizontal rendering of texts. Languages such as Japanese, Korean, and Chinese for example have vertical advance, bearing, etc. for texts stored in the font file, which can be extracted by ex. Freetype.

It would be great if we could get this information through Magnum - would open up a whole new set of text expressions. 

This is even more critical for languages such as Japanese, where vertical text rendering is the de facto norm in books, magazines, manga, etc.

**Comment by mosra** [comment]
Ah, yes of course -- please see #143, it's all listed there. I have successfully done this in another project (HarfBuzz helping me get 90% of the way), but so far other things had a priority so I didn't manage to expose all that in Magnum yet.

Closing in favor of the above-mentioned issue, hope that's okay ;)
