### ISSUE TITLE
std::vector to Corrade::Containers conversion broken on WIndows

### ISSUE THREAD

**Issue by Consti10** [mosra/magnum#366]
Hello,
I have included `Corrade/Containers/ArrayViewStl.h,` but the automatic conversion of std::vector throws a run time error when passing it to the `GL::Buffer setData()` function.
Here is what compiles & runs without problems (as a workaround):
`bufferV.setData(Corrade::Containers::arrayView(vertexData.data(), vertexData.size()));`
But replacing the line with the 'better' code:
`bufferV.setData(vertexData);`
Throws the following run time error:

`Program: ...cuments\magnum_vector_field\build\src\Debug\MyApplication.exe
File: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\include\vector
Line: 1475

Expression: vector subscript out of range

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts.`

The function where the error arises:
`void MyApplication::updateBuffers() {
	const float lifeTimeDelta = 0.000001f;

	//Vector2 vertexData[MaxParticles];
	//Containers::ArrayView<Vector3> vertexData;
	std::vector<Vector2> vertexData{};

	for (int i = 0; i < MaxParticles; i++) {
		Particle& p = ParticlesContainer[i]; // shortcut
		if (p.life > 0.0f) {
			// Decrease life
			p.life -= lifeTimeDelta;
			if (p.life > 0.0f) {
				//do nothing, just upload data
				vertexData.push_back(p.pos);
			}
		}
	}
	//bufferV.setData(Corrade::Containers::arrayView(vertexData.data(), vertexData.size()));
	bufferV.setData(vertexData);
	_mesh.setCount(vertexData.size());
}`

**Comment by Squareys** [comment]
I think this is a duplicate of https://github.com/mosra/corrade/issues/75
It was fixed 11 hours ago, can you try updating corrade?

**Comment by mosra** [comment]
Nice, two race conditions at the same time -- just when I wanted to post exactly the same comment about this being pushed to master today early morning :laughing:

**Comment by Consti10** [comment]
Haha, good to hear it's already fixed.
I'l let you know once I updated corrade.

**Comment by Consti10** [comment]
Altest version of --head via vcpkg (re-install)
Confirmed fix, works again.
