### ISSUE TITLE
Update packages installed via vcpkg from head

### ISSUE THREAD

**Issue by Consti10** [mosra/magnum#367]
Not really a magnum problem, but related:
Assuming I have installed magnum via vcpkg from head ,example command:
`vcpkg install magnum[sdl2application,glfwapplication] --head --triplet x64-windows`

how do I update ? running
`.\vcpkg upgrade --no-dry-run`

installed the latest release of magnum instead.

**Comment by Consti10** [comment]
The only way I know is to uninstall & then reinstall everything.

**Comment by Consti10** [comment]
https://github.com/microsoft/vcpkg/issues/7813

**Comment by Squareys** [comment]
Updating works by removing and installing again. (Yes, not really intuitive)

```
vcpkg remove magnum --recurse
```

**Comment by mosra** [comment]
In 1724f94445590e101bb0338f8accab00aaaedb4d I [extended the info](https://doc.magnum.graphics/magnum/building.html#building-packages-vcpkg) about `--head` packages, hopefully that's enough:

![image](https://user-images.githubusercontent.com/344828/63754000-6a06a680-c8b4-11e9-9041-9c7635066353.png)
