### ISSUE TITLE
how to  set  sdl2 path

### ISSUE THREAD

**Issue by chuyuwei** [mosra/magnum#378]
I put SDL2.0 in C:\Users\chuyuwei\Desktop\duallerp\magnum-bootstrap\SDL2-2.0.10. So how should I write in  cmake 
it always shows 
Could NOT find SDL2 (missing: SDL2_LIBRARY) 
CMake Error at magnum/src/Magnum/Platform/CMakeLists.txt:289 (message):
  SDL2 library, required by Sdl2Application, was not found.  Set
  WITH_SDL2APPLICATION to OFF to skip building it.

it is  vs 2017

**Comment by mosra** [comment]
If that directory contains prebuilt SDL binaries (it's the `SDL2-devel-2.0.10-VC.zip` file), it should be enough to make the root CMakeLists look like this:

```cmake
cmake_minimum_required(VERSION 3.1)
project(MyApplication)

set(CMAKE_MODULE_PATH "${PROJECT_SOURCE_DIR}/modules/" ${CMAKE_MODULE_PATH})

# Add Corrade and Magnum as subprojects, add prebuilt SDL and enable Sdl2Application
list(APPEND CMAKE_PREFIX_PATH "${PROJECT_SOURCE_DIR}/SDL2-2.0.10")
set(WITH_SDL2APPLICATION ON CACHE BOOL "" FORCE)
add_subdirectory(corrade)
add_subdirectory(magnum)

add_subdirectory(src)
```

This seems to be the easiest, I'll mention it in the Getting Started guide.

**Comment by mosra** [comment]
[Getting Started Guide](https://doc.magnum.graphics/magnum/getting-started.html) updated in 6b64ee6240872c12048af22b7c712aa9dd56b994 and verified to be working. It should be now much easier to follow, with less pain points for Windows users.
