### ISSUE TITLE
Run Magnum on different runtime

### ISSUE THREAD

**Issue by janbajana** [mosra/magnum#385]
Magnum has runtime implementation in Magnum::Application.
We have our own runtime implementation for Android using EGL, GLES3, and directly Qualcomm services, DRM mainline graphics stack.
We also generate our glGenFramebuffers. I know Magnum has this GL/DefaultFramebuffer.
I am still not so familiar with Magnum API.

I want to use Magnum as rendering middleware on the application level with our runtime.
I can call direct GL wrapper like:
`GL::Renderer::setClearColor({0.5, 0, 0, 1});`

The app crashes if I try to call Mesh, Shader and other:
`GL::defaultFramebuffer.clear(GL::FramebufferClear::Color);`
`GL::Mesh _mesh;`
`Shaders::VertexColor2D _shader;`

There is nothing in the logs.

I know it is difficult to say without the code and logs. 
But are there any ideas what should I set up for Magnum? Should I somehow pass our framebuffers or rendering textures to Magnum?

This was just one day afford, I will try more tomorrow to get some logs.
Thank you for your thoughts.

**Comment by mosra** [comment]
Hi!

The Application classes are provided for convenience of 90% of users, but are completely optional. Magnum can work without them, but then you're responsible for creating a GL context on your own and then instantiating `Platform::GLContext` and keeping it alive as long as you want to call Magnum GL APIs. 

The crashes you're getting are because the `GLContext` is querying GL function pointers, setting up a state tracker etc., and if you don't instantiate it, `glGenVertexArrays()` and such are `nullptr` and thus the app crashes (or aborts, when it tries to access a nonexistent `GLContext` instance).

Docs to help you with the custom setup: https://doc.magnum.graphics/magnum/platform.html#platform-custom

Let me know if you need anything else.

**Comment by janbajana** [comment]
Super thank you for the update. Now it looks working.
Following QT example:
https://github.com/mosra/magnum-bootstrap/blob/base-qt/src/MyApplication.cpp

Is it recommended to call `resetState`?
`GL::Context::current().resetState(GL::Context::State::ExitExternal);`

We are binding our frame buffers with stereoscopy setup so I do not do any calls to `GL::defaultFramebuffer`.
So my render call at the end looks like this but I am not sure if `resetState` is necessary here:

```
void CubeDelegate::onRenderView(Runtime& /* self */, const RenderParams& renderParams)
{
    GL::Context::current().resetState(GL::Context::State::ExitExternal);

    GL::Renderer::setClearColor({0.5, 0, 0, 1});
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
    _mesh->draw(*_shader);

    GL::Context::current().resetState(GL::Context::State::EnterExternal);
}
```

I still have to write some shaders where I can pass out the view and projection matrix. 
Currently, my rendering is wrong I see only half of the rendered scene. Maybe Viewport is wrong..

**Comment by mosra** [comment]
In that case, instead of calling GL APIs directly, I recommend wrapping the custom framebuffer with `GL::Framebuffer::wrap()` and using Magnum's own APIs to clear it. You can find more info (although still Qt-related) on the mailing list archives, e.g.:

- https://groups.google.com/forum/#!topic/magnum-engine/ixnoqy9Aq8E
- https://groups.google.com/forum/#!topic/magnum-engine/L3oCvRgh5CY

The `resetState()` is needed when code (either yours or from a 3rd party lib) calls into GL, creates GL objects and so on (in case of Qt, Qt itself is using OpenGL to render itself, so there it was needed). If you're 100% sure there's no such thing happening, you don't need to.

**Comment by janbajana** [comment]
Ok, I see. Thanks for the info. 
I have to think more about this later. Currently, we are hiding FrameBuffer setup and binding behind the implementation. Also glClear().
So for now I can not use `GL::Framebuffer` class, so my render call looks like this:

```
void 
AppDelegate::onRenderView(Runtime& /* self */, const RenderParams& renderParams)
{
    GL::Context::current().resetState(GL::Context::State::ExitExternal);

    const RenderParams& r = renderParams;
    glViewport(r.viewPort.origin.x, r.viewPort.origin.y, r.viewPort.dimensions.width, r.viewPort.dimensions.height);

    mCubeMagnum->draw(renderParams.viewMatrix,
                      renderParams.projectionMatrix);

    GL::Context::current().resetState(GL::Context::State::EnterExternal);
}
```
Only glViewport() remains. This setup looks good for now. I am going to write some shaders to render with our projection params.
I am going to have a look also on OvrIntegration for Magnum. How it is done there.

Really thanks for the support and fast answers.

**Comment by mosra** [comment]
As long as you don't use magnum's `GL:.Framebuffer` for anything else, calling `glBindFramebuffer()`, `glViewport()`, `glClear()` directly will be fine. Once you start using the magnum framebuffer classes for offscreen rendering, you'll need to `resetState()` with [State::Framebuffers](https://doc.magnum.graphics/magnum/classMagnum_1_1GL_1_1Context.html#a48935899ecd7bc3897f5bf37777180eeac81a0bdfe577125a16bb2a53d37df5cf) to avoid state tracker confusion. (But I still think you could "just" use `GL::Framebuffer::wrap()` and avoid all those issues, there shouldn't be any bad interactions coming from this API.)

For the multiview extension I'll check and ping you back, I think someone already did some investigation (or maybe a partial implementation already).

**Comment by mosra** [comment]
Regarding `OVR_multiview`: unfortunately there's no in-progress implementation I know of, however I added at least the entry points for it -- see a0fa21c9fb0081aa198819ea0ba0799c5cfeeed7.

**Comment by janbajana** [comment]
Hi Vladimír,

thank you for your answers. This will help us to make future decisions about integration.
For `GL::Framebuffer::wrap()` I have to change our API because it requires Framebuffer id which we do not expose yet.

So far all looks good and I have working Magnum on our devices.
I have one more problem and it is compiled-in resources from `Utility::Resource` for Android. I am not sure my cmake config is right. Any ideas, here is my config?
https://github.com/janbajana/magnum-bootstrap-android/blob/master/src/CMakeLists.txt

```
corrade_add_resource(MagnumBootstrapData_RESOURCES resources/resources.conf)
add_library(MyApplication SHARED ${native_heads} ${native_srcs} ${MagnumBootstrapData_RESOURCES})
```
Compilation error is:
`ninja: error: '/c/Corrade/bin/corrade-rc.exe', needed by 'src/resource_MagnumBootstrapData_RESOURCES.cpp', missing and no known rule to make it
`

**Comment by mosra** [comment]
This looks like some bad interaction between a MinGW / Git Bash shell and CMake .. :/ Are you passing `CORRADE_RC_EXECUTABLE` on the command-line? Then the shell is probably changing `C:/` to `/c/` which CMake doesn't understand. Some options:

- open CMake GUI / ccmake and change the CORRADE_RC_EXECUTABLE from there, alternatively open CMakeCache.txt and edit this variable it manually to the correct value
- try one of the suggestions at https://stackoverflow.com/questions/7250130/how-to-stop-mingw-and-msys-from-mangling-path-names-given-at-the-command-line#34386471 or https://github.com/moby/moby/issues/24029#issuecomment-250412919 (`MSYS_NO_PATHCONV=1` should be enough, hopefully)

**Comment by janbajana** [comment]
Yes, you are right. I was passing the path in `Git Bash` format. 
If I run `gradlew` from the  `Git Bash` command line all is working. But from Android Studion it did not work. I should go back to Linux probably :). All god now. Thanks.

One more question. What is the prefered coordinate system in Magnum?
Left or Right handed?

**Comment by mosra** [comment]
The preferred one is what matches OpenGL -- +X is to the right, +Y up, +Z backward.

**Comment by mosra** [comment]
@janbajana anything left to be done here? :)

**Comment by janbajana** [comment]
No thanks. Forgot to close this.
