### ISSUE TITLE
sdl2application window icon update

### ISSUE THREAD

**Issue by hsdk123** [mosra/magnum#393]
Window icons tend to be one of those subtle but immediately noticeable finishing touches for an application. The following request is an addition of `https://wiki.libsdl.org/SDL_SetWindowIcon` to the sdl2application api.

**Comment by mosra** [comment]
Argh, why the SDL APIs have to be so underwhelming. GLFW has an API for setting a sequence of differently sized images, so one can be sure the icon looks great regardless of its size, but SDL accepts only a single image :/

**Comment by hsdk123** [comment]
Looks like it's time for the mosra to rise up and fill in the blanks! 

I wouldn't mind just having one image for a starting implementation though.

**Comment by mosra** [comment]
Done with 090c6bb4a7dec1db810f9c63ddfcd253f89337dd. According to my tests, if you supply a large enough image, it gets scaled down, which is better than a small image getting a blurry upscale, but still. GLFW has it better :)

Let me know if there are any issues with this.

**Comment by hsdk123** [comment]
Nice, looks good - thanks!
