### ISSUE TITLE
Document the need to enable blending for transparent images a bit better

### ISSUE THREAD

**Issue by hsdk123** [mosra/magnum#394]
I'm noticing that png files with alpha values don't have the setColor alpha values applied when using Flat3D shader (ex. `setColor({1.f, 1.f, 1.f, 0.f})` still displays the image). 

I'm currently using StbImageImporter for image importing. 

Other Peculiarities
- png images with transparent backgrounds have their transparent colours displayed as hard colours (ex. black or white instead of transparent)

Class implementation:
```
class lvn::CSpriteBuffer::BufferImpl
{
public:
	BufferImpl(const float width, const float height)
	{
		using namespace Magnum;
		using namespace Math::Literals;
		struct TriangleVertex {
			Vector3 position;
			Vector2 textureCoordinates;
		};

		// note: this places center in the middle of the texture
		const TriangleVertex data[]{
			{{-width / 2.f, -height / 2.f, 0.f}, {0.0f, 0.0f}},    /* Left vertex, red color */
			{{ width / 2.f, -height / 2.f, 0.f}, {1.0f, 0.0f}},    /* Right vertex, green color */
			{{ width / 2.f,  height / 2.f, 0.f}, {1.0f, 1.0f}},     /* Top vertex, blue color */

			{{-width / 2.f, -height / 2.f, 0.f}, {0.0f, 0.0f}},    /* Left vertex, red color */
			{{ width / 2.f, height / 2.f, 0.f}, {1.0f, 1.0f}},    /* Right vertex, green color */
			{{ -width / 2.f,  height / 2.f, 0.f}, {0.0f, 1.0f}}     /* Top vertex, blue color */
		};

		GL::Buffer buffer;
		buffer.setData(data);

		_mesh.setCount(6)
			.addVertexBuffer(std::move(buffer), 0,
				Shaders::Flat3D::Position{},
				Shaders::Flat3D::TextureCoordinates{});
	}

public:
	Magnum::GL::Mesh _mesh;
	Magnum::GL::Texture2D _texture;
	Magnum::Shaders::Flat3D _shader{ Magnum::Shaders::Flat3D::Flag::Textured };
};
```
Sample Usage:
```
m_buffer->_texture
			.setWrapping(Magnum::GL::SamplerWrapping::ClampToEdge)
			.setStorage(1, Magnum::GL::TextureFormat(image_data->format()), image_data->size())
			/*.setStorage(1, Magnum::GL::TextureFormat::RGBA8, image_data->size())*/
			.setSubImage(0, {}, *image_data);
m_buffer->_shader
			.setColor({1.f, 1.f, 1.f, 0.f})
			//.setColor(rgba)
			.setTransformationProjectionMatrix(lvn::CCameraMgr::GetInstance().getProjectionMatrix() * transform.GetTransformWorld())
			.bindTexture(m_buffer->_texture);
m_buffer->_mesh.draw(m_buffer->_shader);
```

Images:

![light_splash_1280](https://user-images.githubusercontent.com/4100142/68871433-6bcd5280-06ca-11ea-9ebf-b8711962ab6c.png)

![scg2](https://user-images.githubusercontent.com/4100142/68871878-1f364700-06cb-11ea-8a45-85b6088d7769.png)

**Comment by mosra** [comment]
You originally reported that the images get imported as `RGB8Unorm`, but checking with the above ones here, they get correctly imported as `RGBA8Unorm` with both `PngImporter` and `StbImageImporter`. So unless GitHub's image upload did something fishy with them, I can't reproduce.

In order to render the images with alpha transparency, blending has to be enabled and configured correctly, are you doing that? From the top of my head, it would be like this:

```cpp
GL::Renderer::enable(GL::Renderer::Feature::Blending);
GL::Renderer::setBlendFunction(GL::Renderer::BlendFunction::SourceAlpha, GL::Renderer::BlendFunction::OneMinusSourceAlpha);
GL::Renderer::setBlendEquation(GL::Renderer::BlendEquation::Add, GL::Renderer::BlendEquation::Add);
```

or, in case you have them with premultiplied alpha, then

```cpp
GL::Renderer::setBlendFunction(GL::Renderer::BlendFunction::One, GL::Renderer::BlendFunction::OneMinusSourceAlpha);
```

instead of the second line. I think. To decide which one is correct, look for unusually dark edges around the transparent areas. If they're not there, the blending is set up correctly.

**Comment by hsdk123** [comment]
Ah sorry, it seems like I had multiple textures on the screen and I was reading the pixel format for a different texture. I'll go ahead and check the blending equation, just a moment!

**Comment by hsdk123** [comment]
You were right about missing out on the blending equations!
I was more used to the below, hence used this equation instead (not sure if this is just the same equation)
```
GL::Renderer::enable(GL::Renderer::Feature::Blending);
GL::Renderer::setBlendFunction(GL::Renderer::BlendFunction::SourceAlpha, GL::Renderer::BlendFunction::OneMinusSourceAlpha,
GL::Renderer::BlendFunction::One, GL::Renderer::BlendFunction::OneMinusSourceAlpha);
GL::Renderer::setBlendEquation(GL::Renderer::BlendEquation::Add, GL::Renderer::BlendEquation::Add);
```
This fixes my issue, but I think it would make a nice reminder if alpha blending could be added as one of the examples in the examples page.

**Comment by mosra** [comment]
I fail at blending equations honestly, have to look them up every time :) I *think* the above is equivalent to

```cpp
GL::Renderer::setBlendFunction(GL::Renderer::BlendFunction::SourceAlpha, GL::Renderer::BlendFunction::OneMinusSourceAlpha,
                               GL::Renderer::BlendFunction::SourceAlpha, GL::Renderer::BlendFunction::OneMinusSourceAlpha);
```

which is then just a more verbose variant of 

```cpp
GL::Renderer::setBlendFunction(GL::Renderer::BlendFunction::SourceAlpha, GL::Renderer::BlendFunction::OneMinusSourceAlpha);
```

I'll see where this could be mentioned -- I don't want the example to become too crowded.

**Comment by hsdk123** [comment]
Sounds good!

**Comment by mosra** [comment]
Documentation added in c03ed3af7567d0d6459502eb3856cb55976b60c6 ([online](https://doc.magnum.graphics/magnum/classMagnum_1_1GL_1_1Renderer.html#a42c00dd07d227c8975b07e39ad3f6b09)), and it should be now also discoverable under `Alpha blending` and `Transparency` keywords.
