### ISSUE TITLE
Fail to build Magnum::Shaders target WinRT

### ISSUE THREAD

**Issue by linuxaged** [mosra/magnum#396]
Error shows when compiling `resource_MagnumShaders_RCS.cpp` : MSB6006: “cmd.exe” exit with code -1073741515

Details:

    C:\workspace\magnum\build-winrt>cmake .. -G "Visual Studio 16 2019" -A Win32 ^
    More? -DCMAKE_TOOLCHAIN_FILE=C:\workspace\vcpkg\scripts\buildsystems\vcpkg.cmake ^
    More? -DCMAKE_SYSTEM_NAME=WindowsStore ^
    More?     -DCMAKE_SYSTEM_VERSION=10.0 ^
    More? -DBUILD_STATIC=ON ^
    More? -DTARGET_GLES=ON ^
    More?     -DTARGET_GLES2=OFF ^
    More?     -DCMAKE_INSTALL_PREFIX="C:/Sys-winrt" ^
    More?     -DWITH_SDL2APPLICATION=ON ^
    More?     -DWITH_AUDIO=OFF ^
    More?     -DWITH_DEBUGTOOLS=OFF ^
    More?     -DWITH_MESHTOOLS=OFF ^
    More?     -DWITH_PRIMITIVES=OFF ^
    More?     -DWITH_TEXT=OFF ^
    More?     -DWITH_TEXTURETOOLS=OFF
    -- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.
    -- Found Corrade: C:/workspace/vcpkg/installed/x86-uwp/include  found components:  Containers rc Utility
    -- Found Corrade: C:/workspace/vcpkg/installed/x86-uwp/include  found components:  Containers rc Utility PluginManager
    -- Configuring done
    -- Generating done
    CMake Warning:
      Manually-specified variables were not used by the project:

        CMAKE_TOOLCHAIN_FILE

    -- Build files have been written to: C:/workspace/magnum/build-winrt

    C:\workspace\magnum\build-winrt>cmake --build . --config release --target install
    用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.3.2+e481bbf88
    版权所有(C) Microsoft Corporation。保留所有权利。

      Checking Build System
      MagnumMathObjects.vcxproj -> C:\workspace\magnum\build-winrt\src\Magnum\MagnumMathObjects.dir\Release\MagnumMathObjects.lib
      MagnumObjects.vcxproj -> C:\workspace\magnum\build-winrt\src\Magnum\MagnumObjects.dir\Release\MagnumObjects.lib
      Magnum.vcxproj -> C:\workspace\magnum\build-winrt\release\lib\Magnum.lib
      MagnumEglContextObjects.vcxproj -> C:\workspace\magnum\build-winrt\src\Magnum\Platform\MagnumEglContextObjects.dir\Release\MagnumEglContextObjects.lib
      MagnumFlextGLObjects.vcxproj -> C:\workspace\magnum\build-winrt\src\MagnumExternal\OpenGL\GLES3\MagnumFlextGLObjects.dir\Release\MagnumFlextGLObjects.lib
      MagnumGLObjects.vcxproj -> C:\workspace\magnum\build-winrt\src\Magnum\GL\MagnumGLObjects.dir\Release\MagnumGLObjects.lib
      MagnumGL.vcxproj -> C:\workspace\magnum\build-winrt\release\lib\MagnumGL.lib
      MagnumPlatformObjects.vcxproj -> C:\workspace\magnum\build-winrt\src\Magnum\Platform\MagnumPlatformObjects.dir\Release\MagnumPlatformObjects.lib
      MagnumSceneGraphObjects.vcxproj -> C:\workspace\magnum\build-winrt\src\Magnum\SceneGraph\MagnumSceneGraphObjects.dir\Release\MagnumSceneGraphObjects.lib
      MagnumSceneGraph.vcxproj -> C:\workspace\magnum\build-winrt\release\lib\MagnumSceneGraph.lib
      MagnumSdl2Application.vcxproj -> C:\workspace\magnum\build-winrt\release\lib\MagnumSdl2Application.lib
      Compiling data resource file C:/workspace/magnum/build-winrt/src/Magnum/Shaders/resource_MagnumShaders_RCS.cpp
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(230,5): error MSB6006: “cmd.exe”已退出，代码为 -1073741515。 [C:\workspace\magnum\build-winrt\src\Magnum\Shaders\MagnumShadersOb
    jects.vcxproj]
      MagnumTradeObjects.vcxproj -> C:\workspace\magnum\build-winrt\src\Magnum\Trade\MagnumTradeObjects.dir\Release\MagnumTradeObjects.lib
      MagnumTrade.vcxproj -> C:\workspace\magnum\build-winrt\release\lib\MagnumTrade.lib

**Comment by mosra** [comment]
So mosra/corrade#82 didn't work, after all? Because that's most probably the direct consequence :)

If you run the vcpkg-installed UWP `corrade-rc` manually, does it look like it works properly? Printing some output to the console at least?

**Comment by linuxaged** [comment]
Oh, get a system error: can not find VCRUNTIME140_APP.DLL
![image](https://user-images.githubusercontent.com/1172901/69056648-6023b800-0a4b-11ea-894b-871b5c6d822a.png)

**Comment by mosra** [comment]
Argh, I'm getting the same error on the CIs now. I thought you have tested your patch, oh well :sweat_smile: Any ideas how to solve this? Otherwise I have to revert the change.

Right now `corrade-rc` is not needed to build corrade itself (only used by the tests), so that's why the installation worked.

**Comment by mosra** [comment]
I reverted mosra/corrade#82 because it didn't work and thus this shouldn't happen anymore (but you need to provide native `corrade-rc` again).
