### ISSUE TITLE
Access violation with GlfwApplication and std::getenv

### ISSUE THREAD

**Issue by alanjfs** [mosra/magnum#400]
I think this will try and compare a string to a `nullptr`, when the environment isn't there.

https://github.com/mosra/magnum/blob/debddf658571cd2a653c6ffe82bc39f245a51ba7/src/Magnum/Platform/GlfwApplication.cpp#L472

![image](https://user-images.githubusercontent.com/2152766/69220787-aa04bf00-0b6d-11ea-8132-cff78b73d51f.png)

**Comment by mosra** [comment]
First of all: congrats on issue #400! :tada:

**Comment by alanjfs** [comment]
Woho, my first one at that!

**Comment by mosra** [comment]
Fixed by #401 :)
