### ISSUE TITLE
With Qt, adding a new mesh is not shown in Windows/Linux. Works in MacOS

### ISSUE THREAD

**Issue by Mscholli** [mosra/magnum#404]
I've stumbled over a strange issue when using Qt's QOpenGLWidget: A newly added `GL::Mesh` to a `SceneGraph::Drawable3D` is not shown at all in Windows or Linux, but works perfectly in MacOS.  The same code compiled with SDL2 as window manager works as it should (the mesh shows up) in all three OSs. 

Interestingly, upon deleting all existing meshes and re-adding a new mesh, its `_mesh.id()` re-starts at 1 in MacOS, but continues to count up in Linux/Windows. 

Being not terribly seasoned in c++, I am not sure if this is a programming error, a Magnum interop issue or a Qt issue. 
The attached files are single-file examples to demonstrate the issue:
* [QtAddMesh.tar.gz](https://github.com/mosra/magnum/files/3908585/QtAddMesh.tar.gz)
* [SDLAddMesh.tar.gz](https://github.com/mosra/magnum/files/3908586/SDLAddMesh.tar.gz)

Usage: Activate the window and press `U` to delete the mesh (if existing) and add a new one. It should work well with SDL2 but it plots nothing with Qt under Win/Lin.

Tested with the following configurations (using the latest Corrade/Magnum/SDL2/Qt5.13.2):

**Works:**

* Machine A: 
    * Compiler: Apple LLVM version 10.0.1 (clang-1001.0.46.4)
      Target: x86_64-apple-darwin18.7.0
    * Renderer: Intel(R) HD Graphics 5300 by Intel Inc.
        OpenGL version: 4.1 INTEL-12.10.14
        Using optional features:
            GL_ARB_ES2_compatibility
            GL_ARB_separate_shader_objects
            GL_ARB_texture_filter_anisotropic
            GL_ARB_texture_storage
            GL_ARB_vertex_array_object
            GL_EXT_debug_label
            GL_EXT_debug_marker
        Using driver workarounds:
            no-layout-qualifiers-on-old-glsl

* Machine B:
    * Compiler: Apple LLVM version 10.0.1 (clang-1001.0.46.4)
        Target: x86_64-apple-darwin19.0.0 
    * Renderer: AMD Radeon Pro 580 OpenGL Engine by ATI Technologies Inc.
        OpenGL version: 4.1 ATI-3.2.24
        Using optional features:
            GL_ARB_ES2_compatibility
            GL_ARB_separate_shader_objects
            GL_ARB_texture_filter_anisotropic
            GL_ARB_texture_storage
            GL_ARB_vertex_array_object
            GL_EXT_debug_label
            GL_EXT_debug_marker
        Using driver workarounds:
            no-layout-qualifiers-on-old-glsl

**Does *not* work:**

* Windows, running in a VM on Machine C:
    * Compiler: Mingw7.3.0, Qt.5.13.2, latest SDL2
    * Renderer: SVGA3D; build: RELEASE;  LLVM; by VMware, Inc.
        OpenGL version: 3.3 (Core Profile) Mesa 19.1.0 (git-cee1f21471)
        Using optional features:
            GL_ARB_ES2_compatibility
            GL_ARB_direct_state_access
            GL_ARB_invalidate_subdata
            GL_ARB_multi_bind
            GL_ARB_robustness
            GL_ARB_separate_shader_objects
            GL_ARB_texture_filter_anisotropic
            GL_ARB_texture_storage
            GL_ARB_texture_storage_multisample
            GL_ARB_vertex_array_object
            GL_KHR_debug
        Using driver workarounds:
            no-layout-qualifiers-on-old-glsl
            svga3d-gettexsubimage-oob-write
            svga3d-broken-dsa-bufferdata
            mesa-forward-compatible-line-width-range
            svga3d-texture-upload-slice-by-slice
 
* Linux, running on Machine D: 
    * Compiler: g++ (GCC) 9.2.0
    * Renderer: Quadro M3000 SE/PCIe/SSE2 by NVIDIA Corporation
        OpenGL version: 4.6.0 NVIDIA 430.26
        Using optional features:
            GL_ARB_ES2_compatibility
            GL_ARB_direct_state_access
            GL_ARB_get_texture_sub_image
            GL_ARB_invalidate_subdata
            GL_ARB_multi_bind
            GL_ARB_robustness
            GL_ARB_separate_shader_objects
            GL_ARB_texture_filter_anisotropic
            GL_ARB_texture_storage
            GL_ARB_texture_storage_multisample
            GL_ARB_vertex_array_object
            GL_KHR_debug
        Using driver workarounds:
            no-layout-qualifiers-on-old-glsl
            nv-zero-context-profile-mask
            nv-implementation-color-read-format-dsa-broken
            nv-cubemap-inconsistent-compressed-image-size
            nv-cubemap-broken-full-compressed-image-query
            nv-compressed-block-size-in-bits

**Comment by alanjfs** [comment]
I suspect this may be the same issue I've been having with my Intel card. Can you try this?

```bash
yourapplication.exe --magnum-disable-extensions GL_ARB_direct_state_access
```

**Comment by Mscholli** [comment]
I'll give that a try. Is there a way to disable extensions in code instead of the command line? Otherwise I'll need to find out how to pass the command line arguments to the QOpenGLWidget

**Comment by alanjfs** [comment]
> Is there a way to disable extensions in code instead of the command line?

Haha, yes I've been asking the very same question. :) Currently, what you can do is set an environment variable prior to creating the OpenGL context.

```bash
setenv("MAGNUM_DISABLE_EXTENSIONS", "GL_ARB_direct_state_access");
```

**Comment by Mscholli** [comment]
Tested it in Linux, Magnum confirms that the `GL_ARB_direct_state_access` extension has been disabled, but the mesh still does not show up.  

Also gotta correct myself, the `mesh.id()` issue only appears in Windows, in Linux the `mesh.id`'s do not count up upon deleting and re-adding. Is this an additional Windows issue?

**Comment by Mscholli** [comment]
Update: After installing Corrade/Magnum/SDL2/Qt (Corrade/Magnum from latest stable sources, complied with mingw) in Windows 10 on my dual-boot iMac, I get the mesh lines to show up in Windows and the `mesh.id()` stays at one. *However*, it only works when a mesh has already been set up in `initializeGL()` and is drawn in the first call to `paintGL()`. 
Without pre-initializing a mesh, it still does not show up. 
*Interestingly, with pre-initializtion the `mesh.id()` stays at 1 this time. Without it, the first mesh has `mesh.id()=2`, which might be the root cause of why it is not being drawn.*  

SDL still works without any problems, without pre-initialization. 

For completeness, this machine has the following configuration:
* Compiler: mingw-7.3.0 64-bit
* Renderer: Radeon Pro 580 by ATI Technologies Inc.
* OpenGL version: 4.5.13476 Compatibility Profile Context 22.19.170.1536
    Using optional features:
        GL_ARB_ES2_compatibility
        GL_ARB_direct_state_access
        GL_ARB_get_texture_sub_image
        GL_ARB_invalidate_subdata
        GL_ARB_multi_bind
        GL_ARB_separate_shader_objects
        GL_ARB_texture_filter_anisotropic
        GL_ARB_texture_storage
        GL_ARB_texture_storage_multisample
        GL_ARB_vertex_array_object
        GL_KHR_debug
    Using driver workarounds:
        no-layout-qualifiers-on-old-glsl
        amd-windows-broken-dsa-cubemap-copy
        amd-windows-dsa-createquery-except-xfb-overflow
        amd-windows-cubemap-image3d-slice-by-slice

**Comment by mosra** [comment]
Hi! 

I don't have time to fully dive into the code right now (might have more time later this week, tho), but this sounds like Magnum's state tracker gets confused when Qt calls into GL. Can you sprinkle the code with more `resetState()` calls? In particular, do the same as is done for `paintGL()` also in `keyPressEvent()`. I know very little about Qt internals, but I suspect that it does something with GL also in between those two functions, causing Magnum to act up.

Since the same code works with SDL, I don't think it's related to the cursed Intel/Windows-specific issue that @alanjfs mentioned and which we are still fighting. It works on the Mac because there's no `ARB_direct_state_access` and an app without it is doing many more GL state changes, thus being less likely to hit state tracker issues. But it's only a coincidence and due to the way this particular code is written, `ARB_DSA` in particular isn't to blame :)

**Comment by Mscholli** [comment]
Hi Mosra,
I've added the `_context.resetState(GL::Context::State::ExitExternal);` and `_context.resetState(GL::Context::State::EnterExternal);` calls to `paintGL()` but that didn't change anything. `mesh.id()` still starts at 2 and nothing is shown. 
Is there another method/flag to try to reset the state? 

I did some further testing. It seems like the initial mesh is not being updated properly. If I start the Qt app with a mesh defined in `initializeGL` and which is added to a `scenegraph::DrawableGroup3D` before the window is show, the mesh is drawn and updating works. However, the size of the mesh or vertexBuffer is not being updated. For example, plotting a `mesh->setPrimitive(MeshPrimitive::Lines)` with just one line (2 vertices) being defined in `initializeGL`, and `mesh-setCount(2)`, plots the line. If then in `keyPressEvent` this mesh is deleted and a new mesh is generated with for example 6 vertices (3 lines), only the first 2 vertices are drawn even though `mesh.count()` is correctly reported as 6. I think that's why the updating does not work when no initial mesh has been defined, its size stays at 0 even after deleting and adding a new mesh to the `DrawableGroup3D`. 

Doing the same in SDL2 properly updates the mesh and "forgets" the initial mesh size.

**Comment by mosra** [comment]
So! Finally had a chance to look at the code with a fresh brain :)

I managed to make this working here on Linux by calling `makeCurrent()` at the beginning of `keyPressEvent()` -- apparently the GL context is made current only during `paintGL()`. Looking at QOpenGLWidgets's docs, it's mentioned there: https://doc.qt.io/qt-5/qopenglwidget.html#details

```cpp
void oglWin::keyPressEvent(QKeyEvent *event) {
    makeCurrent(); // important
```

The `resetState()` calls seemingly weren't needed in the event handler, but if you run into issues further down the road, try to add them again. Again, as I said, I know only very little what all Qt does internally, so being more careful won't hurt. 

Additionally, the app aborted on exit complaining that no context is current. This is because the `Platform::GLContext` gets destroyed earlier than other members that need to call into GL on destruction to clean up. So, reorder them like this to fix the crash:

```cpp
        Platform::GLContext _context{NoCreate}; // first, so it's destructed last

        Shaders::Flat3D _shader{NoCreate};
        std::vector<FlatDrawable*> _objects;

        Scene3D _scene;
        SceneGraph::DrawableGroup3D _drawables;
        Object3D *_cameraObject;
        SceneGraph::Camera3D *_camera;

        GL::Framebuffer fbo{NoCreate};
```

**Comment by Mscholli** [comment]
Yes, `makeCurrent()` fixes it, thank you!!

I've tested before with `GL::Context::makeCurrent(&_context)`, which didn't help  but it didn't occur to me that I need to tell Qt to make the context current instead of Magnum.

What's still bothering me a bit, but doesn't affect functionality now, is that on Windows, with Mesa 19 as renderer, the `mesh.id()` keeps counting up instead of staying at 1.

**Comment by mosra** [comment]
That's a driver-specific thing, I'd say. Some reuse the IDs, some use an ever-increasing sequence (which I think is better because you can discover dangling IDs easier when the IDs are not reused). 

If you want to be extra sure, you can check for GL object leaks with ApiTrace or Renderdoc (I think both have such a feature), but unless you're doing something intentionally (leaking a `new`-allocated `GL::Mesh`), it shouldn't happen.
