### ISSUE TITLE
iOS build unable to find EGL headers

### ISSUE THREAD

**Issue by hsdk123** [mosra/magnum#409]
Hi, I'm trying to build for iOS, and I'm getting the following include errors upon trying to build
```
EGL/egl.h
```
Are there any additional steps I need to take with the system?

**Comment by mosra** [comment]
Hi, saw your message on Gitter but didn't manage to reply in time (sorry) -- which file does this happen with?

**Comment by hsdk123** [comment]
Starting all over and making a fresh build seems to have fixed the errors, I'll open a new issue if this actually isn't the case.
