### ISSUE TITLE
Yeah, it is a filesystem race.

### ISSUE THREAD

**Issue by celentes** [mosra/magnum#414]
Yeah, it is a filesystem race.
emar calculates a hash based on full file path, copies it with added hash, runs llvm-ar on it, then tries to delete it. So when two threads are running emar on the same file, one can delete the file before the other one has sent it off to llvm-ar.
I'll post an issue to emscripten

_Originally posted by @celentes in https://github.com/mosra/magnum/issues/413#issuecomment-571314928_

**Comment by celentes** [comment]
dup, sorry

**Comment by mosra** [comment]
🤔 Is this what the <kbd>Reference in new issue</kbd> entry in the three-dot menu does? :) If so, I am afraid to ever click it :D

**Comment by celentes** [comment]
Yeah, i was desperately trying to figure out how issues and mentions intercommunicate
