### ISSUE TITLE
Question about multi-window support in Platform::Appliciation for SDL2

### ISSUE THREAD

**Issue by mredstone6** [mosra/magnum#426]
I have been currently developing an application based on this library and I need to handle a multiple windows interface. Is it possible to create a multi-window application with only one GL context based on the Application class.
I have seen that this request as already been asked by @LB-- and in the issue #124 but I would like to know if it is currently available. Thank you for answer.

**Comment by mosra** [comment]
Hi, 

it is not implemented in the Application wrappers *yet* (sorry about that, too much to do, too little time, I have to prioritize), but possible by using SDL APIs directly -- see the discussion in #168 and #321. If you experience any issues, feel free to ask on Gitter (https://gitter.im/mosra/magnum), there's multiple people who managed to implement this on their own.

If you don't mind, I'll close this in favor of #124 to avoid having multiple open issues about the same thing ;) Let's continue the discussion there.
