### ISSUE TITLE
Render a video feed

### ISSUE THREAD

**Issue by helmesjo** [mosra/magnum#431]
Now, the title says it all, and please feel free to assume I know nothing. :)

I'm lacking some complete examples of going from an image buffer -> render on screen (not only setting up a `ImageView` instance, but all the way to drawing it. Given that it's usually 20+ loc to get mesh, texture and whatnot all setup, could you direct me to a bare minimum example of doing this? I'm gathering pieces here and there but it's a bit too many steps for me to not make a mistake and scratch my head for countless hours. 
My current usage of Magnum is only scratching the surface, since it's (currently) only used for very simple visualization of data streamed from a camera.

What I want to do:
1. Take an image buffer streamed and render it on screen.
2. Redo step 1 when the next frame arrives.

Also the image size might change dynamically (cameras added/removed).

Sorry if I come off a bit lazy here, but I figure someone more competent could probably outline the required components in a fraction of the time it would take me to figure it out myself, since this is not at all my area of expertise). :)

**Comment by Janos95** [comment]
Hey Fred,
I think the canonical way to do this is to render a triangle covering the window and attaching the image as a texture to the triangle. I have put a little example into this [repository](https://github.com/Janos95/screen_triangle_example). Since I don't have your image stream the code is painting random images to the screen. The easiest way to inject your stream is probably to use the tickEvent and set the tick interval to an appropriate value.

**Comment by mosra** [comment]
*(Usual apology for replying extremely late -- sorry.)*

There's now an [Animated GIF](https://doc.magnum.graphics/magnum/examples-animated-gif.html) example that implements a very crude looping playback of a finite set of frames, which should hopefully give you something to start with. In your case you would be instead uploading a new image every frame, so not dealing with texture offset or anything. Hope this helps :)

A streaming API (and video importers) is planned, subscribe to #360 for details.

**Comment by helmesjo** [comment]
@Janos95 @mosra 
Great, big thanks to you both! I'll check it out. :)

**Comment by mosra** [comment]
To avoid duplicating information on two separate places, let's continue this in #360.
