### ISSUE TITLE
[MSYS2/Mingw-w64/Clang] duplicate section has different size

### ISSUE THREAD

**Issue by Amphaal** [mosra/magnum#439]
I'm trying to compile the `base.zip`-like project, but using Clang (via a CMake toolchain file).
Compiling prints a linking warning : 
```
C:/msys64/mingw64/lib/libMagnumGlfwApplication-d.a(GlfwApplication.cpp.obj): duplicate section ".rdata$_ZTSN6Magnum8Platform15GlfwApplicationE[_ZTSN6Magnum8Platform15GlfwApplicationE]" has different size. 
```

Forcing the usage of LLVM's LLD with `-fuse-ld=lld` gives me this error : 

```
lld-link: error: duplicate symbol: typeinfo name for Magnum::Platform::GlfwApplication
>>> defined at CMakeFiles/appExec.dir/src/main.cpp.obj
>>> defined at libMagnumGlfwApplication-d.a(GlfwApplication.cpp.obj)
```

My toolchain file is as simple as : 

```
list(APPEND CMAKE_PREFIX_PATH 
    ${MINGW64_ROOT} 
)
SET(CMAKE_BUILD_TYPE Debug)
SET (CMAKE_C_COMPILER "clang")
SET (CMAKE_CXX_COMPILER "clang++")
SET (CMAKE_C_FLAGS "-fuse-ld=lld")
SET (CMAKE_CXX_FLAGS ${CMAKE_C_FLAGS})
```

I've tried this using the official Magnum [MSYS2 package](https://packages.msys2.org/package/mingw-w64-x86_64-magnum?repo=mingw64), but also with the latest HEAD (local compilation of Corrade + Magnum). Same issue with both SDL2 and GLFW.

I've had absolutely no issue nor warnings with GNU tho.

Am I doing something wrong here ?

**Comment by mosra** [comment]
Hi, I'm sorry but MSY2 Clang is not really supported at this point. We tried (see #227, #417) but nobody managed to get this thing running on it yet. I have no idea what's this error about, even :sweat_smile: -- probably something related to the application libraries being static, while the rest is DLLs?

On the other hand clang-cl (from MSVC) works.

**Comment by Amphaal** [comment]
Thank you for your quick response ! Alrighty, I'll propose a fix if I can find the cause of this issue ;)

**Comment by Amphaal** [comment]
Hi back @mosra, just looked at this issue and finally managed to compile. The problem here is obviously caused by explicit inclusion of headers into the `add_library` declaration, as of : 

```
    add_library(MagnumSdl2Application STATIC
        ${MagnumSdl2Application_SRCS}
        ${MagnumSdl2Application_HEADERS})
```

Produces the duplicate symbol error, but : 

```
    add_library(MagnumSdl2Application STATIC
        ${MagnumSdl2Application_SRCS})
```

... does not. Same pattern for the Glfw helper.

Any particular reasons to include headers into the static libs, which are expected to be included later on by the end user ? I still find quite strange that other compilers can just ignore this 🤔 

Cheers !

**Comment by mosra** [comment]
Hi, glad you're back :) ... but oh what the hell :see_no_evil: 

This is just silly. The inclusion of headers is there just to ~~help~~ work around issues in some particular IDEs (such as QtCreator) to properly show headers in the project tree (otherwise it used to omit all that didn't have a corresponding `cpp` file, but maybe that got fixed since).

I guess I could add a workaround to this workaround to not include the headers when compiling with mingw/clang, but I wonder how many more of such cases is there. I checked the headers and there are no out-of-class `inline` functions or non-inline templates that are the common causes for issues on MinGW, so I wonder *why* that happens, and why that happens just for the application classes and nowhere else. 

Question -- if you build Magnum with `BUILD_STATIC` enabled, does that happen for other libs too?

**Comment by Amphaal** [comment]
After few more tests, it seems that the inclusion of headers into the static lib is completely unrelated with the issue. Sorry if I've been misleading.

To wrap things up, these are the use cases I came across : 

- GNU `libMagnumSdl2Application.a` + `magnum-bootstrap-base` (Clang) = error with `LLD`, warning with `LD`
- GNU `libMagnumSdl2Application.a` + `magnum-bootstrap-base` (GNU) = OK
- Clang `libMagnumSdl2Application.a` + `magnum-bootstrap-base` (Clang) = OK
- Clang `libMagnumSdl2Application.a` + `magnum-bootstrap-base` (GNU) = OK

Linking `magnum-bootstrap-base` with a static version of Magnum leads to the same results. (Clang on MinGW also complains about `Context*& magnumGLUniqueCurrentContext()` btw)

Maybe unrelated, but I also noticed that `libMagnumSdl2Application.a` is 50ko leaner when generated with Clang.

I still have no clue on what is going on here ! 🤯

**Comment by mosra** [comment]
Ah, seems like some unfortunate ABI incompatibility between MinGW GCC and Clang... I remember ABI incompatibilities happening between GCC and Clang on Linux in GCC 4 times, but since then it's been quite stable. MinGW apparently didn't reach that level of stability yet :)

I'd say we "fix" this by suggesting that users don't mix compilers on MinGW? :D

**Comment by Amphaal** [comment]
Alright, I just wanted to wait for LLVM 11 to be released on MSYS2 and test once more, and miraculously witness absolutely no evolution whatsoever :clap: !

As I really want to use Clang/LLD with MinGW (some kind of masochism really), I'll compile Magnum / Corrade as subprojects for now on, which is not really an issue. 

There are still additionnal warnings and inconsistencies with MinGW Clang, but I think you are already really close to achieve compatibility. I'll work on a draft to fix these issues ASAP !

**Comment by Amphaal** [comment]
As a side note, LLD for MinGW (`lld-link`) have indeed an option to treat this issue as a warning - just like LD does by default. Just update your toolchain with `SET(CMAKE_EXE_LINKER_FLAGS "-Wl,/force:multiple")`.

**Comment by williamjcm** [comment]
> Hi, I'm sorry but MSY2 Clang is not really supported at this point. We tried (see #227, #417) but nobody managed to get this thing running on it yet. I have no idea what's this error about, even 😅 -- probably something related to the application libraries being static, while the rest is DLLs?
> 
> On the other hand clang-cl (from MSVC) works.

Oh, sorry I didn't talk about this sooner, but I'm sure I managed to build one of my Magnum-based projects with Clang recently.

I use Corrade/Magnum as Git submodules, though, so dunno how that would interact with the GCC-built packages.

I'll check my project again, just in case.

**Comment by williamjcm** [comment]
So, I tried building the `base` bootstrap project with MSYS2/MinGW-w64/Clang, while using the MSYS2/MinGW-w64/GCC-built packages.

Here's the CMake command-line I used: ` cmake -GNinja -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_BUILD_TYPE=Release ..`

While running Ninja did give me the `duplicate section [...] has different size` message, it seems to be just a warning, as the project seems to run without apparent issues:

![image](https://user-images.githubusercontent.com/13572456/97106273-d780b380-16c0-11eb-814d-fca3c712c1fe.png)

**Comment by mosra** [comment]
> There are still additionnal warnings and inconsistencies with MinGW Clang, but I think you are already really close to achieve compatibility. I'll work on a draft to fix these issues ASAP !

@Amphaal that would be great, thank you! 

@williamjcm that's with LD and not LLD, right? :)

**Comment by williamjcm** [comment]
> @williamjcm that's with LD and not LLD, right? :)

That's... actually a good question. I tried running Ninja with `-v`, but the command-line only shows `clang++`, so I don't know which one is used under the hood.

**Comment by Amphaal** [comment]
> EDIT: I managed to get it to use LLD (it's a separate package in MSYS2's repo), which requires `libc++` (also a separate package). And I do encounter the "duplicate symbols" error too.

Okay my CI is now content and succeded compiling, packaging and uploading. 

I guess we should give up for now on GNU/LLVM tooling cohabitation as @mosra said. 

Under-the-hood optimisations of said linkers and compilers are quite heavy to track, and so far subprojecting Magnum is really easy and convenient. Maybe someone more experienced with GNU / LLVM can fix this ? I surely cannot :sadge:

I think that, to celebrate this happy ending, we may consider closing the issue. 
Maybe a simple advice in the documentation regarding this very specific usecase and how to "solve it" can be added ? The mere existence of this ticket might be enough tho.

**Comment by Amphaal** [comment]
Oh, and there are still 80+ warnings regarding redundant `dllexport` declarations, expect a pull request soon enough :)

**Comment by williamjcm** [comment]
In the official MSYS2 Gitter channel, there has been discussion about making a Clang-based environment in `/clang{32,64}` similarly to `/mingw{32,64}`, so I guess they're also aware of the incompatibilities between MinGW-w64/GCC and Clang.

**Comment by mosra** [comment]
> Maybe a simple advice in the documentation regarding this very specific usecase and how to "solve it" can be added ?

Good idea. Added to [Windows troubleshooting docs](https://doc.magnum.graphics/magnum/platforms-windows.html#platform-windows-troubleshooting-duplicate-section-has-different-size) in 8ec6b18c71e6f4588f0a732ba0b9e20186bcd62a. Thanks a lot for all the effort you put in :+1:

**Comment by sab24** [comment]
I had this problem as well but solved it by compiling llvm with the newest lld to solve it. Even release 11 is not new enough to make the problem go away, so somewhere between that time interval things have been fixed in LLVM.

**Comment by Amphaal** [comment]
Very cool ! Were you using https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-clang patches to compile ?

I'll retry once 11.0.1 goes live, hopefully it will contain the fix :)

**Comment by sab24** [comment]
Actually I used crosstool-ng to cross compile on my linux server and just copied that environment to Windows and made my project compile with a 2000 character cmake command specifiying all the include directories, using static linking. I’m not sure what version of msys they use. I don’t think they include that clang patch as I compiled everything, including libraries such as fmt and flatbuffers on linux with gcc

**Comment by deannagarcia** [comment]
I'm still hitting this error. Do you have any workarounds/suggestions to get the compile working?

**Comment by mosra** [comment]
Only what was added to the documentation [linked above](https://doc.magnum.graphics/magnum/platforms-windows.html#platform-windows-troubleshooting-duplicate-section-has-different-size), so compiling all libraries with the same compiler instead of mixing up GCC and Clang.
