### ISSUE TITLE
[Question] Can we just control the render pipeline?

### ISSUE THREAD

**Issue by dongfangliu** [mosra/magnum#447]
I wish to control when to render one frame, but magnum seems to warp the whole workflow as a\ continuous running application?

**Comment by dongfangliu** [comment]
This is quite critical for my reinforcement learning project. I wish get control signals and then render a frame and then get next signal and then render...

**Comment by dongfangliu** [comment]
Also, another questions arises when i try to add the magnum into my pybind11 target
When i do 
`#include <Magnum/GL/DefaultFramebuffer.h>`
`#include <Magnum/GL/Renderer.h>`

Then i got:
```
[build] In file included from /usr/include/Magnum/GL/OpenGL.h:38:0,
[build]                  from /usr/include/Magnum/GL/AbstractObject.h:36,
[build]                  from /usr/include/Magnum/GL/AbstractFramebuffer.h:35,
[build]                  from /usr/include/Magnum/GL/DefaultFramebuffer.h:32,
[build]                  from /home/liuwj/Skeletal-new/src/simulatorInterface/../MagnumVisualize/imguiWindow.h:3,
[build]                  from /home/liuwj/Skeletal-new/src/simulatorInterface/library.cpp:7:
[build] /usr/include/MagnumExternal/OpenGL/GL/flextGL.h:40:2: error: #error Attempt to include auto-generated header after including gl.h
[build]  #error Attempt to include auto-generated header after including gl.h
```

**Comment by mosra** [comment]
Hi, magnum supports both approaches: 

- a windowed application that waits for input events and renders in a loop, which is what most examples do
- and a windowless application that renderes offscreen to a buffer, which you then feed into whatever consumer of the data you need

Your case is most probably the latter, [see the docs for details](https://doc.magnum.graphics/magnum/platform.html#platform-windowless) -- there's also a bootstrap project for you to start with.

For the second question, it seems that some other library is including GL headers as well, and those conflict with the ones in Magnum. Try to include Magnum headers first.

By the way, for general questions like this, feel free to join the [Gitter channel](https://gitter.im/mosra/magnum) -- simply log in with your GitHub account :)

**Comment by dongfangliu** [comment]
Thanks for your quick reply.
I will try..
