### ISSUE TITLE
Compile issues on osx

### ISSUE THREAD

**Issue by hsdk123** [mosra/magnum#452]
Hi, I'm trying to compile on osx and am getting the following issues for master:

`Implicit instantiation of undefined template 'Magnum::Math::BoolVector<80>'` (TextureState.h)

`No member named 'ARB' in namespace 'Magnum::GL::Extensions'; did you mean 'ARM'?` (TextureState.cpp)

**Comment by hsdk123** [comment]
It looks as if the ARB issues are coming from the fact that I'm trying to build against opengl es, and the ifdef doesn't seem to have been placed in TextureState.cpp

I'm unsure of the undefined template issue.

**Comment by mosra** [comment]
Oh yup this is most definitely a bug. This is all wrapped in `#if defined(CORRADE_TARGET_APPLE) && !defined(CORRADE_TARGET_IOS)` which is wrong because it doesn't take into account mac + ES.

I'm sure we talked about this before but I don't remember what ES implementation are you running on. Is this ANGLE or something else?

**Comment by hsdk123** [comment]
Nice, I'm running against ANGLE : b

**Comment by mosra** [comment]
This should hopefully fix the compilation and not cause any runtime assert either, can you confirm?

```patch
diff --git a/src/Magnum/GL/Implementation/TextureState.h b/src/Magnum/GL/Implementation/TextureState.h
index 55c38bb92..2f0169423 100644
--- a/src/Magnum/GL/Implementation/TextureState.h
+++ b/src/Magnum/GL/Implementation/TextureState.h
@@ -158,7 +158,7 @@ struct TextureState {
     #endif
 
     Containers::Array<std::pair<GLenum, GLuint>> bindings;
-    #if defined(CORRADE_TARGET_APPLE) && !defined(CORRADE_TARGET_IOS)
+    #if defined(CORRADE_TARGET_APPLE) && !defined(CORRADE_TARGET_GLES)
     Math::BoolVector<80> bufferTextureBound;
     #endif
     #if !defined(MAGNUM_TARGET_GLES2) && !defined(MAGNUM_TARGET_WEBGL)
diff --git a/src/Magnum/GL/Implementation/driverSpecific.cpp b/src/Magnum/GL/Implementation/driverSpecific.cpp
index 1426b27cd..fdd9ee237 100644
--- a/src/Magnum/GL/Implementation/driverSpecific.cpp
+++ b/src/Magnum/GL/Implementation/driverSpecific.cpp
@@ -40,7 +40,7 @@ namespace {
 /* Search the code for the following strings to see where they are implemented. */
 const char* KnownWorkarounds[]{
 /* [workarounds] */
-#if defined(CORRADE_TARGET_APPLE) && !defined(CORRADE_TARGET_IOS)
+#if defined(CORRADE_TARGET_APPLE) && !defined(CORRADE_TARGET_GLES)
 /* Calling glBufferData(), glMapBuffer(), glMapBufferRange() or glUnmapBuffer()
    on ANY buffer when ANY buffer is attached to a currently bound
    GL_TEXTURE_BUFFER crashes in gleUpdateCtxDirtyStateForBufStampChange deep

```

**Comment by hsdk123** [comment]
Seems to fix most of the original issues, now I'm getting
```
No member named 'bufferTextureBound' in 'Magnum::GL::Implementation::TextureState'
```
(Bufer.cpp line 560)

What's interesting is that if I add
`#define CORRADE_TARGET_GLES` on line 552, the error goes way,
hence I'm assuming that for whatsoever reason CORRADE_TARGET_GLES isn't getting passed into MagnumGLObjects

**Comment by mosra** [comment]
Err, I messed up the original patch, it included `CORRADE_TARGET_GLES` (which isn't a thing, should be `MAGNUM_TARGET_GLES` instead). It's updated above, can you try the new fixed version?

**Comment by hsdk123** [comment]
Seems I might also need to update line 493 in TextureState.cpp - can you confirm?

**Comment by hsdk123** [comment]
If I add that, I now get:
```

Showing All Errors Only
make: *** No rule to make target `/Users/hkim809/Desktop/SoulEngineProject/Light.vn-multi/core/magnum/src/Magnum/Shaders/AbstractVector2D.vert', needed by `/Users/hkim809/Desktop/SoulEngineProject/Light.vn-multi/core/build/magnum/src/Magnum/Shaders/resource_MagnumShaders_RCS.cpp'.  Stop.
```

**Comment by mosra** [comment]
> Seems I might also need to update line 493 in TextureState.cpp

Yes, missed that one, sorry.

> `AbstractVector2D.vert` 

There's no such file anymore, the 2D and 3D variant got combined into `AbstractVector.vert`. Not sure why it still wants it -- try to re-run CMake? Recreate the build dir?

**Comment by hsdk123** [comment]
XCode is a pain...

I can confirm things build! I get the feeling adding a CI build for this particular setup might help things as we move forward.

**Comment by mosra** [comment]
You mean Mac + ANGLE? I'd need a Mac ANGLE build for that -- would you be able to contribute a GitHub Workflows setup https://github.com/mosra/magnum-ci/tree/angle ? There's already a Windows and WinRT/UWP build of it, so this should be just another job, targeting Mac.

(I suppose ANGLE itself doesn't provide Mac nightly builds or anything like that, in that case I would just use that.)

**Comment by hsdk123** [comment]
> You mean Mac + ANGLE

Exactly

> contribute a GitHub Workflows setup https://github.com/mosra/magnum-ci/tree/angle

It doesn't look too complicated, but I'm sadly not familiar with Github Workflows - how would I build / test? (if those are even the appropriate terms)

**Comment by mosra** [comment]
You'd fork the repo and then you can iterate on that, the `Actions` tab in your fork will build each time you push. I think. For reference, this is how the windows support was done: https://github.com/mosra/magnum-ci/pull/1

I'm asking only because I assume you already built ANGLE for Mac yourself so you already know the magic incantations :) 

(I'm not familiar with GitHub Workflows / Actions either, but it seems like the most straighforward solution compared to external CI solutions.)

**Comment by hsdk123** [comment]
> I'm asking only because I assume you already built ANGLE for Mac yourself so you already know the magic incantations :)

Yup, it wasn't too complicated - gotcha, why don't I start on something then, I might ask a ton of questions along the way though...

**Comment by mosra** [comment]
No problem. Open a WIP PR on the repo and direct the questions there, I'll definitely learn something from that also :)

**Comment by mosra** [comment]
Patch commited as 6feb5a4cabaf40ce29300603ef7930de87495236.
