### ISSUE TITLE
'operator <<' is ambiguous

### ISSUE THREAD

**Issue by Epsola** [mosra/magnum#463]
After getting Magnum setup with the vcpkg, I can't build any of the examples.

I'm getting a long list of errors, all the same....
![image](https://user-images.githubusercontent.com/54701802/88867491-f2be5d00-d250-11ea-8943-7319860faa56.png)

**Comment by mosra** [comment]
Hi, uh oh -- sorry about this. What's your Visual Studio version? Is it a stable release or some preview?

This `__builtin_FILE` is a feature that's new in VS2019 16.6 (used for [source location in debug output](https://doc.magnum.graphics/corrade/classCorrade_1_1Utility_1_1Debug.html#Utility-Debug-source-location)) and it seems that I got the version detection wrong and it got enabled on older versions by accident as well.

**Comment by Epsola** [comment]
Hey mosra, I'm using v16.6.5, the latest stable release I believe.

**Comment by pezcode** [comment]
Not on latest corrade master, but `Debug() << __builtin_FILE() << __builtin_LINE()` works on VS 16.6.5 for me. Both with MSVC and clang-cl. Mysterious 🦆

**Comment by mosra** [comment]
@Epsola are those just IntelliSense errors or do the errors happen also if you press Build? I mean, if Corrade itself installed properly with vcpkg, there's no reason why a project using it should suddenly fail. Or do you use some custom settings in your project, particular standard version etc?

In case it's just IntelliSense complaining, this could be easily worked around by modifying `Debug.h`:

```patch
diff --git a/src/Corrade/Utility/Debug.h b/src/Corrade/Utility/Debug.h
index b1ce1d8a..a2fe03a3 100644
--- a/src/Corrade/Utility/Debug.h
+++ b/src/Corrade/Utility/Debug.h
@@ -53,7 +53,7 @@ information.
 */
 /* To distinguish Apple Clang (9.0 will hopefully be Xcode 12), using
    __apple_build_version__ according to https://stackoverflow.com/a/19391724 */
-#if defined(DOXYGEN_GENERATING_OUTPUT) || (defined(__GNUC__) && !defined(__clang__)) || (defined(__clang__) && ((defined(__apple_build_version__) && __clang_major__ >= 12) || (!defined(__apple_build_version__) && __clang_major__ >= 9))) || (defined(_MSC_VER) && _MSC_VER >= 1926)
+#if defined(DOXYGEN_GENERATING_OUTPUT) || (defined(__GNUC__) && !defined(__clang__)) || (defined(__clang__) && ((defined(__apple_build_version__) && __clang_major__ >= 12) || (!defined(__apple_build_version__) && __clang_major__ >= 9))) || (defined(_MSC_VER) && _MSC_VER >= 1926 && !defined(__INTELLISENSE__))
 #define CORRADE_UTILITY_DEBUG_HAS_SOURCE_LOCATION
 namespace Implementation { struct DebugSourceLocation; }
 #endif

```

**Comment by Epsola** [comment]
@mosra They were build errors. Interestingly, today I did an upgrade on the magnum packages and it's working now. I guess this is solved unless it randomly pops up again.

**Comment by mosra** [comment]
Huh. I hate this kind of strange issues, let's hope it doesn't pop up again, then :)

In case it does reappear, please comment here and I'll disable this piece of code for MSVC until it's clear what's going on.
