### ISSUE TITLE
Few questions regarding this project

### ISSUE THREAD

**Issue by Joe23232** [mosra/magnum#465]
Hi I have a few questions regarding this project.

1. Am I able to program my game in C++?
2. Does it come with a GUI editor?
3. Does this game engine support 3D models and animations that comes with it?

**Comment by Squareys** [comment]
Hi @Joe23232 !

Welcome to Magnum :)

1. Yes, this is C++ library for 2D & 3D graphics plus loads of other useful things for games: audio, physics, file format import, ...
2. No, you can build one with [Dear ImGui](https://github.com/ocornut/imgui), for example, though. That's what I'm doing.
3. There are no 3D model or animation files as "standard assets", if that is what you mean. But magnum can load pretty much any 3D file format, so if you have 3D assets, magnum can load models and animation from those.

A good place to get started is [magnum-examples](https://github.com/mosra/magnum-examples).

**Comment by Joe23232** [comment]
> Welcome to Magnum :)

Thank you mate :)

> Yes, this is C++ library for 2D & 3D graphics plus loads of other useful things for games: audio, physics, file format import

Oh that is nice.

> No, you can build one with Dear ImGui, for example, though. That's what I'm doing.

Is it ready for use? I am looking at the screenshots, but I am a bit confused, is this going to function in a similar manner as with Godot? So for example I can move any objects around using the GUI program that you made like I can with Godot or even with Unity?

Is there another project that allows you to use Blender as a GUI game editor (kinda like Armory3D)? (not trying to say your project is bad or anything, I am just most familiar with Blender).

> But magnum can load pretty much any 3D file format, so if you have 3D assets, magnum can load models and animation from those.

Oh nice so that means does it also support animations that I created with Blender?

> A good place to get started is magnum-examples.

Is the C++ code just as easy to use as with Unity C#?

**Comment by pezcode** [comment]
Maybe to clarify: Magnum is not a game engine. Think of it as a library that lets you build your own game engine with blood and sweat. If you're looking for out-of-the-box scene editor, scripting, physics after clicking a checkbox, etc... an actual
 game engine like Godot/Unreal/Unity will be better suited.

**Comment by Joe23232** [comment]
Hi man, yes I am well aware, but I mean about your ImGui project am I able
to use it like a Godot game editor?

**Comment by mosra** [comment]
Hi, thanks for your interest in this project! 

If you're not sure it's a good fit for what you want to do, this short guide might help: https://magnum.graphics/is-magnum-what-i-am-looking-for/
