### ISSUE TITLE
fail to link magnum-based static lib on iOS platform

### ISSUE THREAD

**Issue by linuxaged** [mosra/magnum#487]
Have been caught in this trap for two days, so i create another issue to ask for help 😂

0. Prepare API:

        // Api.h
        #ifdef __cplusplus
        extern "C"{
        #endif
            void BonApi_init(int width, int height);
            void BonApi_draw();
        #ifdef __cplusplus
        }
        #endif

        // Api.cpp
        namespace Magnum {
            namespace Examples {
                using namespace Math::Literals;
                class MouseInteractionExample {
                public:
                    void drawEvent();
                };
                // class impl leaved out
            }
        }

        Magnum::Examples::MouseInteractionExample* app{};

        void BonApi_init(int width, int height) {
            if(app)
                delete app;
            app = new Magnum::Examples::MouseInteractionExample(width, height);
        }

        void BonApi_draw() {
            if(app)
                app->drawEvent();
        }

1. Use CMake generate Xcode framework project:

        project(BonViewer)

        add_library(${PROJECT_NAME} STATIC
            ${Source_Common}
            API.cpp
        )
        set_target_properties(${PROJECT_NAME} PROPERTIES
            FRAMEWORK TRUE
            MACOSX_FRAMEWORK_IDENTIFIER com.bonsmile.bonviewersdk
            MACOSX_FRAMEWORK_INFO_PLIST ${CMAKE_CURRENT_SOURCE_DIR}/Info.plist
            # "current version" in semantic format in Mach-O binary file
            VERSION 16.4.0
            # "compatibility version" in semantic format in Mach-O binary file
            SOVERSION 1.0.0
            PUBLIC_HEADER API.h
            XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY "iPhone Developer"
        )

        target_link_libraries(${PROJECT_NAME} PUBLIC
            Corrade::Utility
            Magnum::Magnum
            Magnum::Trade
            Magnum::GL
            Magnum::MeshTools
            Magnum::Primitives
            Magnum::SceneGraph
            Magnum::Shaders
            MagnumIntegration::ImGui
        )

2. Create an empty iOS app then call `BonApi_init` in `ViewController.m` and add BonViewer lib project as reference project.

3. Build the app project and errors show up:

        Ld /Users/jjj/Library/Developer/Xcode/DerivedData/HelloWorld-dgqyixvttaebrcdxwmzkfmdboffh/Build/Products/Debug-iphoneos/HelloWorld.app/HelloWorld normal (in target 'HelloWorld' from project 'HelloWorld')
            cd /Users/jjj/workspace/HelloWorld/HelloWorld
            /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target arm64-apple-ios14.2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.2.sdk -L/Users/jjj/Library/Developer/Xcode/DerivedData/HelloWorld-dgqyixvttaebrcdxwmzkfmdboffh/Build/Products/Debug-iphoneos -F/Users/jjj/Library/Developer/Xcode/DerivedData/HelloWorld-dgqyixvttaebrcdxwmzkfmdboffh/Build/Products/Debug-iphoneos -filelist /Users/jjj/Library/Developer/Xcode/DerivedData/HelloWorld-dgqyixvttaebrcdxwmzkfmdboffh/Build/Intermediates.noindex/HelloWorld.build/Debug-iphoneos/HelloWorld.build/Objects-normal/arm64/HelloWorld.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/jjj/Library/Developer/Xcode/DerivedData/HelloWorld-dgqyixvttaebrcdxwmzkfmdboffh/Build/Intermediates.noindex/HelloWorld.build/Debug-iphoneos/HelloWorld.build/Objects-normal/arm64/HelloWorld_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -fembed-bitcode-marker -fobjc-arc -fobjc-link-runtime /Users/jjj/Library/Developer/Xcode/DerivedData/HelloWorld-dgqyixvttaebrcdxwmzkfmdboffh/Build/Products/Debug-iphoneos/BonViewer.framework/BonViewer -Xlinker -no_adhoc_codesign -Xlinker -dependency_info -Xlinker /Users/jjj/Library/Developer/Xcode/DerivedData/HelloWorld-dgqyixvttaebrcdxwmzkfmdboffh/Build/Intermediates.noindex/HelloWorld.build/Debug-iphoneos/HelloWorld.build/Objects-normal/arm64/HelloWorld_dependency_info.dat -o /Users/jjj/Library/Developer/Xcode/DerivedData/HelloWorld-dgqyixvttaebrcdxwmzkfmdboffh/Build/Products/Debug-iphoneos/HelloWorld.app/HelloWorld

        Undefined symbols for architecture arm64:
        "Magnum::SceneGraph::Object<Magnum::SceneGraph::BasicMatrixTransformation3D<float> >::doParent()", referenced from:
            vtable for Magnum::SceneGraph::Scene<Magnum::SceneGraph::BasicMatrixTransformation3D<float> > in BonViewer(AppAndroid.o)
        "Magnum::GL::Buffer::~Buffer()", referenced from:
            bon::Grid::~Grid() in BonViewer(AppAndroid.o)
            OVR::TextRenderer::~TextRenderer() in BonViewer(BitmapFont.o)
        "Magnum::GL::AbstractTexture::~AbstractTexture()", referenced from:
            Magnum::GL::Texture<2u>::~Texture() in BonViewer(AppAndroid.o)
        "Magnum::SceneGraph::Object<Magnum::SceneGraph::BasicMatrixTransformation3D<float> >::doTransformationMatrices(std::__1::vector<std::__1::reference_wrapper<Magnum::SceneGraph::AbstractObject<3u, float> >, std::__1::allocator<std::__1::reference_wrapper<Magnum::SceneGraph::AbstractObject<3u, float> > > > const&, Magnum::Math::Matrix4<float> const&) const", referenced from:
            vtable for Magnum::SceneGraph::Scene<Magnum::SceneGraph::BasicMatrixTransformation3D<float> > in BonViewer(AppAndroid.o)
        "Magnum::GL::Mesh::~Mesh()", referenced from:
            std::__1::allocator<Magnum::GL::Mesh>::destroy(Magnum::GL::Mesh*) in BonViewer(AppAndroid.o)
            bon::Grid::~Grid() in BonViewer(AppAndroid.o)
            OVR::TextRenderer::~TextRenderer() in BonViewer(BitmapFont.o)
        "Magnum::GL::Renderbuffer::~Renderbuffer()", referenced from:
            bon::Renderer::~Renderer() in BonViewer(AppAndroid.o)
        "operator delete[](void*)", referenced from:
            Corrade::Containers::Implementation::CallDeleter<Corrade::Containers::Array<char, void (*)(char*, unsigned long)>, void (*)(Corrade::Containers::Array<char, void (*)(char*, unsigned long)>*, unsigned long)>::operator()(void (*)(Corrade::Containers::Array<char, void (*)(char*, unsigned long)>*, unsigned long), Corrade::Containers::Array<char, void (*)(char*, unsigned long)>*, unsigned long) const in BonViewer(AppAndroid.o)
            Corrade::Containers::Implementation::CallDeleter<int, void (*)(int*, unsigned long)>::operator()(void (*)(int*, unsigned long), int*, unsigned long) const in BonViewer(AppAndroid.o)
            Corrade::Containers::Implementation::CallDeleter<Corrade::Containers::Pointer<bon::Renderer>, void (*)(Corrade::Containers::Pointer<bon::Renderer>*, unsigned long)>::operator()(void (*)(Corrade::Containers::Pointer<bon::Renderer>*, unsigned long), Corrade::Containers::Pointer<bon::Renderer>*, unsigned long) const in BonViewer(AppAndroid.o)
            Corrade::Containers::Implementation::CallDeleter<Magnum::Math::Vector3<float>, void (*)(Magnum::Math::Vector3<float>*, unsigned long)>::operator()(void (*)(Magnum::Math::Vector3<float>*, unsigned long), Magnum::Math::Vector3<float>*, unsigned long) const in BonViewer(AppAndroid.o)
            Corrade::Containers::Implementation::CallDeleter<Magnum::Math::Color4<float>, void (*)(Magnum::Math::Color4<float>*, unsigned long)>::operator()(void (*)(Magnum::Math::Color4<float>*, unsigned long), Magnum::Math::Color4<float>*, unsigned long) const in BonViewer(AppAndroid.o)
            Corrade::Containers::Implementation::CallDeleter<bon::Renderer::ShaderParam, void (*)(bon::Renderer::ShaderParam*, unsigned long)>::operator()(void (*)(bon::Renderer::ShaderParam*, unsigned long), bon::Renderer::ShaderParam*, unsigned long) const in BonViewer(AppAndroid.o)
            Corrade::Containers::Implementation::CallDeleter<PhongShader, void (*)(PhongShader*, unsigned long)>::operator()(void (*)(PhongShader*, unsigned long), PhongShader*, unsigned long) const in BonViewer(AppAndroid.o)
            ...
        "Corrade::Utility::Error::defaultOutput()", referenced from:
            Magnum::Math::Matrix4<float>::rotation(Magnum::Math::Rad<float>, Magnum::Math::Vector3<float> const&) in BonViewer(AppAndroid.o)
            Corrade::Containers::LinkedList<Magnum::SceneGraph::Object<Magnum::SceneGraph::BasicMatrixTransformation3D<float> > >::cut(Magnum::SceneGraph::Object<Magnum::SceneGraph::BasicMatrixTransformation3D<float> >*) in BonViewer(AppAndroid.o)
        "Magnum::SceneGraph::AbstractFeatureGroup<3u, float>::~AbstractFeatureGroup()", referenced from:
            Magnum::SceneGraph::FeatureGroup<3u, Magnum::SceneGraph::Drawable<3u, float>, float>::~FeatureGroup() in BonViewer(AppAndroid.o)
        "Magnum::GL::Framebuffer::~Framebuffer()", referenced from:
            bon::Renderer::~Renderer() in BonViewer(AppAndroid.o)
        "Corrade::Utility::Debug& Magnum::Math::operator<<<3ul, float>(Corrade::Utility::Debug&, Magnum::Math::Vector<3ul, float> const&)", referenced from:
            Magnum::Math::Matrix4<float>::rotation(Magnum::Math::Rad<float>, Magnum::Math::Vector3<float> const&) in BonViewer(AppAndroid.o)
        "Corrade::Utility::Error::~Error()", referenced from:
            Magnum::Math::Matrix4<float>::rotation(Magnum::Math::Rad<float>, Magnum::Math::Vector3<float> const&) in BonViewer(AppAndroid.o)
            Corrade::Containers::LinkedList<Magnum::SceneGraph::Object<Magnum::SceneGraph::BasicMatrixTransformation3D<float> > >::cut(Magnum::SceneGraph::Object<Magnum::SceneGraph::BasicMatrixTransformation3D<float> >*) in BonViewer(AppAndroid.o)
        "Magnum::SceneGraph::BasicMatrixTransformation3D<float>::rotateLocal(Magnum::Math::Quaternion<float> const&)", referenced from:
            Magnum::SceneGraph::BasicMatrixTransformation3D<float>::doRotateLocal(Magnum::Math::Quaternion<float> const&) in BonViewer(AppAndroid.o)
        "operator new[](unsigned long)", referenced from:
            Corrade::Containers::Array<Corrade::Containers::Pointer<bon::Renderer>, void (*)(Corrade::Containers::Pointer<bon::Renderer>*, unsigned long)>::Array(Corrade::Containers::ValueInitT, unsigned long) in BonViewer(AppAndroid.o)
            Corrade::Containers::Array<int, void (*)(int*, unsigned long)>::Array(Corrade::Containers::ValueInitT, unsigned long) in BonViewer(AppAndroid.o)
            Corrade::Containers::Array<Corrade::Containers::Array<char, void (*)(char*, unsigned long)>, void (*)(Corrade::Containers::Array<char, void (*)(char*, unsigned long)>*, unsigned long)>::Array(Corrade::Containers::DefaultInitT, unsigned long) in BonViewer(AppAndroid.o)
        "Magnum::SceneGraph::BasicMatrixTransformation3D<float>::rotate(Magnum::Math::Quaternion<float> const&)", referenced from:
            Magnum::SceneGraph::BasicMatrixTransformation3D<float>::doRotate(Magnum::Math::Quaternion<float> const&) in BonViewer(AppAndroid.o)
        "Magnum::ImGuiIntegration::Context::~Context()", referenced from:
            Magnum::Examples::MouseInteractionExample::MouseInteractionExample(int, int) in BonViewer(AppAndroid.o)
            Magnum::Examples::MouseInteractionExample::~MouseInteractionExample() in BonViewer(AppAndroid.o)
        "Magnum::SceneGraph::Object<Magnum::SceneGraph::BasicMatrixTransformation3D<float> >::Object(Magnum::SceneGraph::Object<Magnum::SceneGraph::BasicMatrixTransformation3D<float> >*)", referenced from:
            Magnum::SceneGraph::Scene<Magnum::SceneGraph::BasicMatrixTransformation3D<float> >::Scene() in BonViewer(AppAndroid.o)
        "Magnum::GL::Context::Context(Magnum::NoCreateT, int, char const**, void (*)(Magnum::GL::Context&))", referenced from:
            Magnum::Platform::GLContext::GLContext(Magnum::NoCreateT, int, char const**) in BonViewer(AppAndroid.o)
        "Magnum::SceneGraph::Object<Magnum::SceneGraph::BasicMatrixTransformation3D<float> >::~Object()", referenced from:
            Magnum::SceneGraph::Scene<Magnum::SceneGraph::BasicMatrixTransformation3D<float> >::~Scene() in BonViewer(AppAndroid.o)
        "Magnum::SceneGraph::Object<Magnum::SceneGraph::BasicMatrixTransformation3D<float> >::setClean()", referenced from:
            Magnum::SceneGraph::Object<Magnum::SceneGraph::BasicMatrixTransformation3D<float> >::doSetClean() in BonViewer(AppAndroid.o)
        "Magnum::GL::Context::create()", referenced from:
            Magnum::Platform::GLContext::create() in BonViewer(AppAndroid.o)
        "Magnum::GL::Context::~Context()", referenced from:
            Magnum::Platform::GLContext::~GLContext() in BonViewer(AppAndroid.o)
        "Magnum::ImGuiIntegration::Context::Context(Magnum::NoCreateT)", referenced from:
            Magnum::Examples::MouseInteractionExample::MouseInteractionExample(int, int) in BonViewer(AppAndroid.o)
        "ImGui::CreateContext(ImFontAtlas*)", referenced from:
            Magnum::Examples::MouseInteractionExample::MouseInteractionExample(int, int) in BonViewer(AppAndroid.o)
        "Corrade::Utility::Debug::Debug(Corrade::Containers::EnumSet<Corrade::Utility::Debug::Flag, (unsigned char)255>)", referenced from:
            Magnum::Examples::MouseInteractionExample::MouseInteractionExample(int, int) in BonViewer(AppAndroid.o)
        "operator new(unsigned long)", referenced from:
            _BonApi_init in BonViewer(AppAndroid.o)
        "Magnum::SceneGraph::Object<Magnum::SceneGraph::BasicMatrixTransformation3D<float> >::doParent() const", referenced from:
            vtable for Magnum::SceneGraph::Scene<Magnum::SceneGraph::BasicMatrixTransformation3D<float> > in BonViewer(AppAndroid.o)
        "Corrade::Utility::Debug::~Debug()", referenced from:
            Magnum::Examples::MouseInteractionExample::MouseInteractionExample(int, int) in BonViewer(AppAndroid.o)
        "Corrade::Utility::Debug::operator<<(int)", referenced from:
            Magnum::Examples::MouseInteractionExample::MouseInteractionExample(int, int) in BonViewer(AppAndroid.o)
        "Magnum::ImGuiIntegration::Context::Context(ImGuiContext&, Magnum::Math::Vector2<float> const&, Magnum::Math::Vector2<int> const&, Magnum::Math::Vector2<int> const&)", referenced from:
            Magnum::Examples::MouseInteractionExample::MouseInteractionExample(int, int) in BonViewer(AppAndroid.o)
        "Magnum::SceneGraph::Object<Magnum::SceneGraph::BasicMatrixTransformation3D<float> >::doScene() const", referenced from:
            vtable for Magnum::SceneGraph::Scene<Magnum::SceneGraph::BasicMatrixTransformation3D<float> > in BonViewer(AppAndroid.o)
        "Magnum::SceneGraph::Object<Magnum::SceneGraph::BasicMatrixTransformation3D<float> >::doSetClean(std::__1::vector<std::__1::reference_wrapper<Magnum::SceneGraph::AbstractObject<3u, float> >, std::__1::allocator<std::__1::reference_wrapper<Magnum::SceneGraph::AbstractObject<3u, float> > > > const&)", referenced from:
            vtable for Magnum::SceneGraph::Scene<Magnum::SceneGraph::BasicMatrixTransformation3D<float> > in BonViewer(AppAndroid.o)
        "Corrade::Utility::Debug::operator<<(char const*)", referenced from:
            Magnum::Examples::MouseInteractionExample::MouseInteractionExample(int, int) in BonViewer(AppAndroid.o)
            Magnum::Math::Matrix4<float>::rotation(Magnum::Math::Rad<float>, Magnum::Math::Vector3<float> const&) in BonViewer(AppAndroid.o)
            Corrade::Containers::LinkedList<Magnum::SceneGraph::Object<Magnum::SceneGraph::BasicMatrixTransformation3D<float> > >::cut(Magnum::SceneGraph::Object<Magnum::SceneGraph::BasicMatrixTransformation3D<float> >*) in BonViewer(AppAndroid.o)
        "Magnum::GL::AbstractShaderProgram::~AbstractShaderProgram()", referenced from:
            Magnum::Shaders::VertexColor<3u>::~VertexColor() in BonViewer(AppAndroid.o)
            PhongShader::~PhongShader() in BonViewer(AppAndroid.o)
            GridShader::~GridShader() in BonViewer(AppAndroid.o)
            SdfShader::~SdfShader() in BonViewer(BitmapFont.o)
        "_flextGLInit", referenced from:
            Magnum::Platform::GLContext::GLContext(Magnum::NoCreateT, int, char const**) in BonViewer(AppAndroid.o)
        "Magnum::GL::Renderbuffer::maxSamples()", referenced from:
            Magnum::Examples::MouseInteractionExample::MouseInteractionExample(int, int) in BonViewer(AppAndroid.o)
        "operator delete(void*)", referenced from:
            _BonApi_init in BonViewer(AppAndroid.o)
            Magnum::SceneGraph::Scene<Magnum::SceneGraph::BasicMatrixTransformation3D<float> >::~Scene() in BonViewer(AppAndroid.o)
            Corrade::Containers::Pointer<bon::Renderer>::~Pointer() in BonViewer(AppAndroid.o)
            Corrade::Containers::Pointer<OVR::TextRenderer>::~Pointer() in BonViewer(AppAndroid.o)
            std::__1::_DeallocateCaller::__do_call(void*) in BonViewer(AppAndroid.o)
            Magnum::SceneGraph::FeatureGroup<3u, Magnum::SceneGraph::Drawable<3u, float>, float>::~FeatureGroup() in BonViewer(AppAndroid.o)
        "ImFontConfig::ImFontConfig()", referenced from:
            Magnum::Examples::MouseInteractionExample::MouseInteractionExample(int, int) in BonViewer(AppAndroid.o)
        "ImGui::GetIO()", referenced from:
            Magnum::Examples::MouseInteractionExample::MouseInteractionExample(int, int) in BonViewer(AppAndroid.o)
        "ImGui::GetCurrentContext()", referenced from:
            Magnum::Examples::MouseInteractionExample::MouseInteractionExample(int, int) in BonViewer(AppAndroid.o)
        "Magnum::SceneGraph::Object<Magnum::SceneGraph::BasicMatrixTransformation3D<float> >::setDirty()", referenced from:
            Magnum::SceneGraph::Object<Magnum::SceneGraph::BasicMatrixTransformation3D<float> >::doSetDirty() in BonViewer(AppAndroid.o)
            Magnum::SceneGraph::BasicMatrixTransformation3D<float>::setTransformation(Magnum::Math::Matrix4<float> const&) in BonViewer(AppAndroid.o)
        "Magnum::ImGuiIntegration::Context::operator=(Magnum::ImGuiIntegration::Context&&)", referenced from:
            Magnum::Examples::MouseInteractionExample::MouseInteractionExample(int, int) in BonViewer(AppAndroid.o)
        "Magnum::SceneGraph::Object<Magnum::SceneGraph::BasicMatrixTransformation3D<float> >::doScene()", referenced from:
            vtable for Magnum::SceneGraph::Scene<Magnum::SceneGraph::BasicMatrixTransformation3D<float> > in BonViewer(AppAndroid.o)
        "Corrade::Utility::Error::Error(std::__1::basic_ostream<char, std::__1::char_traits<char> >*, Corrade::Containers::EnumSet<Corrade::Utility::Debug::Flag, (unsigned char)255>)", referenced from:
            Magnum::Math::Matrix4<float>::rotation(Magnum::Math::Rad<float>, Magnum::Math::Vector3<float> const&) in BonViewer(AppAndroid.o)
            Corrade::Containers::LinkedList<Magnum::SceneGraph::Object<Magnum::SceneGraph::BasicMatrixTransformation3D<float> > >::cut(Magnum::SceneGraph::Object<Magnum::SceneGraph::BasicMatrixTransformation3D<float> >*) in BonViewer(AppAndroid.o)
        "Magnum::SceneGraph::Object<Magnum::SceneGraph::BasicMatrixTransformation3D<float> >::absoluteTransformation() const", referenced from:
            Magnum::SceneGraph::Object<Magnum::SceneGraph::BasicMatrixTransformation3D<float> >::absoluteTransformationMatrix() const in BonViewer(AppAndroid.o)
        "Magnum::ImGuiIntegration::Context::relayout(Magnum::Math::Vector2<int> const&)", referenced from:
            Magnum::Examples::MouseInteractionExample::MouseInteractionExample(int, int) in BonViewer(AppAndroid.o)
        ld: symbol(s) not found for architecture arm64
        clang: error: linker command failed with exit code 1 (use -v to see invocation)

Shouldn't the Magnum class and method have been renamed after compiling(name mangling)? why the linker try to find method like `Magnum::SceneGraph::Object<Magnum::SceneGraph::BasicMatrixTransformation3D<float> >::doParent()`?
Have also tried take `ViewController.m` as Objective-C++ source, but not working either 🤷‍♂️

**Comment by linuxaged** [comment]
Symbols in `BonViewer`: [symbols.txt](https://gist.github.com/linuxaged/a63822f67c93b55978112833f3549e73)

**Comment by mosra** [comment]
I think we could still solve this one on Gitter, because this doesn't seem like Magnum is at fault ;)

> Create an empty iOS app then call BonApi_init in ViewController.m and add BonViewer lib project as reference project.

And that's the problem, I think Even though you link the libraries in CMake, the concept of static libraries (unlike dynamic) has no way to represent dependencies on external libraries. In CMake the information from `target_link_libraries()` is used only for transitive dependencies -- if you later *in CMake* link the static target to some dynamic library or executable, it will remember these dependencies and link them as well. 

If you however take the `*.a` as a file and add it to a new project (either in Xcode, or even in another CMake project that doesn't know anything about the original `target_link_libraries()` call), none of this dependency info is known anymore, similarly as corresponding include paths are not known and you have to add them by hand as well. I don't know how "reference projects" work in Xcode, but as far as I see from the linker command line, they don't seem to pass through the static depenencies either.

> Shouldn't the Magnum class and method have been renamed after compiling(name mangling)?

Yes, they are, but the linker is helpfully demangling them for you again in the error message so you don't have to suffer :)

**Comment by linuxaged** [comment]
Now i have integrated the BonViewer with `add_subdirectory(../bonviewer/src bonviewer)`, above link errors seem disapear but there's two new link errors:

	Undefined symbols for architecture arm64:
	  "ImGui::TableSettingsInstallHandler(ImGuiContext*)", referenced from:
	      ImGui::Initialize(ImGuiContext*) in libMagnumImGuiIntegration.a(imgui.o)
	  "_flextGLInit", referenced from:
	      Magnum::Platform::GLContext::GLContext(Magnum::NoCreateT, int, char const**) in libBonViewer.a(AppAndroid.o)
	ld: symbol(s) not found for architecture arm64

Magnum v2020.06 being used, i will try the master.

**Comment by mosra** [comment]
This is `Magnum::EglContext` missing, I think. Add it to that `target_link_libraries()` call :)
