### ISSUE TITLE
Example usage of magnum-fontconverter fails with error "PluginManager::Manager::load(): unresolved dependency TgaImageConverter of plugin MagnumFontConverter"

### ISSUE THREAD

**Issue by fgoujeon** [mosra/magnum#489]
The command `magnum-fontconverter --font FreeTypeFont --converter MagnumFontConverter DejaVuSans.ttf myfont` fails with error `PluginManager::Manager::load(): unresolved dependency TgaImageConverter of plugin MagnumFontConverter`.

I'm using magnum-plugins 2019.10-1 from Arch Linux.

**Comment by mosra** [comment]
Whoops, I forgot to update this tool since shared mutable manager state got removed in mosra/corrade@e6f65387158f27d7474d629f025376118af3b3ac. Should be fixed in 1f37032990618bfcd0279d631c7d4507f4749c82, thanks for the report!
