### ISSUE TITLE
Errors in PhongShader inline documentation

### ISSUE THREAD

**Issue by Innokentiy-Alaytsev** [mosra/magnum#492]
I've spotted two errors in `PhongShader` inline documentation:
* [setLightColor()](https://github.com/mosra/magnum/blob/3d136503d8a959b4c260b9b60ca925566cc9d095/src/Magnum/Shaders/Phong.h#L920) function documentation says about position.
* [setLightSpecularColor()](https://github.com/mosra/magnum/blob/3d136503d8a959b4c260b9b60ca925566cc9d095/src/Magnum/Shaders/Phong.h#L970) function documentation says about position.

**Comment by mosra** [comment]
Small things that matter. Fixed in beecb8fb82e74e42149a17903cd0f2a387d21e20, thank you!
