### ISSUE TITLE
Homebrew magnum-plugins install fails

### ISSUE THREAD

**Issue by Osurac529** [mosra/magnum#497]
Hi,

macOS 10.15.7

I tried installing the magnum-plugins using homebrew after successfully installing magnum itself.

mcaruso@Mikes-MBP ~ %  brew install mosra/magnum/magnum-plugins
==> Installing magnum-plugins from mosra/magnum
==> Downloading https://github.com/mosra/magnum-plugins/archive/v2020.06.tar.gz
Already downloaded: /Users/mcaruso/Library/Caches/Homebrew/downloads/5fc3c0f3a7416030b4b7069404db05f804d6fe06c3c0113e25dd770b9988addd--magnum-plugins-2020.06.tar.gz
==> curl -L https://github.com/BinomialLLC/basis_universal/archive/2f43afcc97d0a5dafdb73b4e24e123cf9687a418.tar.gz -o
==> mkdir basis-universal
==> tar xzvf basis-universal.tar.gz -C basis-universal --strip-components=1
==> curl -L https://github.com/zeux/meshoptimizer/archive/97c52415c6d29f297a76482ddde22f739292446d.tar.gz -o src/exte
==> mkdir meshoptimizer
==> tar xzvf meshoptimizer.tar.gz -C meshoptimizer --strip-components=1
==> mkdir build
==> cmake -DWITH_ASSIMPIMPORTER=ON -DWITH_BASISIMAGECONVERTER=ON -DWITH_BASISIMPORTER=ON -DWITH_DDSIMPORTER=ON -DWITH
Last 15 lines from /Users/mcaruso/Library/Logs/Homebrew/magnum-plugins/08.cmake:
-- LIB_SUFFIX variable is not defined. It will be autodetected now.
-- You can set it manually with -DLIB_SUFFIX=<value> (64 for example)
-- LIB_SUFFIX autodetected as '', libraries will be installed into /usr/local/Cellar/magnum-plugins/2020.06/lib
-- Found Git: /usr/local/bin/git (found version "2.28.0") 
-- Found Corrade: /usr/local/include  found components: Containers rc Utility PluginManager 
CMake Error at /usr/local/Cellar/cmake/3.19.6/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
  Could NOT find Magnum (missing: AnyImageImporter)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.19.6/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:582 (_FPHSA_FAILURE_MESSAGE)
  modules/FindMagnum.cmake:1006 (find_package_handle_standard_args)
  src/MagnumPlugins/AssimpImporter/CMakeLists.txt:27 (find_package)

-- Configuring incomplete, errors occurred!
See also "/tmp/magnum-plugins-20210224-9827-bz59j/magnum-plugins-2020.06/build/CMakeFiles/CMakeOutput.log".

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/mosra/homebrew-magnum/issues

**Comment by mosra** [comment]
Strange. I just tested here and it worked. 

Although I had to `brew link --overwrite magnum` because I have a custom build installed into `/usr/local`... so maybe you have a similar case of a barebones Magnum installed by hand to `/usr/local` and then Homebrew refused to overwrite that when installing magnum?

If that's not the case, can you check what's in `/usr/local/Cellar/magnum/2020.06/lib/magnum/importers/` and what's in `/usr/local/lib/magnum/importers/`? Those should contain the same files if everything went alright, and `AnyImageImporter.so` should be among them.

**Comment by Osurac529** [comment]
Yes I was running into some issues prior to this I did clone magnum and build and install it. And actually I installed it incorrectly to /usr/local/bin, oops when I set the PREFIX during cmake. It didnt look like there was an uninstall target for the make file so I manually removed what I could from /usr/local/bin. 

 ls /usr/local/Cellar/magnum/2020.06/lib/magnum/importers/ 
AnyImageImporter.conf AnySceneImporter.conf ObjImporter.conf      TgaImporter.conf
AnyImageImporter.so   AnySceneImporter.so   ObjImporter.so        TgaImporter.so

ls /usr/local/lib/magnum/importers/
ls: /usr/local/lib/magnum/importers/: No such file or directory

**Comment by Osurac529** [comment]
`brew link --overwrite magnum` worked! Thank you!

**Comment by mosra** [comment]
Glad this got solved so quickly :)
