### ISSUE TITLE
EmscriptenApplication: powerPreference default is not supported

### ISSUE THREAD

**Issue by Squareys** [mosra/magnum#500]
Hi all,

in WebGL, there is the option to set powerPreference to prefer high performance or low power consumption, _or default_.
The final value is currently not supported [in EmscriptenApplication](https://github.com/mosra/magnum/blob/master/src/Magnum/Platform/EmscriptenApplication.cpp#L372-L374), but [is supported in emscripten](https://emscripten.org/docs/api_reference/html5.h.html#c.EmscriptenWebGLContextAttributes.powerPreference).

There might be usecases where letting the User Agent (Browser) choose the power preference is wanted.

Best,
Jonathan

**Comment by mosra** [comment]
Ah I thought this was a PR already :)

I'd say having flags `Flag::PowerPreferenceLowPower` and `Flag::PowerPreferenceHighPerformance` would make sense, and the default would be if neither is chosen. And keeping the old one, annotated as deprecated, for backwards compatibility.

**Comment by mosra** [comment]
Implemented in e9c44739f2a89b49816b4cae5334705a01c6e15e.
