### ISSUE TITLE
proposal to make magnum game engine

### ISSUE THREAD

**Issue by drcucaracha** [mosra/magnum#502]
hello, the idea would be to make magnum a video game engine that would basically be the core of magnum in a ui an executable and
the extensions could be dll that people could download according to what they need them keeping the kernel without
changes and easier to find errors in case you have them and making the engine very modular
I know it seems like a titanic task but looking at the magnum examples it has a lot of potential and I am sure that having a small executable that has
basic things will attract a lot of public nothing is impossible so blender and godot started with little things that people could try without knowing much about programming
With the subject of scripting in my opinion it would be good if you could use c ++ and python since you do not have to learn a new language and python has many
Biblitecas with a section of addons like that of blender where people can create their addons and upload or share them, with this I do not mean that
magnum disappears as liberia but it could be done in a new branch of github and that the community and people contribute to the project
the three strengths that an engine must have are 1- the quality, which magnum already has 2- easy to use (that's why I said python and c ++) 3- good performance
if more than say I attack who reads this :)

**Comment by alkavan** [comment]
It took over 10 years to develop magnum ... I'm just saying, this is not something that would take a month or two. And also I'm not sure what you exactly mean "engine" ... like UE or CryEngine? this kind of interface? or just code components?

I would love to see magnum getting more game systems, but also I would start small. Just one such system, no interface...

Do you know what would be really cool to have?
[ECS](https://en.wikipedia.org/wiki/Entity_component_system) module for Magnum. That can really ease some game development. Something with good and easy-to-use architectural design.

And also would focus on C++ as Magnum does.
And as for bindings, I would actually suggest [Lua](http://www.lua.org/)!
This language is made for this job, and also simpler and more elegant than Python IMHO.

**Comment by drcucaracha** [comment]
hello to interface I mean to have a window already compiled with some options for its use
as for lua I would prefer python since addons could be made easily added characteristics as the blender is made
and the logic I think is easier to integrate there without mentioning that it could be optimized if the python code is translated to c ++
I suppose it would be easier with an existing library and the possibility of integrating machin lerning as a pro example openai that
It is already written in python, the idea behind all this is to make an attractive product for any public that does not know how to compile or does not work with libraries
increasing the popularity of magnum both by curious people and new contributors which would be good for the project in my humble opinion

**Comment by mosra** [comment]
Closing as having an UI and a non-programmer-friendly WYSIWYG editor is out of scope of this project. Magnum itself is a middleware to build actual game engines (or apps) on.

If you want an editor, check out the Magnum-based [Wonderland Engine](https://wonderlandengine.com/) or ... Godot, for example.
