### ISSUE TITLE
How to install .conf files?

### ISSUE THREAD

**Issue by Osurac529** [mosra/magnum#503]
Hi I am using magnum and magnumplugins as a cmake sub project using the add_subdirectory approach and not building statically. So far things are going pretty well. I am installing the magnum plugins like this for example since they are exclude_from_all:

install(TARGETS AnySceneImporter LIBRARY DESTINATION lib/magnum/importers)

However the corresponding .conf file AnySceneImporter.conf does not get installed along side the shared object? How can I install the .conf file too?

When the .conf is not present in the install destination this runtime error happens:
PluginManager::Manager::load(): plugin AnySceneImporter is not ready to load: PluginManager::LoadState::WrongMetadataFile

Thanks

**Comment by Osurac529** [comment]
My original problem was I did not have success with the static build of Magnum and MagnumPlugins, well it turns out I need that to work because one of my supported platforms is android and Magnum only works statically on android. 

This is what I have to bring Corrade, Magnum and MagnumPlugins into my cmake project:

```
set(MAGNUM_VERSION "v2020.06")
set(BUILD_STATIC ON CACHE BOOL "" FORCE)
set(BUILD_PLUGINS_STATIC ON CACHE BOOL "" FORCE)

include(FetchContent)
FetchContent_Declare(
  Corrade
  GIT_REPOSITORY git@github.com:mosra/corrade.git
  GIT_TAG        ${MAGNUM_VERSION}
)
FetchContent_MakeAvailable(Corrade)

FetchContent_Declare(
  Magnum
  GIT_REPOSITORY git@github.com:mosra/magnum.git
  GIT_TAG        ${MAGNUM_VERSION}
)
if(ANDROID)
  set(WITH_WINDOWLESSEGLAPPLICATION ON CACHE BOOL "" FORCE)
  set(TARGET_GLES2 OFF CACHE BOOL "" FORCE)
elseif(APPLE)
  set(WITH_WINDOWLESSCGLAPPLICATION ON CACHE BOOL "" FORCE)
elseif(UNIX)
  set(WITH_WINDOWLESSGLXAPPLICATION ON CACHE BOOL "" FORCE)
endif()
set(WITH_ANYIMAGEIMPORTER ON CACHE BOOL "" FORCE)
set(WITH_ANYSCENEIMPORTER ON CACHE BOOL "" FORCE)
FetchContent_MakeAvailable(Magnum)

FetchContent_Declare(
  MagnumPlugins
  GIT_REPOSITORY git@github.com:mosra/magnum-plugins.git
  GIT_TAG        ${MAGNUM_VERSION}
)
#set(WITH_ASSIMPIMPORTER ON CACHE BOOL "" FORCE)
set(WITH_TINYGLTFIMPORTER ON CACHE BOOL "" FORCE)
set(WITH_JPEGIMPORTER ON CACHE BOOL "" FORCE)
set(WITH_PNGIMPORTER ON CACHE BOOL "" FORCE)
FetchContent_MakeAvailable(MagnumPlugins)
```

That seems to be working. Then in my application I have:

```
find_package(MagnumPlugins REQUIRED
    TinyGltfImporter
    JpegImporter
    PngImporter)
    
find_package(
  Magnum REQUIRED
    GL
    MeshTools
    SceneGraph
    Trade
    Shaders
    DebugTools
    AnyImageImporter
    AnySceneImporter
    ${PLATFORM_COMPONENT})

if(NOT Magnum_FOUND)
  message(
    STATUS "Couldn't find magnum, not building snapshot ${PLATFORM_COMPONENT}")
  return()
endif()

find_package(Glog REQUIRED)
find_package(gflags REQUIRED)
find_package(Boost REQUIRED COMPONENTS filesystem)
find_package(Eigen REQUIRED)

# set_directory_properties(PROPERTIES CORRADE_USE_PEDANTIC_FLAGS ON)

file(GLOB_RECURSE SOURCES src/*.hpp src/*.cpp include/*.hpp)
add_library(render ${SOURCES})

target_include_directories(render PUBLIC include)
target_link_libraries(
  render
  PUBLIC image
         Eigen3::Eigen
         Magnum::WindowlessApplication
         Magnum::GL
         Magnum::Magnum
         Magnum::Trade
         Magnum::MeshTools
         Magnum::SceneGraph
         Magnum::Shaders
         Magnum::DebugTools
         Magnum::AnyImageImporter
         Magnum::AnySceneImporter
         #MagnumPlugins::AssimpImporter
         MagnumPlugins::TinyGltfImporter
         MagnumPlugins::JpegImporter
         MagnumPlugins::PngImporter         
         gflags::gflags
         glog::glog
         Boost::filesystem
  PRIVATE)
```

Everything builds, however at runtime I get this error:

```
PluginManager::Manager::Manager(): none of the plugin search paths in {../PlugIns/magnum/importers, ../lib/magnum/importers, magnum/importers} exists and pluginDirectory was not set, skipping plugin discovery
PluginManager::Manager::load(): plugin AnySceneImporter is not static and was not found in 
```

**Comment by Osurac529** [comment]
I ended up figuring out my situation, we were using a version of nlohmann json that did not match the version used by TinyGltfImporter for the static build mode and it was causing crashes because two instances of the json templates do not work together, C++ thing. I did get the static build working. Never figured out how to install the conf files in the dynamic build but since I have the static working I don t need that.

**Comment by mosra** [comment]
Hey, sorry for the late reply. It's probably pointless to ask now, but did Magnum's own `install()` commands work if you don't use `EXCLUDE_FROM_ALL`? 

The `EXCLUDE_FROM_ALL` was there mainly for the use case where the main project doesn't do any install of its own, and instead only takes the final binaries from `lib/` or `bin/` inside the build directory, but if you *do want* a full build and an installation then `EXCLUDE_FROM_ALL` doesn't make sense.

**Comment by Osurac529** [comment]
I did not try without using EXCLUDE_FROM_ALL, our project setup has things setup using EXCLUDE_FROM_ALL for external things we use, we could be using things in an odd way but it works.

In the future I will keep that in mind. I'm just glad everything compiled now and does not crash and we know why it was happening. Thank you for your help!
