### ISSUE TITLE
GLTF skinning support

### ISSUE THREAD

**Issue by dsanjit** [mosra/magnum#506]
Would be great to have GLTF skinning support so that we can import skinned game characters.

**Comment by mosra** [comment]
Hi! 

most of the building blocks should be in place, the only major missing piece right now is support in builtin shaders, so you have to make your own shader. But besides that:

- [TinyGltfImporter](https://doc.magnum.graphics/magnum/classMagnum_1_1Trade_1_1TinyGltfImporter.html#Trade-TinyGltfImporter-behavior-meshes) is capable of importing arbitrary attributes, including the skinning ones, so it's just that they're not directly available via some convenience API
- Skeleton animations are imported
- Skins are fully imported as well

Shader support is sketched out in #444, but not merged yet. My focus is currently somewhere else, so I can't give any promise when full builtin support would land.

**Comment by hsdk123** [comment]
Hi, this issue seems to have been open for more than a year now - just an extra +1 in hopes this gets picked up. It's difficult to produce any standard 3d rpg-like game without this, and it would be great to have a default in magnum.

**Comment by mosra** [comment]
This is now implemented:

- Generic joint IDs / weights attribute in 7f94a6f914c834e0d693cf2a8d62eb1d40492699
- `Trade::MeshData` support in f447e994d271c8688da3cf7f04a1a2643f42cc21
- Builtin Flat, Phong and MeshVisualizer support in 89a6eb22def083c4907add7d007184d868d27cd2
- `MeshTools::compile()` support in c026ac1cb5733c951e24d85868c742eb258e55dd
- `AssimpImporter` support in mosra/magnum-plugins@19af6b8f8a57b2e49c2944261a439167bf7a0ec7 (with the original way of importing as custom attributes kept as well for compatibility)
- `GltfImporter` support in mosra/magnum-plugins@cf9c300a3063c832c31ed7a72f5a805c2b93c358 (with the original way of importing as custom attributes kept as well for compatibility)

Apart from shader tests, which show full usage of these APIs, a practical usage will be in the `magnum-player` executable in Magnum Extras, which I'll push soon. I'll also add a usage snippet into the documentation, but probably won't have time for a self-contained example app.

**Comment by hsdk123** [comment]
This is absolutely great!! Thank you!! Looking for the `magnum-player` example as well!

**Comment by mosra** [comment]
Very high-level docs here: https://doc.magnum.graphics/magnum/shaders.html#shaders-usage-skinning

The [magnum-player](https://doc.magnum.graphics/magnum/magnum-player.html) executable is now updated for skinning support, https://github.com/mosra/magnum-extras/commit/673038dec812ccf4f68e93d9795584a76a55e6f1 contains all changes that were needed to import the skins and hook them up with the (already present) animation system. I'm afraid I won't be able to make a standalone example anytime soon, so feel free to reach out on Gitter if you run into issues implementing skinning in your project ;)

**Comment by hsdk123** [comment]
This is like an early Christmas present! Thanks, will definitely ask questions as I implement this, thank you for all the work!
