### ISSUE TITLE
Android primatives example does not render

### ISSUE THREAD

**Issue by mgood7123** [mosra/magnum#515]
https://doc.magnum.graphics/magnum/examples-primitives.html does not render on android but does render on Desktop

however https://doc.magnum.graphics/magnum/examples-triangle.html does render on android

why could this be and how can i find out what is going wrong?

https://github.com/mosra/magnum/issues/514#issuecomment-857623574 may be useful

Cube

```C++
    class Cube: public Crafter::Package {
    public:
        CRAFTER_PACKAGE_CONSTRUCTOR_WRAPPERS_HPP(Cube);
        void setup() override;
        void drawEvent() override;
        void mousePressEvent(MouseEvent& event) override;
        void mouseReleaseEvent(MouseEvent& event) override;
        void mouseMoveEvent(MouseMoveEvent& event) override;

        Magnum::GL::Mesh _mesh;
        Magnum::Shaders::PhongGL _shader;

        Magnum::Matrix4 _transformation, _projection;
        Magnum::Color3 _color;
    };

void Crafter::Packages::Cube::setup() {
    GL::Renderer::enable(GL::Renderer::Feature::DepthTest);
    GL::Renderer::enable(GL::Renderer::Feature::FaceCulling);

    Trade::MeshData cube = Primitives::cubeSolid();

    GL::Buffer vertices;
    vertices.setData(MeshTools::interleave(cube.positions3DAsArray(),
                                           cube.normalsAsArray()));

    std::pair<Containers::Array<char>, MeshIndexType> compressed =
            MeshTools::compressIndices(cube.indicesAsArray());
    GL::Buffer indices;
    indices.setData(compressed.first);

    _mesh.setPrimitive(cube.primitive())
            .setCount(cube.indexCount())
            .addVertexBuffer(std::move(vertices), 0, Shaders::PhongGL::Position{},
                             Shaders::PhongGL::Normal{})
            .setIndexBuffer(std::move(indices), 0, compressed.second);

    _transformation =
            Matrix4::rotationX(30.0_degf)*Matrix4::rotationY(40.0_degf);
    _projection =
            Matrix4::perspectiveProjection(
                    35.0_degf, Vector2{windowSize()}.aspectRatio(), 0.01f, 100.0f)*
            Matrix4::translation(Vector3::zAxis(-10.0f));
    _color = Color3::fromHsv({35.0_degf, 1.0f, 1.0f});
}

void Crafter::Packages::Cube::drawEvent() {
    GL::defaultFramebuffer.clear(
            GL::FramebufferClear::Color|GL::FramebufferClear::Depth);

    _shader.setLightPositions({{1.4f, 1.0f, 0.75f, 0.0f}})
            .setDiffuseColor(_color)
            .setAmbientColor(Color3::fromHsv({_color.hue(), 1.0f, 0.3f}))
            .setTransformationMatrix(_transformation)
            .setNormalMatrix(_transformation.normalMatrix())
            .setProjectionMatrix(_projection)
            .draw(_mesh);
    swapBuffers();
}

void Crafter::Packages::Cube::mousePressEvent(MouseEvent& event) {
    // button identification is not yet handled on android
#ifndef CORRADE_TARGET_ANDROID
    if(event.button() != MouseEvent::Button::Left) return;
#endif

    event.setAccepted();
}

void Crafter::Packages::Cube::mouseReleaseEvent(MouseEvent& event) {
    _color = Color3::fromHsv({_color.hue() + 50.0_degf, 1.0f, 1.0f});

    event.setAccepted();
    redraw();
}

void Crafter::Packages::Cube::mouseMoveEvent(MouseMoveEvent& event) {
    // button identification is not yet handled on android
#ifndef CORRADE_TARGET_ANDROID
    if(!(event.buttons() & MouseMoveEvent::Button::Left)) return;
#endif

    Vector2 delta = 3.0f*Vector2{event.relativePosition()}/Vector2{windowSize()};

    _transformation =
            Matrix4::rotationX(Rad{delta.y()})*
            _transformation*
            Matrix4::rotationY(Rad{delta.x()});

    event.setAccepted();
    redraw();
}
```

**Comment by mgood7123** [comment]
I am getting no errors from magnum so it may be related to EGL initialization

**Comment by mgood7123** [comment]
> I am getting no errors from magnum so it may be related to EGL initialization 

Which returns no errors btw

**Comment by mgood7123** [comment]
i just tried this with an GLES2.0 3D cube example (uses `gl*()` ) and it works

EGL2_CUBE.h
https://gist.github.com/62ab731640791fa837b7a8d9df304d97

EGL2_CUBE.cpp
https://gist.github.com/c048143976ba60df8a3aaba36859e874

so i decided to add

```C++
void Crafter::Packages::Cube::viewportEvent(ViewportEvent &event) {
    int x = event.windowSize().x();
    int y = event.windowSize().y();
    GL::defaultFramebuffer.setViewport({{0, 0}, {x, y}});
}
```

to Cube but it did not work :(

**Comment by mgood7123** [comment]
ok, looking at https://github.com/mosra/magnum-examples/blob/ports/src/primitives/PrimitivesExample.cpp

i was missing

```C++
    _projection = Matrix4::perspectiveProjection(35.0_degf, Vector2{GL::defaultFramebuffer.viewport().size()}.aspectRatio(), 0.01f, 100.0f)*
                  Matrix4::translation(Vector3::zAxis(-10.0f));
```

**Comment by mosra** [comment]
"Dear" @mgood7123, please look at yourself in the mirror and contemplate on what have you done. 

In a course of about two weeks, you managed to open mosra/magnum#510, mosra/magnum#511, mosra/magnum#512, mosra/magnum#513, mosra/magnum#514, mosra/magnum#515, mosra/magnum#516, mosra/magnum#517, mosra/magnum#518, mosra/magnum#519 and mosra/corrade#118, commented several times on each of them, closed and opened them repeatedly, referenced them from other issues and thus generated about 2979652646 notification e-mails for everyone that's watching this repository. With no added value, all this is just noise irrelevant to anybody else using the project.

If this would be your first time, I would be *quite mad*. But given that we all witnessed the same self-centered attention grab [happening on the Gitter chat last July](https://gitter.im/mosra/magnum/archives/2020/07/22), where any other conversation was impossible amidst your code snippet carpet-bombing to the point I had to block you, I'm afraid I have to do the same here. You had enough warnings already, you didn't learn anything, and this cadence of notifications that benefit noone is *far* from being acceptable in an open-source project with a community-based support.

Bye and please never return.
