### ISSUE TITLE
relative position is not reset on android (with fix)

### ISSUE THREAD

**Issue by mgood7123** [mosra/magnum#516]
AndroidApplication.cpp
```C++
action == AMOTION_EVENT_ACTION_DOWN ? app.mousePressEvent(e) : app.mouseReleaseEvent(e);
```
```
D/magnum: relative position:  Vector(1, -2)
I/ViewRootImpl@3b7fe9e[MainActivity]: ViewPostIme pointer 1 // mouse release, position is not reset
I/ViewRootImpl@3b7fe9e[MainActivity]: ViewPostIme pointer 0 // mouse press
D/magnum: relative position:  Vector(-358, -154) // was pressed at a position different from release
```

->

```C++
if (action == AMOTION_EVENT_ACTION_DOWN) {
    app.mousePressEvent(e);
} else {
    app.mouseReleaseEvent(e);
    // reset the relative position
    // if the relative position is not reset, then
    // the relative position of mouse press will be
    // relative to the last location of mouse release
    // which differs from desktop behaviour
    app._previousMouseMovePosition = Vector2i{-1};
}
```

```
D/magnum: relative position:  Vector(1, -2)
I/ViewRootImpl@3b7fe9e[MainActivity]: ViewPostIme pointer 1 // mouse release, position is reset
I/ViewRootImpl@3b7fe9e[MainActivity]: ViewPostIme pointer 0 // mouse press
D/magnum: relative position:  Vector(0, 0) // correct relative offset
```

**Comment by mosra** [comment]
"Dear" @mgood7123, please look at yourself in the mirror and contemplate on what have you done. 

In a course of about two weeks, you managed to open mosra/magnum#510, mosra/magnum#511, mosra/magnum#512, mosra/magnum#513, mosra/magnum#514, mosra/magnum#515, mosra/magnum#516, mosra/magnum#517, mosra/magnum#518, mosra/magnum#519 and mosra/corrade#118, commented several times on each of them, closed and opened them repeatedly, referenced them from other issues and thus generated about 2979652646 notification e-mails for everyone that's watching this repository. With no added value, all this is just noise irrelevant to anybody else using the project.

If this would be your first time, I would be *quite mad*. But given that we all witnessed the same self-centered attention grab [happening on the Gitter chat last July](https://gitter.im/mosra/magnum/archives/2020/07/22), where any other conversation was impossible amidst your code snippet carpet-bombing to the point I had to block you, I'm afraid I have to do the same here. You had enough warnings already, you didn't learn anything, and this cadence of notifications that benefit noone is *far* from being acceptable in an open-source project with a community-based support.

Bye and please never return.
