### ISSUE TITLE
Windowless Android Application demo

### ISSUE THREAD

**Issue by mgood7123** [mosra/magnum#517]
https://github.com/mgood7123/Crafter

complete project demonstrating 4 rotatable Cube's

Rendered by magnum inside of a `WindowlessAndroidApplication`

Using an experimental cross platform wrapper (`Crafter::Package`), and classes designed for use with magnum gl context `EGLSurfaceView` and `EGLTextureView` 

(https://github.com/mgood7123/EGLSurfaceView-EGLTextureView)

![Screenshot_20210611-223040_Crafter.jpg](https://user-images.githubusercontent.com/26642847/121699871-ac918580-cb12-11eb-8917-ff0780f8d868.jpg)

**Comment by mosra** [comment]
"Dear" @mgood7123, please look at yourself in the mirror and contemplate on what have you done. 

In a course of about two weeks, you managed to open mosra/magnum#510, mosra/magnum#511, mosra/magnum#512, mosra/magnum#513, mosra/magnum#514, mosra/magnum#515, mosra/magnum#516, mosra/magnum#517, mosra/magnum#518, mosra/magnum#519 and mosra/corrade#118, commented several times on each of them, closed and opened them repeatedly, referenced them from other issues and thus generated about 2979652646 notification e-mails for everyone that's watching this repository. With no added value, all this is just noise irrelevant to anybody else using the project.

If this would be your first time, I would be *quite mad*. But given that we all witnessed the same self-centered attention grab [happening on the Gitter chat last July](https://gitter.im/mosra/magnum/archives/2020/07/22), where any other conversation was impossible amidst your code snippet carpet-bombing to the point I had to block you, I'm afraid I have to do the same here. You had enough warnings already, you didn't learn anything, and this cadence of notifications that benefit noone is *far* from being acceptable in an open-source project with a community-based support.

Bye and please never return.
