### ISSUE TITLE
Any way to log the matrix or vector to the console?

### ISSUE THREAD

**Issue by asmwarrior** [mosra/magnum#526]
Hi, is it possible to print/std::cout the matrix or vector?

I see there is a document says: https://doc.magnum.graphics/magnum/namespaceMagnum_1_1DebugTools.html

~~~~
std::cout << vector2 << std::endl;
std::cout << matrix4 << std::endl;
~~~~

But it looks like I can't use such tool to log the matrix or vector, any ideas?

Thanks.

**Comment by pezcode** [comment]
[Corrade::Debug](https://doc.magnum.graphics/corrade/classCorrade_1_1Utility_1_1Debug.html) (and its friends `Warning` and `Error`) is what you're looking for. Most Magnum types support being printed to them.

**Comment by mosra** [comment]
Yes, as @pezcode says :)

This wasn't really documented either, so I *finally* added an [introductory chapter with the essentials](https://doc.magnum.graphics/magnum/features.html) (83f18b23139ff53d74f936f00702bca029917e26). Thanks for pointing out the issues! :+1:

**Comment by asmwarrior** [comment]
Hi, @mosra  thanks for the quick response.

Indeed, I can use something like:
~~~~
Utility::Debug{} << _rotationPoint;
~~~~

To print the Vector `_rotationPoint` variable to the console.
