### ISSUE TITLE
[Possible Regresion] [Firefox]  [loading font] Text not displaying on linux firefox 93 and X11- since commit "f360c19426684218006933cd1f6a60851c9dcfbc" 

### ISSUE THREAD

**Issue by werto87** [mosra/magnum#538]
My project is based on this magnum example "https://doc.magnum.graphics/magnum/examples-imgui.html".
Loading a different font worked before commit "f360c19426684218006933cd1f6a60851c9dcfbc".
Code for loading a different font:
```cpp
  ImGuiIO &io = ImGui::GetIO ();
  ImVector<ImWchar> ranges;
  ImFontGlyphRangesBuilder builder;
  builder.AddText (from_u8string (std::u8string{ u8"♠♥♦♣" }).c_str ());
  builder.AddRanges (io.Fonts->GetGlyphRangesDefault ());
  builder.BuildRanges (&ranges);
  auto const fontFile = std::filesystem::path{ "bin/asset/DejaVuSans.ttf" };
  auto const fontSize = 100.0f;
  smallFont = io.Fonts->AddFontFromFileTTF (fontFile.c_str (), fontSize * 0.5f, nullptr, ranges.Data);
  bigFont = io.Fonts->AddFontFromFileTTF (fontFile.c_str (), fontSize * 0.5f * 1.2f, nullptr, ranges.Data);
  io.Fonts->Build ();
```
If I use this commit "f360c19426684218006933cd1f6a60851c9dcfbc". There is no Text in my app. I only see the special chars "♥♦♣". Note that I do not see "♠" and some of the symbols are in the wrong place.
If the code above is commented out the text works fine. 

Some Information:
Problem happens in firefox 93.0 on arch linux using X11 and on windows with firefox 93.0.
On android mobile with firefox 93.2 it crashes.
When I use chrome everything works.
Magnum console output Mozilla Firefox 93.0 on arch linux using X11:
```
Renderer: GeForce GTX 980/PCIe/SSE2 by Mozilla project.js:1:40379
OpenGL version: OpenGL ES 2.0 (WebGL 1.0) project.js:1:40379
Using optional features: project.js:1:40379
    GL_ANGLE_instanced_arrays project.js:1:40379
    GL_EXT_texture_filter_anisotropic project.js:1:40379
    GL_OES_vertex_array_object project.js:1:40379
    GL_WEBGL_draw_buffers project.js:1:40379
Using driver workarounds: project.js:1:40379
    firefox-deprecated-debug-renderer-info project.js:1:40379
    emscripten-pthreads-broken-unicode-shader-sources
```

I tried to reproduce this in a small project but it did not work. So I think the problem is loading a different font and doing something else.
[Source code of my project where the problem happens](https://github.com/werto87/game_01_client)
[Link to the broken version of my website (click on fullscreen to start)](https://modern-durak.com/)

**Comment by mosra** [comment]
(Sorry for the late reply, things piled up since.)

Glad to hear the missing text issue was caused by some bug in cxxopts and not Magnum.

> Do you have an example on how to load a font and add special letters

Unfortunately I don't, this is something that's ImGui-specific, and I don't use ImGui myself that much. If those glyphs don't get displayed, could it be that DejaVu simply doesn't have them? If the TTF file contains those, then please ask on ImGui forums instead, they'll be able to help you much better ;)
