### ISSUE TITLE
Copy paste mistake in Frustrum.h

### ISSUE THREAD

**Issue by DJQuardaboff** [mosra/magnum#545]
The second line should have `Frustum<Double>` as the type.
https://github.com/mosra/magnum/blob/a146f9f74b5224367ea6efd2f755958686a984a5/src/Magnum/Math/Frustum.h#L269-L270

**Comment by mosra** [comment]
Hi again, thank you for spotting this! Fixed in d3430f7599e6815182dd628e94addcc80b6182a5.
