### ISSUE TITLE
glDepthRange lacks sensible bindings

### ISSUE THREAD

**Issue by amras0000** [mosra/magnum#558]
It is possible to use glDepthRange and glDepthRangef without issues by way of `Magnum/External/flextGL.h `, but as far as I can tell there's no non-external reference to those functions, nor any mention of them in the docs. It's possible other functions have been missed, but this is the only missing pair I've run into.

I believe there should be a `GL::Renderer::setDepthRange(double, double)` and `(float,float)`.

**Comment by mosra** [comment]
Yeah, not everything from GL is exposed. [A complete list of the incompletely exposed APIs is here.](https://doc.magnum.graphics/magnum/opengl-mapping.html)

I'll look into this when I find time, another such candidate is in #543. And you're right, at the moment it's no problem using the raw GL APIs directly.

**Comment by mosra** [comment]
Exposed in bede836077af1bd67ee6e501d797dbf7ac7f1842, and the NV variant that doesn't clamp in 56a850f9ad24f9db23f54fb080b5fbfc68a390d2.
