### ISSUE TITLE
Can vcpkg be used to install a later version of magnum?

### ISSUE THREAD

**Issue by eladmaimoni** [mosra/magnum#562]
Currently vcpkg points to magnum version 2020.06. I would like to use some of the new functionality such as transformations on MeshData.

I tried installing magnum using the --head option but it failed.

`vcpkg install magnum --triplet=x64-windows-static-md --head`

So is it somehow possible to use a later release? will there be a new release to vcpkg soon?

**Comment by mosra** [comment]
Latest `master` of magnum depends on latest `master` of corrade, meaning you have to install *both* with `--head`. Vcpkg itself isn't clever enough to do that on its own, so you have to do that explicitly:

```bat
vcpkg install corrade magnum --triplet=x64-windows-static-md --head
```

And do the same also when you'd eventually want upgrade to a newer Git revision. Or when you install other parts of the project, like plugins, you have to (re)install `corrade`, `magnum` *and* `magnum-plugins` with `--head`. ([Doc link just for completion.](https://doc.magnum.graphics/magnum/building.html#building-packages-vcpkg) Yes, yes, TL;DR on steroids as you said in #561, I know, sorry, will try to cut down on the context on that page, when I get time.)

Next release will happen eventually, it's tracked in #453.
