### ISSUE TITLE
Feature Request: Support std::stop_token as optional parameter to Sdl2Application::exec()

### ISSUE THREAD

**Issue by jonesmz** [mosra/magnum#566]
See: https://en.cppreference.com/w/cpp/thread/stop_token

And Sdl2Application::exec() is implemented as follows:
```
int Sdl2Application::exec() {
    #ifndef CORRADE_TARGET_EMSCRIPTEN
    while(mainLoopIteration()) {}
    #else
    emscripten_set_main_loop_arg([](void* arg) {
        static_cast<Sdl2Application*>(arg)->mainLoopIteration();
    }, this, 0, true);
    #endif
    return _exitCode;
}
```

It would be nice, if Magnum was compiled with C++20, to have the ability to pass an std::stop_token into the exec() function as an additional way to terminate.

This would be an alternative to calling Sdl2Application::exit();

The motivation behind this feature request is to support slightly better encapsulation, where an application that has a threadpool, holding one or more `std::jthread` objects may not want to have the threadpool code aware of special rules to shutdown the threads, allowing instead for the std::stop_token to be respected directly for a pool-wide graceful shutdown.

**Comment by mosra** [comment]
Not planned, use `mainLoopIteration()` directly instead.
