### ISSUE TITLE
MSVC 2019 compile error C2440 with DrawableGroup3D

### ISSUE THREAD

**Issue by asmaloney** [mosra/magnum#646]
I have some code working on macOS that I'm now trying to compile using MSVC 2019.

I have a declaration in a class:
```cpp
Magnum::SceneGraph::DrawableGroup3D mDrawables;
```

I am including `SceneGraph/SceneGraph.h` & `SceneGraph/FeatureGroup.h`.

I'm getting this:

```
Magnum/SceneGraph/FeatureGroup.h(177,1): error C2440: 'static_cast': cannot convert from '_Ty' to 'Feature &' [build\debug\lib\mglLib.vcxproj]
          with
          [
              _Ty=Magnum::SceneGraph::AbstractFeature<3,Magnum::Float>
          ]
          and
          [
              Feature=Magnum::SceneGraph::Drawable<3,Magnum::Float>
          ]
Magnum/SceneGraph/FeatureGroup.h(177,65): message : static_cast and safe_cast to reference can only be used for valid initializations or for lvalue casts between related classes [debug\lib\mglLib.vcxproj]
Magnum/SceneGraph/FeatureGroup.h(176): message : while compiling class template member function 'Magnum::SceneGraph::FeatureGroup<3,Magnum::SceneGraph::Drawable<3,Magnum::Float>,Magnum::Float>::~FeatureGroup(void)'[build\debug\lib\mglLib.vcxproj]
Widget_p.h(66): message : see reference to class template instantiation 'Magnum::SceneGraph::FeatureGroup<3,Magnum::SceneGraph::Drawable<3,Magnum::Float>,Magnum::Float>' being compiled [debug\lib\mglLib.vcxproj]
```

Using:
- latest magnum (86e7dd51f3e42a754635c17361ac35c8bdd74de7)
-  Visual Studio 2019 Developer Command Prompt v16.11.32
-  Windows SDK version 10.0.20348.0

Somehow it doesn't know these classes are related. Am I missing another include or something?

**Comment by mosra** [comment]
Does it go away if you `#include <Magnum/SceneGraph/Drawable.h>`?

Just FYI, the `SceneGraph.h` (and similar namespace-level includes elsewhere) is containing forward declarations only, contrary to the "give me everything" approach in other libraries. Include directives for each particular type are shown in the docs.

**Comment by asmaloney** [comment]
Got it. Thanks!

I think my brain was like: "It compiles on macOS/clang, so it _must_ be something with MSVC (it usually is). Let's try to pick apart the template error."

Rather than: "Am I _sure_ I'm including the right stuff?" 😁
