### ISSUE TITLE
Grabbing depth information from non-default framebuffer.

### ISSUE THREAD

**Issue by TrevorCash** [mosra/magnum#647]
Hello,

I am running a simple example where I have a non-default framebuffer with a renderbuffer attachement (depth+stencil).

I am using the code from the mouse interaction example to read depth at a given pixel coord.

I am not sure what I would use for the mapForRead() function, as the GL::DefaultFramebuffer::ReadAttachment::Front does not work in this case.

I have also just tried binding the framebuffer and calling glReadPixels(fbPosition.x(), fbPosition.y(), 1, 1, GL_DEPTH_STENCIL, GL_UNSIGNED_INT_24_8, (void*) & readData);

But I do not seem to be getting any data from that.

Any Help Appreciated.

Thanks - Trevor

**Comment by mosra** [comment]
Hi,

it should be enough to `read()` with a depth format that doesn't make the driver angry. See my response at https://github.com/mosra/magnum/issues/643#issuecomment-2239423002 for why `mapForRead()` isn't needed in this case. I'm not sure if reading combined depth + stencil formats is at all possible, would need to check the spec, but reading just the depth component alone or the stencil component alone should work I think?

If that doesn't work either, are you getting any GL errors? If you're using one of the builtin application classes and are on Windows or Linux, you can pass `--magnum-gpu-validation on` on the command line to get a GL debug output that might show more detailed info if a GL error is indeed happening.

**Comment by TrevorCash** [comment]
Thanks, I was able to get single pixel read with this code in my depthAt function.

```
        Image2D data = sceneRenderFrameBuffer->read(
            Range2Di::fromSize(fbPosition, Vector2i{ 1 }).padded(Vector2i{ 0 }),
            { GL::PixelFormat::DepthComponent, GL::PixelType::Float });
        auto size = data.pixels().size();

        return *((float*)data.pixels().data());
```

**Comment by mosra** [comment]
A bit of code golf just in case (the examples badly need some refresh...):

```cpp
        Image2D data = sceneRenderFrameBuffer->read(
            Range2Di::fromSize(fbPosition, Vector2i{ 1 }),
            { PixelFormat::Depth32F });
        auto size = data.pixels().size();

        return data.pixels<Float>()[0][0];
```

Getting the stencil would then have to be done in a second read, with `PixelFormat::Stencil8UI`, querying pixels as `UnsignedByte`.

**Comment by TrevorCash** [comment]
Thanks - Thats more readable.  Updated
