### ISSUE TITLE
AnyImageImporter doesn't detect in-memory .hdr files with RGBE magic signature

### ISSUE THREAD

**Issue by pezcode** [mosra/magnum#652]
HDR images can have [two different magic signatures](https://github.com/nothings/stb/blob/2e2bef463a5b53ddf8bb788e25da6b8506314c08/stb_image.h#L7097) but `AnyImageImporter` only [checks for one of them](https://github.com/mosra/magnum/blob/cf3ed8f6a59ad0693878a6824ee36d03c2c20a7f/src/MagnumPlugins/AnyImageImporter/AnyImageImporter.cpp#L219) when loading from memory

**Comment by mosra** [comment]
Someone should update Wikipedia with that, heh. Doesn't help that stb_image doesn't track that to any source, and that the `file` utility doesn't recognize that signature either. The only code I found that actually uses it is https://www.graphics.cornell.edu/~bjw/rgbe/rgbe.c

I'm adding the detection but is there a chance you have a sufficiently small file (few kB) to add as a test case?

**Comment by pezcode** [comment]
Yeah sure, this is the test file that triggered this for us:

[spree_bank_32x16.zip](https://github.com/user-attachments/files/17677758/spree_bank_32x16.zip)

The tool that produced it is https://github.com/kopaka1822/ImageViewer/

**Comment by mosra** [comment]
Ha, yes, the tool seems to be using exactly that bit of code as I linked. Commited as f91638c461852101df6e50b73f642b644d769bf1.

**Comment by pezcode** [comment]
Thanks ☺️
