### ISSUE TITLE
Dropping EXT_direct_state_access support

### ISSUE THREAD

**Issue by mosra** [mosra/magnum#81]
When [ARB_direct_state_access](https://www.opengl.org/registry/specs/ARB/direct_state_access.txt) support gets more widespread, I'm considering dropping support for the old and messy [EXT_direct_state_access](https://www.opengl.org/registry/specs/EXT/direct_state_access.txt) extension. The reasons are:
- `EXT_direct_state_access` is supported only on binary AMD, NVidia and (small subset of) Intel drivers for Windows and Linux. It isn't available on OSX and not implemented in Mesa. And because it's obsoleted by the ARB version, there won't be any new implementations.
- It contains sheer amount of deprecated functionality, which bloats GL headers.
- Everything is basically duplicated and thus, along with the non-DSA version, there are three different code paths to test.
- Weird "create on first use" design philosophy, which adds unnecessary complexity.
- It has many late additions and missing functionality equivalents (#77, no way to blit framebuffers the DSA way etc.)
- Bad interaction with `ARB_robustness` (it's possible to do things either DSA or robust way, not both)

Things to finish in the engine:
- [x] Port Mesh class to the new `ARB_vertex_attrib_binding` so we can use `ARB_DSA` functions

I'll drop the support when the ARB version is available also in AMD drivers so ~~all~~ both vendors that had EXT version have a replacement.

**Comment by ethan-tqa** [comment]
Does this restrict you to 4.5 or you can call ARB version of the functions in 4.4 and below?

**Comment by mosra** [comment]
Yes, you can use the functions on any driver that supports ARB_direct_state_access.

If the driver supports version 4.5 it just means that you can use the extension without having to check for its presence.

**Comment by mosra** [comment]
`GL::Mesh` is switched to use ARB_DSA in 21b2cac95364e44d40f826b60fbaddbf4372fbf3 (which uncovered a bug on Intel Windows drivers, see 094ea1bbd08a68741aecee3290992b8e18c90c1b), EXT_DSA is finally dropped in 572b64bb5cf027338f47c39c79e12ecb78103f15, resulting in 2k LOC being deleted. Yay! :tada:
