### ISSUE TITLE
Adding feature clarity of memory management

### ISSUE THREAD

**Issue by wivlaro** [mosra/magnum#86]
Adding a non-inherited feature to an object requires doing this at the moment:

```new MyFeature(*containingObject);```

This looks like the application programmer has to memory-manage the new feature theirself. While it is possible (i.e. you can manually destruct the feature before object, but not before) and sometimes convenient, the API itself does not suggest that containingObject will destroy its features on destruction.

I would suggest adding a method `T& AbstractObject::addFeature<T>(arg1,arg2,...argn)` that calls constructor `new T(*this, arg1, arg2... argn)`, which gives the impression of the object managing the feature, as it does.

As features always *require* an object on construction, it would be a logical addition.

**Comment by mosra** [comment]
:+1: yup, good idea.

If I remember correctly, someone suggested doing similar thing also for object children, because (in terms of memory management) they are behaving the same -- `T& Object::addChild<T>(args...)`. Can't find the original discussion, though.

I'll think that through in regards to planned "data-oriented" improvements to see if these two ideas can play well together. The ultimate goal is to get rid of naked pointers and `new`s completely.

**Comment by LB--** [comment]
I second the suggestion :+1:

**Comment by mosra** [comment]
One potential problem came across my mind:

- The `AbstractObject::addFeature<F>(args...)` function would call `new F{*this, args...}` and thus assume that `F`'s constructors always have `AbstractObject&` (or some derived type) as *first* argument.
- Similarly, the `Object::addChild<O>(args...)` function would call `new O{args..., this}` and thus assume that `O`'s constructors always have `Object*` (or some derived type) as *last*, possibly optional argument.

Although the above argument order is probably common practice (is it?), these functions would add constraints on feature and object constructors, which might be annoying in some cases.

Looking for inspiration into the STL, `std::tuple` has [a special constructor](http://en.cppreference.com/w/cpp/utility/tuple/tuple) taking `std::allocator_arg_t` *tag* as first argument to indicate that the user wants to specify also an allocator in addition to initializers for all the tuple elements.

Thoughts?

**Comment by wivlaro** [comment]
Maybe it would be easier if the Feature's object was not required to be set in the constructor. I had thought that a good practise was to have the [constructor should do as little as possible](http://stackoverflow.com/questions/293967/how-much-work-should-be-done-in-a-constructor). But this would break the contract that a Feature *always* has an object.

As an example, if we ever added some kind of callbacks or hooks for when features are added/removed it would open up a world of pain whereby application code could be run (and throw exceptions from) constructors.

The alternative is requiring a sub-classed feature's constructor to conform to some kind of contract, or require an allocator interface.

I think I'd personally prefer to be able to attach Features to Objects later than construction, as with the Object parent->child relationship. It opens up the possibilities of: more flexible Feature pooling; effectively enabling/disabling features; remove logic from my own constructors. 

Googling around for some precedent, maybe this would provide some inspiration:

https://github.com/alecthomas/entityx#creating-components

**Comment by LB--** [comment]
> and thus assume that `F`'s constructors always have `AbstractObject&` (or some derived type) as _first_ argument.

The classes are being designed to implement and interface. Even the compiler will let people know when they have done something wrong. If someone is making such a class they have already agreed to adhere to the design pattern.

**Comment by mosra** [comment]
Done in 7fc31139e2f1cc03d7503e43b705cfbe64dbaaf6. Sorry about everything taking so long.
