### ISSUE TITLE
MSVC 2015 port

### ISSUE THREAD

**Issue by mosra** [mosra/magnum#96]
Support for MSVC 2013 is currently only in `compatibility` branch. I want to support MSVC 2015 in `master` to make users' lives easier (more frequent updates, less ugly workarounds...).

Stuff that was worked around in `compatibility` branch with ugly hacks and is known to be fixed/implemented in MSVC 2015:

- `char32_t` etc. are no longer typedefs to `unsigned int` etc.
- no need to use `std::array` to work around [array initialization bug](https://connect.microsoft.com/VisualStudio/feedback/details/792161/constructor-initializer-list-does-not-support-braced-init-list-form)
- unrestricted unions
- user-defined literals
- non-static data member initializers
- `noexcept`, `constexpr`
- `__func__` (used in `Corrade::TestSuite`)
- `std::chrono::high_resolution_clock` is now [really high-resolution](https://connect.microsoft.com/VisualStudio/feedback/details/719443/)

Bugs/annoyances which might still be present:

- [x] the need to explicitly specify type when calling `addTests()` in `Corrade::TestSuite`
- [x] more explicit typing needed for list-initialization in comparison with GCC/Clang
- [ ] it is not possible to have multiple definitions of template alias (unlike `typedef`s)

There's still one thing left that makes the port currently impossible:

- [x] It is not possible to initialize arrays in `constexpr` constructors (see Known Issues [in this blog post](http://blogs.msdn.com/b/vcblog/archive/2015/04/29/c-11-constant-expressions-in-visual-studio-2015-rc.aspx)). I'm using this rather heavily in *all* `Vector` and `Matrix` classes and thus the port would be far from clean. The blog post says that these bugs should be fixed in the final release or first update, so let's wait until that.

**Comment by mosra** [comment]
The `constexpr` issue [is fixed now](http://blogs.msdn.com/b/vcblog/archive/2015/06/02/constexpr-complete-for-vs-2015-rtm-c-11-compiler-c-17-stl.aspx), so nothing should stop me from doing the port when the final version is released.

**Comment by mosra** [comment]
To be released on [2015-07-20](http://blogs.msdn.com/b/somasegar/archive/2015/06/29/save-the-date-visual-studio-2015-rtm-on-july-20th.aspx).

**Comment by mosra** [comment]
Current state (master on 20e5d9512f80c7494b45da399106e9c2c3b31887): stuck on `constexpr` bugs and meaningless errors which were completely okay in 2013. I made some minor changes to the buildsystem and worked around some silly {}-initialization-related bugs, will commit that to have things in clean state for further experiments.

* `Corrade::Interconnect` library is completely unusable (the tests can't even compile), will investigate further. Probably my fault, because the library had some issues even on 2013. Without tests the rest compiles with some minor changes.
* `Math::RectangularMatrix` compilation stops on the following:

    > [Math/RectangularMatrix.h(111)](https://github.com/mosra/magnum/blob/20e5d9512f80c7494b45da399106e9c2c3b31887/src/Magnum/Math/RectangularMatrix.h#L111): error C2476: 'constexpr' constructor does not initialize all members

    Removing `constexpr` might work, but then what's the point of that?! Minimal repro case which compiles fine on GCC/Clang but fails with crazy errors on MSVC 2015 (check the [online compiler](http://webcompiler.cloudapp.net/)). Isn't this related to the array initialization error they promised to fix in the final version? YES IT IS.

    ```cpp
    struct A {};

    struct B {
        constexpr B(): _a() {}
        
        A _a[4];
    };
    ```

* `Math::Vector` compilation stops on the following:

    > [Math/Vector.h(177)](https://github.com/mosra/magnum/blob/20e5d9512f80c7494b45da399106e9c2c3b31887/src/Magnum/Math/Vector.h#L177): error C2476: 'constexpr' constructor does not initialize all members

    Similar to the above, can be worked around by removing `constexpr` keyword. Again, what's the point of having MSVC 2015 support if I can't use `constexpr` at all? Minimal repro case:

    ```cpp
    struct Foo {};
    
    struct A {
        constexpr A(Foo): _i() {}
    
        constexpr A(): A(Foo()) {}
    
        int _i;
    };
    ```

* `SceneGraph::AbstractFeature` fails with the following: 

    > [SceneGraph/AbstractFeature.h(76)](https://github.com/mosra/magnum/blob/20e5d9512f80c7494b45da399106e9c2c3b31887/src/Magnum/SceneGraph/AbstractFeature.h#L76): error C2653: 'CachedTransformations': is not a class or namespace name

    Don't know what's causing this, I'm suspecting the parser went haywire for some unknown reason (yet another `windows.h` collision? misplaced whitespace? bad moon phase?). Also not present on MSVC 2013. Will investigate further in this case, because this is pathetic.

* More funny stuff:

    > [Implementation/FramebufferState.h(36)](https://github.com/mosra/magnum/blob/20e5d9512f80c7494b45da399106e9c2c3b31887/src/Magnum/Implementation/FramebufferState.h#L36): error C4579: 'Magnum::Implementation::FramebufferState::DisengagedViewport': in-class initialization for type 'const Magnum::Range2Di' is not yet implemented; static member will remain uninitialized at runtime but use in constant-expressions is supported

    > [AbstractTexture.cpp(222)](https://github.com/mosra/magnum/blob/20e5d9512f80c7494b45da399106e9c2c3b31887/src/Magnum/AbstractTexture.cpp#L222): error C2143: syntax error: missing ';' before '}'

    > ... (rage quit)

Any ideas what to do next? Wait for the next bugfix update? I don't want to replace every other `constexpr` with some crazy `CONSTEXPR_ONLY_IF_WE_ARE_ON_SANE_COMPILER` macro. That stuff doesn't belong in master.

**Comment by mosra** [comment]
Initial work-in-progress MSVC 2015 support is now in master (no, it's not usable yet). 

AppVeyor now has MSVC 2015 so I set up the builds for master branch too. Click the badges below to see the funny errors in action:
- Corrade -- [![Build status](https://ci.appveyor.com/api/projects/status/afjjlsgtk6jjxulp/branch/master?svg=true)](https://ci.appveyor.com/project/mosra/corrade/branch/master)
- Magnum -- [![Build status](https://ci.appveyor.com/api/projects/status/5b477m034cfaskse/branch/master?svg=true)](https://ci.appveyor.com/project/mosra/magnum/branch/master)

**Comment by mosra** [comment]
Related bug reports, forums etc:
- [C++ – constexpr does not work with delegating constructors](https://connect.microsoft.com/VisualStudio/feedback/details/1579279/c-constexpr-does-not-work-with-delegating-constructors)
- https://www.reddit.com/r/cpp/comments/3g3aa1/what_do_you_want_to_see_in_vs_2015_update_1/

**Comment by LB--** [comment]
Is the CI up to date? I was able to build and install Corrade with Visual Studio 2015 without issue.

**Comment by mosra** [comment]
Yes, it is. Corrade works if you don't enable tests and don't use Interconnect library.

The CI builds Corrade with tests enabled, which test also the Interconnect library and thus the build fails. Apparently MSVC 2015 has some backward incompatibilites so that everything that passed silently or with warning in 2013 now ends with an error.

**Comment by mosra** [comment]
Got Corrade building now even with tests. It forgot what it knew in 2013 and template deduction for variable templates is broken now.

With `Magnum::SceneGraph`, MSVC 2015 lost it completely when encountering template aliases. Having `template<class T> using Something = SomethingOther<T>` somewhere in the code causes it to forget random type and variable definitions at random places (even in its own internal headers!!) with no error/warning message at all. Ugh. This can't be real.

Without `Magnum::SceneGraph` it somewhat compiles now (with a lot of nasty workarounds). Didn't have the courage to run the tests. 

Will commit the less ugly changes to get it in somewhat usable state.

**Comment by mosra** [comment]
Done as part of being mad while fixing #109 ([commit log](https://github.com/mosra/magnum/compare/8c2eaea406b35dcf9caa41cddc6eb845ca052f82...69949b991ad308e374a1c395f9f957a4de65eac7)).
