### ISSUE TITLE
Re-enable glDrawRangeElements() on WebGL 2 when it actually works

### ISSUE THREAD

**Issue by mosra** [mosra/magnum#97]
Currently, the `glDrawRangeElements()` WebGL 2 function is not implemented in Firefox (38) and causes ["Not Implemented." assertion](https://hg.mozilla.org/mozilla-central/file/d44425c6730c/dom/canvas/WebGL2ContextDraw.cpp#l18). It is also not yet implemented in Emscripten, but I have [a patch that adds it](https://github.com/mosra/emscripten/commit/97388539c5e9cea509ca270b1d6aa0bbe18e64b7).

Related [Mozilla bug](https://bugzilla.mozilla.org/show_bug.cgi?id=898475).

So it is now [disabled in Mesh::draw() code](https://github.com/mosra/magnum/commit/4ce28752626102a2acfcc8a72e057eb2e86b4ad4) until stable Firefox implements it, then it should be added to Emscripten and then re-enabled here for performance reasons.

On the other hand, in the [draft WebGL 2 specification](https://www.khronos.org/registry/webgl/specs/latest/2.0/#3.7) there is the following comment that might possibly cause the function to be removed from the final specification:

> ``` cpp
> /* TODO(kbr): argue against exposing this because it can't safely
>    offer better performance than drawElements */
> void drawRangeElements(GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, GLintptr offset);
> ```

Making this into an issue so I don't forget the particulars.

**Comment by mosra** [comment]
Related discussion: https://twitter.com/kamidphish/status/641366351001419777

**Comment by Squareys** [comment]
The [Related mozilla bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1202427) has been fixed, right?

**Comment by mosra** [comment]
yup, and moreover is also patched over / ignored in emscripten in a similar way: https://github.com/kripken/emscripten/blob/6dc4ac5f9e4d8484e273e4dcc554f809738cedd6/src/library_gl.js#L7361 so I guess this is safe to enable now

**Comment by mosra** [comment]
Workaround reverted in f6ba4111e1669b254da8f0dafdbb5d9cb6df364a.

**Comment by Skylion007** [comment]
@mosra Is it okay to put this. back now?

**Comment by mosra** [comment]
Based on what I read when investigating this, it seems that the API doesn't improve anything on current GPUs anymore (another evidence supporting this is that Vulkan doesn't have any way to specify inde range), and so I'm thinking about going the other way instead, and stop using `DrawRangeElements` altogether. It would make the internals simpler and reduce the amount of public APIs overloads.

**Comment by mosra** [comment]
`glDrawRangeElements()` is enabled on WebGL 2 again in 9ec7f26fae3f6e7f6461c086db0134bb721f25c1. Hopefully, after three reverts, this is the last time this particular piece of code gets touched.
